### ISSUE TITLE
Tag tracking+: not working for tag containing a "/"

### ISSUE THREAD

**Issue by 130G** [AprilSylph/XKit-Rewritten#1007]
### Platform

Ubuntu 20.04

### Browser

Firefox 109.0.1 (64-bit)

### Addon version

v0.21.1 (Beta)

### Details

If a tag containing a "/" is followed, the Tag Tracking+ feature doesn't update the number of new posts (on the dashboard and the search bar). Also, clicking on the tag in the dashboard's sidebar redirects to the error page.

Probably because "/" is not translated to "%2F"

Random example: [Searching "my/art" tag](https://www.tumblr.com/tagged/my%2Fart?sort=recent) vs [clicking on "my/art" tracker on dashboard](https://www.tumblr.com/tagged/my/art?sort=recent)

**Comment by marcustyphoon** [comment]
See also: #850
