### ISSUE TITLE
Reblog the same post every x days

### ISSUE THREAD

**Issue by taracdia** [AprilSylph/XKit-Rewritten#1016]
### Concept

I don't know if it's possible but it would be great to have something auto post a certain post every certain number of days. Great for day of the week posts and ides of March stuff

**Comment by marcustyphoon** [comment]
Sounds like some sort of reblog-scheduling helper. Certainly it wouldn't make sense for the extension itself to compose and submit a post/reblog every so often, I think.

My guess is that this is pretty niche; in the case of the ides of march thing you can just go and schedule the next ten years' worth of posts using Tumblr's UI in just a few minutes.
