### ISSUE TITLE
Open in Tabs: Not functional in blog card modals/blog view modals

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1019]
### Platform

MacOS 13.2.1

### Browser

Chrome 110.0.5481.177 arm64

### Addon version

master

### Details

Putting aside which URL Open in Tabs actually navigates to, as reported in #751, links to blogs in blog cards and the blog view modal are not opened in tabs at all. (Calling stopPropagation from a delegated jQuery `on` handler, for whatever reason, doesn't cancel redpop's soft navigation.)

**Comment by AlecBlance** [comment]
It's been a head scratcher for me also but, what works is MutationObserver. There we can detect if the anchor is added, then attach a click event listener. This adds more processes though.

**Comment by marcustyphoon** [comment]
The extension's `pageModifications` utilities make that sort of thing pretty easy! Check out... well, any of the scripts that use it, but let's say the "boring tag chiclets" file in AccessKit, for example; that one is a pretty simple demo.

**Comment by AlecBlance** [comment]
Wow! I just checked it, and I'm blown away. It works right off the bat. Thanks for this! I'll definitely take my time familiarizing everything in here.
