### ISSUE TITLE
Quote Replies: Buttons not shown in Kiwi Browser

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1030]
### Platform

Android 8.0.0

### Browser

Kiwi Browser 107.0.5304.74

### Addon version

v0.21.4

### Details

Despite the changes in #900, I do not observe Quote Replies buttons appearing next to mentions on the activity page in Kiwi Browser unless I tap the mention.

This:
 - needs confirmation
 - may very well be a Kiwi Browser bug; we could choose to mitigate it or wontfix it if so.

**Comment by AprilSylph** [comment]
If Kiwi Browser is matching `@media (hover: hover)` when your primary pointing device can't hover, that is by definition a Kiwi Browser bug.
