### ISSUE TITLE
Tweaks: Hide recommendations on the dashboard and/or at the end of tag search

### ISSUE THREAD

**Issue by asshuka** [AprilSylph/XKit-Rewritten#106]
![210325_02-48-15](https://user-images.githubusercontent.com/80346620/112374439-ac080080-8d14-11eb-8da6-bee034b106cb.png)
why have they done this

**Comment by AprilSylph** [comment]
> why have they done this

feature parity with the mobile apps

**Comment by AprilSylph** [comment]
closed by ea92736f96f6c4d5ffee31300bc3220148bd5d19
