### ISSUE TITLE
Meatballs util: visual weirdness with long menu items

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1066]
### Platform

MacOS 13.2.1 arm64

### Browser

Chrome 112.0.5615.137

### Addon version

all of my non-draft PRs (yes, this is not—as far as I know—easily observable in the current release since none of our meatballs items are long enough, but it is with font size adjustments, such as from Palettes for Tumblr)

### Details

<img width="285" src="https://user-images.githubusercontent.com/8336245/237014706-2c2a52b9-94bc-4dc3-8eef-7c0aab611670.png">

I love pseudo elements.

Requires a rewrite of #1063 (inline pseudo or just adding the label to the DOM instead; preference?) or tweaks to #1065 if it replaces it.

**Comment by AprilSylph** [comment]
looks like this should be as simple as removing `display: flex` and related properties from our meatballs CSS
