### ISSUE TITLE
Tumblr Live carousel broken again

### ISSUE THREAD

**Issue by gnollhide** [AprilSylph/XKit-Rewritten#1075]
### Platform

Ubuntu Linux

### Browser

Firefox flatpak version 113.0.2 64bit

### Addon version

v0.21.7 (beta)

### Details

As of May 25, 2023 the tumblr live thing at the top of the dashboard is back, with multiple small square blogs that are live. Disabling and re-enabling the tweak itself or the full tweak addon doesn't make a difference, refreshed or not.

**Comment by SophieScott12** [comment]
This is still an issue on Firefox on Windows 10 as of now, 30 May 2023

**Comment by marcustyphoon** [comment]
Yep! We've submitted the update to Mozilla already, but lately they've been taking a while to approve our updates.
