### ISSUE TITLE
Quick Tags bundles doesn't appear at all

### ISSUE THREAD

**Issue by LugiaDepression** [AprilSylph/XKit-Rewritten#1078]
### Platform

Windows 7 Ultimate

### Browser

Firefox 104.0.2

### Addon version

v0.21.7

### Details

I've looked over and the Quick Tags bundles I added doesn't show up for me, not in the basic, not in the legacy post creator, not in new posts neither reblogs. The help tutorial says I need to enabled the beta post editor for Quick Tags to work but I have no idea what's that or where I can find it. Where tumblr support said I can find it I only see the legacy editor thing, but it sure neiter post maker shows my bundles I made.

**Comment by marcustyphoon** [comment]
You need to turn the legacy editor switch off (this requires your browser window to be wide enough), and then this icon should appear. Does your post editor not look like this?

<img width="990" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/6c86d5e7-c8ea-4be3-a314-ad37b7384192">

Additionally, in the XKit Rewritten preference pane, is the blue switch at the right side of the Quick Tags entry on?

<img width="377" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/b56ab9dd-de29-41b6-96b3-388d8d8e307c">
