### ISSUE TITLE
Restore 'delete' and 'edit' buttons to the footer of posts.

### ISSUE THREAD

**Issue by Westcoastal** [AprilSylph/XKit-Rewritten#1080]
### Concept

As described in the title, restore the 'edit' and 'delete' buttons to the footer of the post where they've always been, rather than in the context menu for a post.

**Comment by marcustyphoon** [comment]
Off the top of my head, I think you're referring to an experiment, though I could be wrong. If it is, we'd wait for any change to be finalized before considering playing with it.

**Comment by Westcoastal** [comment]
I don't think it's an experiment. They moved 'delete' and 'edit' into the three-dot menu on desktop.

**Comment by AprilSylph** [comment]
I'm still seeing delete and edit buttons in the post footer...

**Comment by AprilSylph** [comment]
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/28949509/82ee01b2-acfa-4a0e-be36-2197170176b7)

I've also not seen anyone else, inside or outside of Tumblr, talk about this. Do you still not see these buttons when you e.g. have no extensions enabled?
