### ISSUE TITLE
Mass Unliker has no effect

### ISSUE THREAD

**Issue by sleepycadets** [AprilSylph/XKit-Rewritten#1088]
### Platform

Windows 10

### Browser

Firefox 113.0.2 (64-bit)

### Addon version

v0.21.8

### Details

When toggling Mass Unliker, my like number does not change. It has been several minutes, and several attempts on different pages of Tumblr. it also seems like there's supposed to be a confirmation dialogue, which does not pop up.

**Comment by marcustyphoon** [comment]
You can use the `?` button next to a script to see its help page on the wiki!

> This script adds a button to the sidebar on the Likes page which, when clicked, prompts you to clear your likes. If confirmed, all your likes will be fetched via the Tumblr API and then unliked one at a time, at a maximum rate of 1 per second.

https://github.com/AprilSylph/XKit-Rewritten/wiki/Features#mass-unliker

**Comment by sleepycadets** [comment]
I have seen that. thats how i knew it was supposed to prompt me.

**Comment by marcustyphoon** [comment]
Gotcha. So are you seeing this button on the likes page:

<img width="1058" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/12d1835d-665d-4f88-ba8b-573a0a1c89db">

And getting this dialogue box when clicking it?

<img width="1058" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/80943079-38a2-48ef-b774-5a7024019d6d">

**Comment by sleepycadets** [comment]
,,ah. i didn't know it made something new appear on tumblr itself. thank you very much, i feel very silly.

**Comment by marcustyphoon** [comment]
No problem :)
