### ISSUE TITLE
Allow Anti-Capitalism to still show blazed posts

### ISSUE THREAD

**Issue by inklesspen** [AprilSylph/XKit-Rewritten#1094]
### Concept

As discussed in https://github.com/AprilSylph/XKit-Rewritten/discussions/1091, it would be nice to still be able to see blazed posts when using Anti-Capitalism to hide dashboard takeovers.

I saw a Blazed post on my dash today and stopped to inspect the HTML structure. It's very long, so I'm not going to post it except if requested, but the meat of it is that the Blaze badge on the post has class `blazeBadge` (`cTtCk`) and the "Sponsored with Blaze" notice has classes `sponsoredText` (`zYMVR`) and `blaze` (`lLxmv`).

I went into the Anti-Capitalism source and found `keyToCss('adTimelineObject', 'instreamAd', 'mrecContainer', 'nativeIponWebAd', 'takeoverBanner')`, which evaluates to `:is(.Qrht9, .XJ7bf, .Yc2Sp, .uOyjG, .njwip)`, and plugging that into `document.querySelectorAll` does indeed select the blazed post.

So obviously we want to only select ads which do not contain an element with the `blaze` class (or `blazeBadge`, I suppose, depending on what we think is more long-term reliable.

```
`${keyToCss('adTimelineObject', 'instreamAd', 'mrecContainer', 'nativeIponWebAd', 'takeoverBanner')}:not(:has(${keyToCss('blaze')}))`
```

The nested `:not(:has(…))` did the trick; this selector no longer matches blazed posts.

It seems to me that we could add an option to the Anti-Capitalism script to tack on the allow-blaze option, but I don't know if there's some other reason `:not(:has(…))` would be frowned upon.

Let me know if I should send a pull request for this.

**Comment by AprilSylph** [comment]
[`:has()` is not yet supported in Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility).

**Comment by marcustyphoon** [comment]
If I recall correctly, it would require a rewrite of significant portions of Firefox's CSS engine in order to make it not perform terribly, or something. (And to be fair, I can't imagine how it even works.) I'm sure it'll happen at some point.

Implementing behavior like that in XKit Rewritten would use a well-established pattern: register the current string with a pageModifications callback and test for the the child with querySelector in the callback, rather than implementing the whole behavior in CSS.

**Comment by inklesspen** [comment]
Ah, fair.

It seems there's an alternative approach: we could split up the list of ad-related classes. If I already pay for tumblr's Ad-Free, I don't need to block in-timeline or sidebar ads, just the takeover stuff, right?

**Comment by marcustyphoon** [comment]
Currently takeover stuff isn't blocked, so Anti-Capitalism isn't doing anything for you if you have ad-free! Possibly, though?
