### ISSUE TITLE
Classic Search not redirecting to /tagged/

### ISSUE THREAD

**Issue by kitsunegari101** [AprilSylph/XKit-Rewritten#1095]
### Platform

Windows 10 10.0.18363 Build 18363

### Browser

Firefox 114.0.1 (64-bit)

### Addon version

v0.21.8 (Beta)

### Details

I'm unsure if it's something I've done wrong in configuring my settings, especially given that I have New XKit as well, but Classic Search is not redirecting from /search/ to /tagged/ no matter how hard I try. Is there a possibility that something in my XKit Rewritten settings is conflicting with this? My current settings are attached.
[xkit rewritten specs.txt](https://github.com/AprilSylph/XKit-Rewritten/files/11745171/xkit.rewritten.specs.txt)

**Comment by AprilSylph** [comment]
Classic Search only intercepts the action that happens when you press Enter in the search bar, it doesn't redirect anything else. Off the top of my head there should be nothing that prevents this.

I'll take a closer look later to see if I can reproduce it with your exact config.

**Comment by kitsunegari101** [comment]
That's the problem—it doesn't redirect when I press enter in the search bar; it just flings me right back to the search page.

No rush! I'll hang tight for the meantime.

**Comment by marcustyphoon** [comment]
As an additional piece of information, what searches are you testing with? Some terms don't have tagged pages.

**Comment by kitsunegari101** [comment]
I'm starting to think that you're right; I was searching for Rafael Sabatini's novel Captain Blood but evidently it's not popular enough to warrant a tag on its own.

**Comment by AprilSylph** [comment]
It's not to do with popularity. I don't know how it works, but some tags just don't have `/tagged/` pages because of certain terms. "Captain Blood" definitely checks out as being hit with whatever filter that is, and I can confirm that visiting https://www.tumblr.com/tagged/captain%20blood directly also redirects, nothing to do with Classic Search.

**Comment by kitsunegari101** [comment]
Must just be Tumblr weirdness, then. Thanks for the help anyway!
