### ISSUE TITLE
chromebook & trimming

### ISSUE THREAD

**Issue by sodabear18** [AprilSylph/XKit-Rewritten#1096]
### Platform

ChromeOS

### Browser

Chrome

### Addon version

v0.21.9

### Details

i'm using a chromebook and a chrome web browser, i have trimming enabled but no matter what i do, its not allowing me to trim post. am i just doing something wrong?

**Comment by AprilSylph** [comment]
https://github.com/AprilSylph/XKit-Rewritten/wiki/Features#trim-reblogs

**Comment by marcustyphoon** [comment]
My standard copy-pasted tutorial:

> You can trim reblogs in threads created in the new post editor with XKit Rewritten's Trim Reblogs! Make sure you have it enabled in the XKit Rewritten settings menu to the right of your browser's address bar.
>
> To use Trim Reblogs, draft or post the reblog with your additions, then navigate to it and press the scissors icon! You can pick which reblog trail items stay, so if you and your partner start with a post with just a title, you can keep it on top. This requires the thread to have been started with the new post editor (or on the mobile app).
>
> The new method doesn't indent your partner's text; it just keeps the reblog in the normal reblog format and removes the trail items that you don't want to keep.
