### ISSUE TITLE
No Recommended not hiding top-of-dashboard video rec

### ISSUE THREAD

**Issue by umbralOptimatum** [AprilSylph/XKit-Rewritten#1097]
### Platform

macOS 10.14.6

### Browser

FIrefox 114.01

### Addon version

v0.21.9

### Details

Not sure whether this fits under an existing No Recommended option, but recently I've been getting these dashboard video inserts. Not loaded thanks to uBlock Origin, but accidentally click it still opens a tracking redirect link and it's kinda annoying! I dug around in the obfuscated css classes and didn't see anything obvious to uniquely identify it, so full HTML included.

<img width="567" alt="Screen Shot 2023-06-16 at 1 36 42 AM" src="https://github.com/AprilSylph/XKit-Rewritten/assets/12092270/455aba2a-8190-4273-b855-15b1fbd171bb">

`<div class="So6RQ" tabindex="-1"><div class="ge_yK" tabindex="-1"><div class="c79Av"><div class="Z0Knh"><div></div></div><div class="XJ0js"><div></div></div><div class="qj1WD"></div><div class="qj1WD"></div><div><a href="https://tmk.smartadserver.com/click?imgid=30162497&amp;insid=11739025&amp;pgid=1485277&amp;fmtid=111589&amp;uid=b5352d4815ddb2e6800fe06ada8091310e682304efa4350e13f57707c8508b85&amp;uii=3517769876006285036&amp;acd=1686892841640&amp;opid=71b10efa-0dc8-4773-921c-1b13b35d15d6&amp;opdt=1686892841640&amp;transactionid=MzAxNjA0OTc6NGRnZjYxYzEtMTk2ZC0OOTk2LTljMmYtZGZkYjD5MGFiNDAx&amp;tmstp=1686892841617737&amp;tgt=brand_safety%3d1%3blanguage%3den%3bage%3d27%3buser%3db5358d4815ddb2e6800fe06ada8091310e682304efa4350e13f57707c8508b85%3bis_admin%3d0%3bad_free_with_ads%3d0%3bcl_general%3dyes%3bcl_violence%3dno%3bcl_drug_use%3dno%3bcl_sexual_themes%3dno%3brandom_to_billion%3d0%3b%24dt%3d1t%3b%24dma%3d506%3b%24gps%3d1t%3b%24hc&amp;systgt=%24qc%3d1308470168%3b%24ql%3dMedium%3b%24qpc%3d02474%3b%24qt%3d152_2114_14724t%3b%24dma%3d506%3b%24b%3d12999%3b%24o%3d12100&amp;envtype=0&amp;imptype=0&amp;gdpr=0&amp;cappid=1451257256&amp;go=https%3a%2f%2fmusic.tumblr.com%2ftagged%2fjean%2520deaux%2520aotm" target="_blank" rel="noopener"><div class="Cewkz" style="padding-bottom:40%"><div class="xACoA moatContainer"><div class="gDuxW oce3Y" role="application" aria-label="Video Player" style="border-radius:3px"><div class="yz4vl"><script type="text/javascript" src="https://z.moatads.com/tumblrjsvideo916683822435/moatvideo.js#_moatApi77130489"></script><video muted="" style="min-height:40px" role="button" playsinline="" controlslist="nodownload" autoplay="" aria-label="Pause"><source src="https://creatives.sascdn.com/diff/3905/11739025/Tumblr-AotM_JeanDeaux_V1_785661b5-b6db-46f9-ab68-9bef8f7bc03f.mp4"></video><div class="kEaLk eB3NB"><div class="C4lo4"><div class="LQ3tN anjRo" role="progressbar" aria-busy="true"><div class="OpTfa"></div><div class="OpTfa"></div><div class="OpTfa"></div></div></div></div><div class="V3aM5 NUgGE" style=""></div></div></div></div></div></a><a href="https://tmk.smartadserver.com/click?imgid=30160497&amp;insid=11739025&amp;pgid=1485677&amp;fmtid=111599&amp;uid=b5358d4815ddb2e6800fe06ada8091310e682304efa4350e13f57707c8508b85&amp;uii=3517769876006285036&amp;acd=1686892841640&amp;opid=71b10efa-0dc8-4773-921c-1b13b35d15d6&amp;opdt=1686892841640&amp;transactionid=MzAxNjA0OTc6NGRmZjYxYzEtMTk2ZC00OTk2LTljMmYtZGZkYjU5MGFiNDAx&amp;tmstp=1686892841617737&amp;tgt=brand_safety%3d1%3blanguage%3den%3bage%3d27%3buser%3db5358d4815ddb2e6800fe06ada8091310e682304efa4350e13f57707c8508b85%3bis_admin%3d0%3bad_free_with_ads%3d0%3bcl_general%3dyes%3bcl_violence%3dyes%3bcl_drug_use%3dyes%3bcl_sexual_themes%3dno%3brandom_to_billion%3d0%3b%24dt%3d1t%3b%24dma%3d506%3b%24gps%3d1t%3b%24hc&amp;systgt=%24qc%3d1308470168%3b%24ql%3dMedium%3b%24qpc%3d02474%3b%24qt%3d152_2114_14724t%3b%24dma%3d506%3b%24b%3d12999%3b%24o%3d12100&amp;envtype=0&amp;imptype=0&amp;gdpr=0&amp;cappid=1451257256&amp;go=https%3a%2f%2fmusic.tumblr.com%2ftagged%2fjean%2520deaux%2520aotm" target="_blank" rel="noopener" class="H4DuS"><div class="erLM8">Tumblr Exclusive: Jean Deaux</div></a></div></div></div></div>`

**Comment by marcustyphoon** [comment]
I think this counts as an ad rather than a content recommendation, as it's turned off by Tumblr's ad-free subscription! Does Anti-Capitalism effect it?
