### ISSUE TITLE
No Recommended showing recommended posts

### ISSUE THREAD

**Issue by kingofthecrocofiles** [AprilSylph/XKit-Rewritten#1099]
### Platform

Windows 10

### Browser

Firefox 114.0.1

### Addon version

v0.21.9

### Details

Despite having No Recommended turned on, I am getting recommended posts from tags I follow on my dashboard. I have all optioned turned on under the details.

**Comment by AprilSylph** [comment]
You can turn off followed tag recommendations via https://www.tumblr.com/settings/dashboard.
