### ISSUE TITLE
AccessKit Disable Animations: Broken imageset creation in post editor (Chromium)

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1100]
### Platform

MacOS 13.2.1 arm64

### Browser

Chrome 114.0.5735.106

### Addon version

master

### Details

In Chromium:

Insert two separate images into the new (gutenblr) post editor. Try to drag one beside the other with the four-squares (dragHandle) button in the top left.

With AccessKit's disable animations function on, this fails. With it off, it succeeds.

This is not the case once the images have been successfully dragged into each other to create a photoset: dragging them apart works; dragging them back together works (?).

a) Confirmation would be great;
b) Fixed by changing the selector to `:not(${playPauseSelector}):not([data-is-drop-zone="true"] *)`; is this the best way and is this a data attribute we should rely on, @AprilSylph?

**Comment by AprilSylph** [comment]
The data attribute is coming from Gutenberg itself so it should be fairly reliable, I think?

I think the best solution would be to scope the AccessKit script's transformations to just posts, though, and exclude the editor outright.

**Comment by marcustyphoon** [comment]
This AccessKit feature's primary areas of effect aren't inside posts, but excluding the block editor area to avoid compatibility issues makes sense.

**Comment by AprilSylph** [comment]
...I'll admit, I thought we were talking about the alt text tweak, because pure CSS breaking the editor doesn't compute in my brain.

**Comment by marcustyphoon** [comment]
Me neither. I would love to look at the low-level code there just to see what could possibly be going wrong.

I didn't actually test in Firefox; it very well might be a Chromium bug. Will do that later.

**Comment by AprilSylph** [comment]
Can't reproduce in Firefox.

**Comment by marcustyphoon** [comment]
Can't reproduce in Firefox.

Can reproduce in Chrome 114 on Windows. Yay, it's a Chromium thing.
