### ISSUE TITLE
Request: Auto queue shuffler

### ISSUE THREAD

**Issue by mweston6288** [AprilSylph/XKit-Rewritten#1104]
### Concept

Either right before or right after posting from the queue, have XKit shuffle the queue. This could make things more interesting for people by making their post history more erratic and cause some posts to potentially resurface much later.

**Comment by marcustyphoon** [comment]
XKit can't act automatically at a certain time since it has to be running in a web browser. In theory there could be an automatic shuffle after you queue something with Quick Reblog, though.
