### ISSUE TITLE
New tweak proposal: Removing "Rather use the mobile app?"  banner.

### ISSUE THREAD

**Issue by salazarbarrera** [AprilSylph/XKit-Rewritten#1116]
### Concept

Lately I've been using the mobile browser a lot (on Firefox , well, technically on Mull), and I've noticed that the banner suggesting to download the app is quite persistent. Every time the session is lost, or if an undetermined time after closing the banner has passed, the message resurfaces. 
I could send this code myself, but I was wondering what would be better, to just hide or display-none the thing via CSS, or programmatically pressing the "X" in the message whenever it is detected.

Screenshot for reference.
![Screenshot_20230702-102707](https://github.com/AprilSylph/XKit-Rewritten/assets/68821455/ae6a2c4f-f9fa-42bb-97c5-095bb6e393aa)

**Comment by marcustyphoon** [comment]
Does this occur on regular Firefox for Android? Usually recurring popups are due to cookies not being persisted correctly. I couldn't find any actual documentation abut what changes "Mull" includes.

**Comment by salazarbarrera** [comment]
Mull is a privacy focused browser, so it isn't too weird it deletes
cookies/sessions more frequently (I'm not certain if it does, but I'm
almost sure). Oddly enough, sometimes when the session is lost, the
decision to hide the recommendation persists (as it did today), and others,
the warning pops up again even while the session hasn't expired.
