### ISSUE TITLE
Turn Off Showing Mutuals/Followers in Notifications

### ISSUE THREAD

**Issue by Runzugirl** [AprilSylph/XKit-Rewritten#1122]
### Concept

I wanted to know if there's a way to turn off notifications that show if someone you're mutuals with or following you or you're following have interacted with your posts? When I open my notifications, I don't like seeing every single relationship I have with every person there. I don't want to think about who I'm following, who's following me, or who I'm mutuals with to show up next to the notification. It's anxiety inducing. Any way there can be an option to turn it off/get rid of it?

**Comment by marcustyphoon** [comment]
Normally I would suggest sending this in to Tumblr support as a feature request as well, but (someone correct me if I'm wrong here) I seem to recall it being publicly mentioned as in the "probably not; we're trying to avoid having to make settings toggle" category?

Okay, honestly? Send it in anyway: feedback about what users want is still important, and those decisions are never set in stone!

(I personally don't like the site feature in question just like you, so I am all for this, whether it's a site toggle or an XKit tweak!)

**Comment by Runzugirl** [comment]
Just in case, I sent tweeted it to Tumblr support and the main Tumblr twitter, but I can send an email as well. I'm smdh at myself, forgetting to even try email or seeing if they took feature requests through the site. 😂

**Comment by marcustyphoon** [comment]
Tumblr support requests go to the form at https://tumblr.com/support !

**Comment by Runzugirl** [comment]
Yep, found it earlier, even though the site made it a bit messy to find. Thank you though!
