### ISSUE TITLE
Mutual checker doesn't work on dashboard

### ISSUE THREAD

**Issue by roryrara** [AprilSylph/XKit-Rewritten#1141]
### Platform

Windows 10

### Browser

Firefox 115.0.2 (64-bit)

### Addon version

7.9.2

### Details

Mutual Checker doesn't show an icon in front of the poster's username

**Comment by AprilSylph** [comment]
7.9.2 is a New XKit version. Also, this is a duplicate of #1138.

**Comment by roryrara** [comment]
My bad, I meant for the Rewritten, will it be fixed?

**Comment by marcustyphoon** [comment]
It already is; you will get v0.21.13 automatically once it goes through Mozilla's review process!
