### ISSUE TITLE
Quick reblog: zero-click blog select

### ISSUE THREAD

**Issue by rexendevar** [AprilSylph/XKit-Rewritten#1152]
### Concept

I really like Tumblr's own quick reblog menu (the one where you hold E and mouse over the reblog button). All it lacks for me is the ability to add tags. In that, Xkit's is superior, but I reblog extremely regularly to two separate blogs and I dislike having to open the dropdown menu every time. I propose an optional system in which, given a number of blogs that is less than about seven or so, the dropdown will be replaced by a display of blog icons next to each other, and it will choose which to reblog to based on which has most recently been hovered over. [Here's a rough mockup](https://64.media.tumblr.com/500999747b2425864517ccccfa40d1e7/015b82223c67ce29-6d/s1280x1920/4ec64b264063b859d9d1cae860369a1bbb12c22d.pnj). When one wants to reblog to a specific blog, they must simply move their mouse over the reblog button, then down - making sure to pass over the icon of where they wish to reblog to - straight to the text fields or the reblog button.

**Comment by marcustyphoon** [comment]
I like this! I would make you have to click, though; that seems essentially as fast to me and less finicky.

**Comment by rexendevar** [comment]
That makes sense. Either way it reduces the number of clicks, so I'm happy with either.
