### ISSUE TITLE
Trim Reblogs Working On Dash

### ISSUE THREAD

**Issue by rebelliouslegacy** [AprilSylph/XKit-Rewritten#1160]
### Concept

I know that in order to use Trim Reblogs, you must first save the reply to your drafts. and then edit it as you see fit. But that is annoying there needs to be a feature that allows us to trim a post while on the dash instead of going back and forth between the dash and drafts to do replies. That's annoying and honestly kills the mood. Can y'all please think about adding a feature where you can trim reblogs from the dash, it would be very helpful.

**Comment by AprilSylph** [comment]
You can trim reblogs from the dashboard...

If you're talking about trimming in the editor, _during_ the draft/reblog, that's essentially impossible. The post has to exist in some capacity before XKit can freely edit it.

**Comment by rebelliouslegacy** [comment]
I'm talking about when I'm on the dash a pair of scissors icon is suppose to appear to allow me to trim to the reblog before editing, that is now showing up, it only shows when I'm in my drafts. It will not show up on the dashboard and I've tried everything I can think of and it does not show. If it is possible to do it from the dash then y'all need to tell me how to fix this because again it is NOT showing up on the dash. I get the regular icos comment, reblog, like and delete if I'm the original poster. But the scissors icons DOES not appear.

**Comment by marcustyphoon** [comment]
> I'm talking about when I'm on the dash a pair of scissors icon is suppose to appear to allow me to trim to the reblog before editing, 

That is not "supposed to" appear because that isn't possible, unfortunately.

> If it is possible to do it from the dash then y'all need to tell me how

You can reblog the post with your additions, then view your reblog on the dash and trim it. Not exactly what you're looking for, but that's the closest we can do.

**Comment by rebelliouslegacy** [comment]
Are you not reading what I'm saying, the scissors icon that you click to trim the reblog is not showing up when I am on the Dash, I get that I can edit it, I'm not talking about that. I use to be able to trim the reblogs from the dash without having to send them to the drafts first but now I can't. I've seen someone post the same issue somewhere else. Before you edit a post you can click the scissors icons and cut your previous reply and then add you new one, I'm only able to do that in drafts, not on my dash. If it is able to be trimmed on the dash then how do I get the scissors icon to show? 

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/140308865/f4028520-4035-4716-8d77-ea4c2b4ba49a)

See NO scissors icon on the dashboard!

**Comment by marcustyphoon** [comment]
In that screenshot, is it **your** reblog or your partner's?

**Comment by rebelliouslegacy** [comment]
It's my partner? I've been able to trim posts from the dash when I first started using X-Kit Rewritten now, all of a sudden I can't.

**Comment by marcustyphoon** [comment]
Gotcha. There has never been a way to do this using XKit Rewritten; when a post appears on your dash as your partner's, there's no way to mark the way you would want to reblog it in advance.

**Comment by rebelliouslegacy** [comment]
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/140308865/dea44e49-4e87-4cc9-b625-3de2e8bf08c3)

Then what do you call this!? Because I see the scissors icons on a post I reblogged from myself but when it comes to replies from others it doesn't. I need a better explanation because right now you're just making me more annoyed.

**Comment by marcustyphoon** [comment]
You can edit your own posts. You can't edit other people's posts.

Thus, similarly, you can trim your own posts. You can't trim other people's posts.

**Comment by rebelliouslegacy** [comment]
So you're telling me that when my partner reblogs a reply from me adding my own. On the dash I can't trim it before adding my own reply. Hitting scissors and cutting my previous reply?

**Comment by marcustyphoon** [comment]
Not a hundred percent sure what you're saying there, but my best guess is that you're thinking of each part of the trail as if they're stored separately, and a thread displays all of these individual items stuck together. If that were the case, maybe you would be able to edit/remove one of the replies you wrote from your partner's reblog. Tumblr doesn't store posts this way, though*.

When you reblog a post on Tumblr, it makes a new copy of the whole thread, however it looks at the time. We have the power to remove the trail items from a copy owned by you. For example:

<img width="455" alt="Screenshot 2023-07-23 at 1 19 13 PM" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/e053dd76-c2a7-43c6-8845-e6a6828e2c12">

This—the entire thing—is stored as my partner's post, including the parts of the trail I wrote. I cannot change how it looks.

If I reblog it, Tumblr makes a copy of the whole thing in my drafts or on my blog. I own the copy, and I can remove parts of the trail in my copy. But before that copy gets made, I can't change anything.

--

*my understanding is that if the Tumblr devs were starting over from scratch, they might consider storing each trail item separately, but that isn't how it was made in 2007 and there's no going back now.
