### ISSUE TITLE
Support for Liked By pages

### ISSUE THREAD

**Issue by dontanswerit** [AprilSylph/XKit-Rewritten#1163]
### Concept

I enjoy looking through my likes, which has to be done with Liked/By/[Username]/Page/whatever. Xkit doesnt load on these pages, only the typical Likes page which is just from page 1. I know I might be one of very few people who uses tumblr like this but itd be nice to have the quick reblog 500 pages into my likes.

**Comment by marcustyphoon** [comment]
The code that XKit Rewritten uses for many things isn't in those pages, so I doubt this will happen. But the older "New XKit" still works there, so you can use its One-Click Postage! (Slightly buggy as it is, iirc.)

**Comment by dontanswerit** [comment]
> The code that XKit Rewritten uses for many things isn't in those pages, so I doubt this will happen. But the older "New XKit" still works there, so you can use its One-Click Postage! (Slightly buggy as it is, iirc.)

Yeah thats what im doing for now, I just wanted to mention it Just In Case and whatnot. Doesnt hurt to mention.
