### ISSUE TITLE
Tweak: Skip type selection when pressing create post button 

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1170]
### Concept

Opening the Tumblr post editor to a specific "post type" is just a shortcut for opening it and adding a specific block to its contents. This is great when you're using the bar above the dashboard—it's just one click anyway—but for me it means that the selection interface at https://www.tumblr.com/new is a waste of time, as I select "text" essentially 100% of the time after clicking the create post button, pressing command-v to insert most kinds of media content.

A tweak could probably skip this by putting a `navigate('/new/text')` handler on the button (or by redirecting /new to /new/text or clicking the text button, but those seem like more work for no benefit).

**Comment by AprilSylph** [comment]
This is almost certainly coming as a real Tumblr update... sometime. No idea when.
