### ISSUE TITLE
Hide Tumblr Live bar

### ISSUE THREAD

**Issue by leonoctem** [AprilSylph/XKit-Rewritten#1172]
### Concept

an option to hide the tumblr live bar that shows on the dashboard if possible.

**Comment by marcustyphoon** [comment]
This is already implemented as one of the options at the bottom of Tweaks!

**Comment by leonoctem** [comment]
> This is already implemented as one of the options at the bottom of Tweaks!

i am absolutely blind it seems cause I scearched all over! thank you 🤣
