### ISSUE TITLE
Re-add account stats to the account submenu

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#1177]
### Concept

Among many other disastrous things, Tumblr is currently trialing a forced 'mobile' account stats layout that gets rid of the expandable account stats menu, preventing you from viewing or visiting your follower page/count, queued posts, drafts, blog members, post+, blaze, and mass post editor from the dashboard. For comparison, the same blog's HTML in the sidebar:

Desktop layout:
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/06fc6875-f09b-43bf-8bb7-b75b2cb3e220)

Forced mobile layout:
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/838563f1-b3c9-4167-9530-6e3a1e14bc28)

And while the `floatingButton` div remains across both layouts, the caret button itself is completely removed from the mobile layout.

**Comment by enchanted-sword** [comment]
Reverting this change is relatively simple, since it only removed elements rather than adding or moving anything, and because the CSS styles for all of the removed elements are still present in the stylesheets so simply adding the elements with the proper classes is enough to style it to exactly how it should look.

**Comment by marcustyphoon** [comment]
I find this one super funny because I read through more posts than I can count on one hand screaming about how the account menu in the left rail was *obviously* broken and redundant because the same items are shown in the right rail. Of course being able to see these for you main blog with one click instead of two would be nice, though.

**Comment by marcustyphoon** [comment]
Oh: for clarity, do you think we should name this, like, "re-add account stats to the account menu" or something? I don't think there's anything "mobile" about the current layout (if anything, it's the opposite; the view you want to re-add is the mobile one, because on a mobile device there isn't any room to put the items in question on the right).

**Comment by enchanted-sword** [comment]
I described it as the mobile layout because the class of the elements were specifically changed from `desktop` to `mobile`, but it's actually a bit insulting because the...actual mobile layout...doesn't hide the stats. Even on blogs that are part of the vertical nav beta.

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/3a488184-e970-4c31-a1da-e1491025bf56)
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/39655109-bc26-4e05-b68f-3232fd057417)

You mentioned stuff being moved to the right rail, but even if I turn off XKit as well as all of my custom scripts, nothing displays in the vertical nav layout's right rail that doesn't in the non-vertical nav layout, just the recommended blogs and radar.

**Comment by marcustyphoon** [comment]
> I described it as the mobile layout because the class of the elements were specifically changed from `desktop` to `mobile`,

Oh, wow, that's pretty funny. Leftovers from a previous version, I guess.

> You mentioned stuff being moved to the right rail, but even if I turn off XKit as well as all of my custom scripts, nothing displays in the vertical nav layout's right rail that doesn't in the non-vertical nav layout

Yeah, they're only shown when you're on `https://www.tumblr.com/blog/[your blog]` or `https://www.tumblr.com/blog/[your blog]/drafts` or whatever. (I assume you're talking about the fact that you can't access them from e.g. the dashboard? Definitely a drawback of this current layout.) It was when people were viewing their own blog pages that they were seeing the same elements on the page twice and complaining that it looked broken (which, IMO, it did, but of course the alternative has its downsides as well).
