### ISSUE TITLE
Cleanfeed: filter posts with specified tags

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#1178]
### Concept

An option to treat posts with specified tags as mature would be helpful since a lot of people still use some variation of "#nsfw" or "#nsft" to mark mature posts without community labels. While tag filtering does exist, implementing it alongside the option to mark specified blogs as mature would add an element of consistency as well as allowing people to simply hide media in posts specified as mature while still using the "hide filtered posts entirely" tweak.

**Comment by marcustyphoon** [comment]
I both like this idea and think that one could make the argument that if something is tagged nsfw/nsft and does not have the "mature" community label (and thus does not get its media hidden by cleanfeed), it's supposed to have one and thus one should mark it with the "missing label" button. (Got to follow those iOS store rules, unfortunately.)

**Comment by enchanted-sword** [comment]
Of course, but if you're using Cleanfeed you probably want the media hidden before you flag it and not after.
