### ISSUE TITLE
Hide Tumblr live carousel tweak fails on "for you" tab

### ISSUE THREAD

**Issue by ToughPapaya** [AprilSylph/XKit-Rewritten#1180]
### Platform

Windows 10 

### Browser

Chrome - Version 115.0.5790.171 (Official Build) (64-bit)

### Addon version

0.21.14

### Details

I have "hide Tumblr live carousel" checked under Tweaks, and Tweaks is toggled on. But I still see the Tumblr live carousel.

**Comment by marcustyphoon** [comment]
I have been made aware of this, but there are multiple versions of that element floating around and all of my accounts have the same one, so I can't personally fix it unless someone sends me a copy of the element html or a screenshot of the element expanded in dev tools or something.

**Comment by ToughPapaya** [comment]
![Tumblr live carousel html](https://github.com/AprilSylph/XKit-Rewritten/assets/113640163/7ef58d2a-a983-4000-b49e-cf069920c728)

**Comment by marcustyphoon** [comment]
Realization: I didn't handle the case where the user has the "for you" tab as the default, and I didn't notice this when I tested my alt account because I forgot to disable an override script for this face.
