### ISSUE TITLE
Tweaks option to remove the Changes/Shop/etc. links leaves an orphaned element behind

### ISSUE THREAD

**Issue by ketsuban** [AprilSylph/XKit-Rewritten#1198]
### Platform

Windows 11

### Browser

Firefox 116

### Addon version

v0.21.14

### Details

Enabling the Tweaks option "Turn the Changes/Shop/etc. links into a separating line" fails to remove the randomly-selected heading ("Content for the content gods", "Check these out", "Roll the dice", etc.) which is left orphaned.

**Comment by marcustyphoon** [comment]
duplicate of #1195!
