### ISSUE TITLE
"Remove Post Fade-in" Tweak

### ISSUE THREAD

**Issue by Demonskullz** [AprilSylph/XKit-Rewritten#1202]
### Concept

In the newest update(?), when new pages are loaded, posts "fade in" ([video demonstration](https://va.media.tumblr.com/tumblr_rzgp7tHkjC1xac1zk_720.mp4)) instead of instantly being shown. I'd like for there to be a tweak that removes this.

**Comment by marcustyphoon** [comment]
- Agreed;
- Send this as feedback to Tumblr support! (Mention that you probably have the "virtual scroller" feature flag in case the person who gets your report is confused);
- If this stays I don't know if we'll be able to do anything about it, as XKit Rewritten might not load fast enough to affect it.

**Comment by AprilSylph** [comment]
Probably not soon. Let's go ahead with the tweak.

**Comment by marcustyphoon** [comment]
Oh, that is... surprising.

**Comment by AprilSylph** [comment]
Yep, there's now only a fade-in when a new timeline being loaded, like if you open the blog view. I think that was a pre-existing thing, so I believe we're good to close this issue as no action needed.

**Comment by marcustyphoon** [comment]
Honestly, I'm sort of tempted to do this anyway; the "new timeline being loaded" scenario still having an animation makes the linked video completely valid.
