### ISSUE TITLE
Panorama is broken, no longer resizes dashboard

### ISSUE THREAD

**Issue by lexstellaris** [AprilSylph/XKit-Rewritten#1205]
### Platform

Windows 10

### Browser

Firefox 116.0.2 (64 bit)

### Addon version

0.21.14

### Details

In the last day or so, Panorama no longer works on my Win10 desktop. All it does when toggled on is to move the post entries on dash to the left but doesn't resize them at all. I get the same behaviour on my Win10 laptop using the same browser and XKit version. I've checked and unchecked all the other tweaks I have on to see if there's a conflict somewhere but there isn't. I have no other tumblr-specific styles, scripts, or add-ons in use, and it was working fine a couple of days ago. Nothing has changed in my system at all. I still appear to have the old dashboard? But if anything else has changed on tumblr's end I can't see what it might be.

**Comment by marcustyphoon** [comment]
Related: #1109

**Comment by martienne17** [comment]
Same things is happening to me, using Firefox on Linux Mint.

**Comment by martienne17** [comment]
I am still having this issue.

**Comment by marcustyphoon** [comment]
Tracking this under #1109.
