### ISSUE TITLE
No Recommended: Clarify recommended posts setting label

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1210]
### Concept

"Hide recommended posts on the dashboard" is, for the most part, not what the option in question does. I think it therefore deserves the kind of overly-specific label we might not otherwise use. (Hide recommended posts... that cannot be toggled in settings? Honestly I'm not sure exactly what it *does* do.)

**Comment by AprilSylph** [comment]
I think every type of released recommended post has a toggle, so maybe the best label would be "Hide experimental types of recommended posts"?
