### ISSUE TITLE
Show Originals still showing most reblogs

### ISSUE THREAD

**Issue by IronCurtainPony** [AprilSylph/XKit-Rewritten#1231]
### Platform

Windows 10

### Browser

116.0.3 (64-bit)

### Addon version

0.21.15

### Details

With Show Originals enabled, I still have the majority of reblogs come through while browsing the Original Posts tab. Enabling/disabling the "Always show my own reblogs" or "Always show reblogs with contributed content" options doesn't change anything. I had the same issue before the latest version of the extension, but it suddenly went away and worked properly again even after I got the Tumblr UI update, I did not keep track whether this began before or after the latest update. The reblogs that show up stay consistent even when I enable/disable Show Originals and the extension itself, as well as removing it re-adding the extension to Firefox.

**Comment by marcustyphoon** [comment]
Duplicate of #1196, which you understandably would have not seen because a fix was implemented already and will be out in the next release!

**Comment by marcustyphoon** [comment]
Are you still observing this with the latest version of the extension?
