### ISSUE TITLE
Live bar does not hide when navigating to the dashboard internally.

### ISSUE THREAD

**Issue by StarHorder** [AprilSylph/XKit-Rewritten#1235]
### Platform

windows 10

### Browser

firefox 99.01

### Addon version

0.21.15

### Details

the LIVE bar does not hide when navigating internally on tumblr, the element is only hidden upon refreshing.

reproduction: navigate to https://www.tumblr.com/dashboard by clicking on the 'home' button or the 'tumblr' logo. refresh.
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/11035862/e8a54502-5a83-4991-96ec-d26b56bb5024)

this is possibly related to #https://github.com/AprilSylph/XKit-Rewritten/issues/1172

**Comment by marcustyphoon** [comment]
Should be fixed in v0.22.0, which is still being reviewed for Firefox!

**Comment by marcustyphoon** [comment]
Are you still observing this with the latest version of the extension?

**Comment by StarHorder** [comment]
Nope. update has resolved the issue. TYSM.
