### ISSUE TITLE
Feature: Search Timelines

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#1236]
> **Search Timelines**
> Find posts by text match

I am envisioning a feature that adds a search bar to the top of all known timelines. When this search bar is typed into, each post is checked for a match for the input. If it passes the check (has a match), the post stays visible. If it fails the check (doesn't have a match), the post is hidden.

The search bar should debounce input/change events to avoid re-checking posts more often than needed.

Emptying the search bar should make the feature perform cleanup on the current timeline.

What to check for text matches:
- Every block in the `content` array
- Every block in the `trail`
- Every blogname in the `trail`
- The post author
- The reblog parent
- Tags

What to check within blocks: anything that is, or can become, visible to the user. Text within text blocks is obvious, but also things like inline link URLs, image alt text, link block titles, audio block track/album/artist names, etc.

Matching method: substring. To copy Tumblr's example, a search for "horse" should match a post containing the word "abhorsement".

The following nice-to-haves should _not_ be included in the feature's base implementation, for the sake of reviewer sanity. They may be considered as followup enhancements to the base feature, to be considered and reviewed separately.
- Match highlighting
- Preferences for which timelines to activate on

**Comment by marcustyphoon** [comment]
> the feature should not attempt to hook each timeline up to toggle preferences initially.

Sorry, could you clarify this one?

**Comment by AprilSylph** [comment]
It shouldn't have preferences like Collapsed Queue for controlling which timelines the feature activates on, in the first iteration of the feature.

Just deciding how we would want to split those preferences (i.e. whether we allow enabling it on Drafts but not Posts, or to include every `/blog/:blogName/*` timeline under the same toggle) is its own cognitive task, and should not be included in the feature's base implementation, but should be considered as an enhancement to the feature afterwards.

**Comment by marcustyphoon** [comment]
Ah, gotcha! 👍

**Comment by enchanted-sword** [comment]
I'm interested in working on this feature, if nobody has started yet.

**Comment by marcustyphoon** [comment]
@AprilSylph Is this still intended to be active, or should it be closed due to Tumblr's virtual scroller changes that—sort of—enable control-F?

**Comment by AprilSylph** [comment]
I think <kbd>CTRL</kbd>+<kbd>F</kbd> works well enough that this can be closed, yeah.
