### ISSUE TITLE
Mutual Checker not working 

### ISSUE THREAD

**Issue by eden-fenster** [AprilSylph/XKit-Rewritten#1237]
### Platform

Windows 11

### Browser

Chrome 115.0.5790.173 (Official Build) (64-bit)

### Addon version

v0.22.0 (beta)

### Details

It's not showing me who my mutuals are

**Comment by AprilSylph** [comment]
Looks like Tumblr updated the new attribution structure _again_ so there is no longer a unique way to target the post author attribution.

Problem line: https://github.com/AprilSylph/XKit-Rewritten/blob/d504ba9d2f2833afe653244e2234059d4ce87a85/src/scripts/mutual_checker.js#L13

I wonder if it's reliable to just target the first `a` queried within `header .attribution`. I kinda wanna put more checks in place to make sure the mutual icon actually gets attached to the post author name.

**Comment by AprilSylph** [comment]
@marcustyphoon I'm self-assigning this one but feel free to take it from me if you see fit.

**Comment by eden-fenster** [comment]
Sadly I don't know nearly enough JS to work on this type of thing, but
thanks for the offer.
Good luck working on it and bringing it back.

בתאריך יום ד׳, 23 באוג׳ 2023, 20:44, מאת April Sylph ‏<
***@***.***>:

**Comment by inklesspen** [comment]
I note that the blogLink element (`postAttribution.querySelector('a')`) has the CSS class `blogLink`. However, I think you'd want to add the mutuals icon as the first element within the div with CSS class `attribution`.
