### ISSUE TITLE
Scripts creating notifications should use their own icon

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#124]
Quick Reblog and Quick Tags currently use the XKit Rewritten addon icon for `notifications:create` for quick-n-dirty Chromium compatibility. Creating 128px square PNGs of their script icons to use instead would be much more preferable; when this is done, the notification titles could be changed to the script title too (Chromium notifications include the addon name anyway).

**Comment by AprilSylph** [comment]
`browser.notifications` will be unimplemented due to browser/OS differences. a custom toast system will be developed instead.

**Comment by marcustyphoon** [comment]
we could still do this actually
