### ISSUE TITLE
Tweaks: Changes/Shop carousel line missing margin

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1240]
### Platform

MacOS 13.5 arm64

### Browser

Chrome 115.0.5790.170

### Addon version

v0.22.1

### Details

<img width="579" alt="Screenshot 2023-08-24 at 11 04 32 PM" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/a13e32e8-5ca0-4d28-b8cb-eef4d6d25604">

The line that the relevant tweak turns what was formerly known as the "you're caught up" carousel into may(?) become hidden under a post because its bottom margin is not respected, only being visible because it sticks out at the corners. This only occurs in my testing with the reblog redesign A/B test (and the virtual scroller A/B as well; I did not test without). It's not obvious to me why this would make a difference.

(I am manipulating site code to get it on my main account so this may be an artifact of my test setup; if someone who has the reblog redesign could confirm this that would be great. I couldn't get the carousel in question to appear on my alt account with the reblog redesign.)

The simplest way to fix this that I can think of is setting a 1px height minimum and using outline and outline offset to make the line.

**Comment by AprilSylph** [comment]
Doesn't occur for me on my account that has the reblog redesign, but that account doesn't have the virtual scroller.

![Screen Shot 2023-08-25 at 13 17 46](https://github.com/AprilSylph/XKit-Rewritten/assets/28949509/ad0c6fac-cd80-4123-99a4-c6b8688de935)

**Comment by marcustyphoon** [comment]
Yes, virtual scroller is required.

**Comment by marcustyphoon** [comment]
> it turns out accounts that have it naturally never display a carousel at the top of the timeline, only in between posts

Yeah; this element used to be called "you're caught up!" and was/is used to indicate when you have scrolled far enough down your dash to catch up to where you had previously seen; if you have already seen every post on your dash it doesn't show up.

> Really curious as to what the difference between having it naturally and enabling it is

Wait—is there a difference for you? From your screenshots it looked the same but I might not be interpreting you correctly.

(The difference between having it naturally and enabling it, though, would be that the HTML that you get directly from the server depends on what flags are actually on your account; modifying the flags before the page javascript gets to them so that they are the same will make the page javascript try to render the same thing on top of different DOM elements, i.e. hydration mismatch. So you will potentially see corrupted UI when you first navigate to a Tumblr tab, but once you click a few links and soft navigate around, all of the elements will have been created by the javascript code and they'll match your edited flags.)

**Comment by marcustyphoon** [comment]
I think this may no longer be an issue? If someone can confirm, I'll close this.

**Comment by AprilSylph** [comment]
Yep, no longer an issue. I wonder what changed?
