### ISSUE TITLE
Anti-Capitalism feature adding purple bar to dashboard

### ISSUE THREAD

**Issue by scootalewis** [AprilSylph/XKit-Rewritten#1241]
### Platform

Windows 10

### Browser

Firefox

### Addon version

v0.21.15

### Details

With the Anti-Capitalism function of XKit Rewritten active, a purple bar is appended to the bottom of my browser window, treated like any other dashboard element; dimmed whenever I bring up a blog on my dash, and no longer present on non-dashboard Tumblr pages. Additionally, it doesn't appear to be an html element that I can isolate with the element viewer in my browser, which is...strange. I can;t bring up any menus if I right-click it, it doesnt appear to serve any function at all, it's just a weird purple bar a few pixels tall.

**Comment by AprilSylph** [comment]
Sounds like you're seeing the "We see you are using an ad-blocker" banner from Tumblr, but something else you have is hiding its contents.

Here's how it looks for me with just Anti-Capitalism, no other content blocking enabled, using XKit Rewritten v0.21.15 on Firefox 116.0.3 (64-bit):

![Screen Shot 2023-08-26 at 16 54 46](https://github.com/AprilSylph/XKit-Rewritten/assets/28949509/cf0ec37e-f20e-46a4-97dd-c18b7cb31504)
