### ISSUE TITLE
Have to turn extension off and on

### ISSUE THREAD

**Issue by namara-ashina** [AprilSylph/XKit-Rewritten#1257]
### Platform

Windows 10

### Browser

Firefox 116.0.2 (64-bit)

### Addon version

v0.21.15. (beta)

### Details

Recently, xkit rewritten will sometimes just stop working and I'll lose the ability to hover over the reblog button to reblog/queue. I've been fixing it by going to my extension manager, turning it off, then turning it back on again. It's happened 2 or 3 times in the past few weeks.

**Comment by marcustyphoon** [comment]
Do you have extension automatic updates turned off somehow? v0.21.15 isn't the latest version, and the later ones have been out for long enough that I would have expected Firefox to update you.

**Comment by namara-ashina** [comment]
I did a manual check for updates and it says I have the latest version. Allow automatic updates is currently set to Default but I'll change it to On to see if it helps

**Comment by namara-ashina** [comment]
Whoops, accidentally closed the ticket.

**Comment by marcustyphoon** [comment]
Interesting—you did a manual check and the version is still v0.21.15? Or did it change to v0.22.1?

Additionally: do you observe the entire extension not working when this happens, or just Quick Reblog? (You could turn on an innocuous feature like Limit Checker or Mirror Posts, leave it on, and check whether their sidebar item/menu item shows up the next time this occurs.) That would help figure out if it's a problem with Quick Reblog or with XKit Rewritten as a whole/something XKit Rewritten relies on like the Tumblr users API.

**Comment by namara-ashina** [comment]
Still v0.21.15 but i think I may have found the issue? I noticed it had stopped working again so I restarted it to turn on Limit Checker. And then I went to try manually updating the extension again and it broke again. Before and after:
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/108107288/bb3f23f5-019e-4ae0-bb22-04707ad3ff25)

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/108107288/35449e20-acb1-480d-94b5-bccd87c3473f)
It seems maybe my browser is having difficulty getting the update and it's breaking the extension?

**Comment by namara-ashina** [comment]
Okay so I managed to fix it. It was refusing to update because I didn't have the latest version of Firefox but now that that's updated I'm up to version v0.22.1 and it no longer turns itself off when I manually check for updates

**Comment by marcustyphoon** [comment]
Oh, weird, I remember writing a response to this but I must not have hit post or something.

Firefox 116.0.2 should have been new enough, so that's interesting. I wonder if this is related to https://support.mozilla.org/en-US/questions/1271306, which suggests that automatic extension updates might not work on certain internet connections like corporate networks if they're configured in a specific way; if that's the case here I wouldn't be surprised if this happens again every time one of your extensions updates more frequently than Firefox itself.
