### ISSUE TITLE
Add a script for Blockpack feature enhancements 

### ISSUE THREAD

**Issue by Charlignon** [AprilSylph/XKit-Rewritten#1264]
### Concept

# Context 

[A few months ago](https://wip.tumblr.com/post/716494775180804097/is-there-a-chance-tumblr-could-make-a-custom), Tumblr released* a feature called blogpack : it allows users to create custom feeds by putting a list of blogs in a url. It's pretty handy, but also pretty much manual.

# Proposition
Here are a few things that could be added to improve the usability of this feature : 
- Display a list of blogs in the blogpack in the sidebar, with options to remove or hide them (see rough mockup below)
- Add a search menu to quickly add new blogs and modify the url accordingly
- Store blogpacks in Xkit, in a similar fashion to Quick tags
- Display a list of these stored somewhere on the dahsboard for quick access

<details><summary>Mockup</summary>

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/58429220/8e4a8ee6-0558-49c0-abc7-7d4f8a9f7891)

</details>

# Acknowledgement
Some items may be redundant and unnecessary. Maybe storing in xkit is enough, and additional buttons are not needed. I am open to feedback on what would be the best user experience

*The feature is not 100% released. To quote staff, it's a "demo", but they never gave any update on the matter. In the meantime (which could be very long), we could greatly improve it with minimal effort. However I would understand if we said "no dev for features that may change in the future". Tell me what you think.

I have experience in web development, and I would be glad to work on this myself. In facts I am containing myself to not start coding now because I really really like blogpacks and want to use them daily

**Comment by AprilSylph** [comment]
Tumblr is in fact working on a real feature (or more accurately, an experiment) that builds upon blogpacks, it's called [Collections](https://cyle.tumblr.com/post/727197901957332992/tumblr-starter-pack-collection-on-tumblr-by-cyle).

**Comment by AprilSylph** [comment]
> However I would understand if we said "no dev for features that may change in the future".

This does inform my decision not to apply a "help wanted" label to this issue, but...

> I would be glad to work on this myself. In facts I am containing myself to not start coding now because I really really like blogpacks and want to use them daily

I won't discourage you from building it! Even if Collections ends up released before this theoretical feature (Blogpacks+?), this could be a good exercise in navigating and contributing to the codebase. It'd be great to have more people on board the project!

**Comment by Charlignon** [comment]
Thank you for your feedback ! I am almost done with development, I just need to figure out the linter :)
This was a good exercise and I had a good overview of the codebase, so even if this doesn't end up release I'd be glad to help with other things ! XKit a really cool and helpful project, so I want to contribute at least a bit

**Comment by Charlignon** [comment]
Well it seems the planets have aligned ! Labs just published news about [Collections](https://www.tumblr.com/labs/728187838181605376/introducing-collections?source=share), that should be coming pretty soon. I guess this can be discarded since it's redundant ? (although the feature is not publicly available yet)
