### ISSUE TITLE
"Remove the sticky effect from post avatars" option in Tweaks is obsolete

### ISSUE THREAD

**Issue by ravewulf** [AprilSylph/XKit-Rewritten#1265]
### Platform

Windows 10

### Browser

Firefox 117

### Addon version

0.22.1

### Details

The new Tumblr layout/theme has removed the sticky avatars, meaning this setting has no effect. Possibly change this toggle to restore the sticky post avatars feature based on the toggle state or else create a new setting to restore sticky post avatars?

**Comment by ravewulf** [comment]
Still an issue with Beta 0.23.0

**Comment by marcustyphoon** [comment]
Yeah, that layout is still being tested—my account doesn't have it, for example.

(It sounds like you're kind of saying two mostly-separate things with this issue: a) the avatar unstickying doesn't do anything when the avatars aren't sticky, which is true and we would remove it in that case, and b) you would like a feature to put the avatars back on the side of the post column!)

**Comment by ravewulf** [comment]
Yep, technically two separate (somewhat related) issues and they can be separated if that makes more sense. The bump to the topic was purely to prevent the bot from closing the issue :)

**Comment by marcustyphoon** [comment]
@AprilSylph I see you marked this as help wanted; what action are you treating this issue as tracking? Removing the obsolete option? I assume it would make sense to track anything else elsewhere?

**Comment by AprilSylph** [comment]
Yeah, just removing the obsolete option. Anything further needs to be its own issue.
