### ISSUE TITLE
Cleanfeed not hiding unstretched media

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#1277]
### Platform

Windows 10

### Browser

Firefox Nightly 119.0a1

### Addon version

v0.22.1

### Details

Cleanfeed occasionally fails to filter certain media in posts as intended (manually blurred here)
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/a605d86a-3003-4b1e-b93e-bc6d62a05ca3)

It isn't a problem with the tagged post filtering, as other posts with the same tag are filtered correctly, but rather a problem in `cleanfeed.css`.
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/30d11b7f-775e-4766-b48f-9e7febb8f6e2)

The selector for media to be hidden specifically ignores `<figure>` elements with an existing `style` attribute, however in this case, the media is unstretched, and thus contains inline styling:
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/7b739d21-1c55-4b15-8c32-b9142ebc62c0)

I am assuming there is a valid reason for why inline-styled media is ignored, but the selector might need to be adapted in some way to include unstretched media.

**Comment by marcustyphoon** [comment]
As per a git blame it's to avoid hitting ask avatars! Should be fixable I'm sure. https://github.com/marcustyphoon/XKit-Rewritten/commit/5b1b5e048ea9b74d0771974820dd6a8b63f7d8a9

**Comment by enchanted-sword** [comment]
I could be wrong, but it seems like it would only apply to anonymous ask avatars, since normal ones aren't wrapped in a `<figure>` tag (the anon avatars are just a blank element and the image is a background image added by the stylesheet). Since the anon avatars have an `aria-label` attribute and imagesets don't, the selector could probably be changed to just exclude that instead.

**Comment by enchanted-sword** [comment]
Seems to work fine 
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/df4ed412-af85-4e26-afa3-69cfc3d5c98e)
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/1fd16dbd-0a1b-427b-8823-bf0b036902d0)
