### ISSUE TITLE
TimeFormat formats `<time>` elements outside of posts

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#1289]
We should not be processing `<time>` elements that appear outside of posts or the post editor.

Right now, because we are processing all `<time>` elements on the page, https://www.tumblr.com/explore/answertime has a duplicated timestamp when TimeFormat is enabled:

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/28949509/4481fcfd-c081-4cae-8eb6-45888d5c2145)

HTML | CSS
-|-
<img width="366" alt="Screenshot 2023-09-28 at 9 47 33 am" src="https://github.com/AprilSylph/XKit-Rewritten/assets/28949509/f5605961-a3b2-423a-b18c-eb8100905bd7"> | <img width="251" alt="image" src="https://github.com/AprilSylph/XKit-Rewritten/assets/28949509/bf32580d-7cb8-425c-ac52-5a8b586e4658">

**Comment by marcustyphoon** [comment]
Hm, that's a surprise, but indeed we do. We could target `article etc`; we don't want to use `postSelector` as that would not count the radar post, I assume. Probably more semantic than either is just using `keyToCss('timestamp')`, imo.
