### ISSUE TITLE
Tumblr Savior not hiding tags with Xkit Rewritten enabled?

### ISSUE THREAD

**Issue by MiniaturePeaches** [AprilSylph/XKit-Rewritten#1299]
### Platform

Windows 11

### Browser

Chrome

### Addon version

v.0.23.0

### Details

For some reason, Tumblr Savior doesn't hide tags when I have Xkit Rewritten enabled, or even the old version of Xkit. I am unsure why but it isn't very pleasant. If you can help in any manner that'd be great!

**Comment by marcustyphoon** [comment]
I recommend using Tumblr's native filtering instead of Tumblr Savior.

That being said, I wasn't able to reproduce this with only XKit Rewritten installed. Does it occur if you disable all other web extensions besides Tumblr Savior and XKit Rewritten?

**Comment by MiniaturePeaches** [comment]
> I recommend using Tumblr's native filtering instead of Tumblr Savior.
> 
> That being said, I wasn't able to reproduce this with only XKit Rewritten installed. Does it occur if you disable all other web extensions besides Tumblr Savior and XKit Rewritten?

Ah huh, I see. And I only have Tumblr Savior and Grammarly as extensions besides Xkit Rewritten. 

It seems to work to block the tags/posts when I use Xkit rewritten and the native filtering system together though.
