### ISSUE TITLE
Scrolling Avatars

### ISSUE THREAD

**Issue by Justforasking** [AprilSylph/XKit-Rewritten#1310]
### Concept

Is there any way to restore the scrolling avatars at the side of posts? Having to scroll back up to see whose blog the post came from is inconvenient.

**Comment by enchanted-sword** [comment]
If there's any interest in adding this, I already have a standalone script for icons that would only need minimal modification to work with XKit.

**Comment by nightpool** [comment]
not sure how April is feeling but I'm somewhat in favor. I keep getting to the bottom of a post and forgetting which mutual I'm supposed to upgrade or downgrade my opinion of based on how the reblog trail ends up going 😭

**Comment by enchanted-sword** [comment]
If I didn't have the scrolling icons I would constantly be sending my mutuals posts they just put on my dash lol

**Comment by Happyquack** [comment]
I saw that the option to remove the sticky effect has been removed, but are there still plans to add the option to bring the sticky effect back?

**Comment by enchanted-sword** [comment]
The feature is fully functional, hasn't been implemented yet though.
