### ISSUE TITLE
Cleanfeed: hiddenClass not being added to certain posts

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#1312]
### Platform

Windows 10

### Browser

Firefox Nightly 121

### Addon version

0.23.0

### Details

Rarely, I'll come across a post that isn't filtered by Cleanfeed desipite being from a blog on my filter list. At first, I assumed it was a problem with the CSS selector again, but I checked, and the affected posts don't actually have the `xkit-cleanfeed-filtered` class added to them. It isn't blog-specific; out of two posts from the same blog on my dash, one was filtered and the next wasn't. It also wasn't a random one-off bug, I've seen it more than once now and it persists for affected posts through browser refreshes.

**Comment by marcustyphoon** [comment]
Weird. Persisting through browser refreshes on a per post basis is especially strange. The code is pretty simple.

I didn't implement the changes in #1213 on cleanfeed/mutual checker, but they shouldn't be necessary—posts should be reprocessed if you scroll far away from them and then back. This doesn't feel like a race condition thing, really? But maybe? The posts aren't filtered posts that you clicked to view, are they?

Being a dev, you could try e.g. `console.log(await timelineObject(postElement), localFlaggedBlogs.includes(name))` and see if you can pin down the post(s) in question (not) getting processed.

**Comment by enchanted-sword** [comment]
Whoops, figured out what was happening: coincidentally enough, both blogs I had noticed the "bug" with had actually changed their URL by a single character since I added them to the filter and I didn't notice it. The reason only some posts were flagged was because some posts had community labels, so they got filtered regardless.

**Comment by marcustyphoon** [comment]
Ah, one of those :D I think it would be cool to have our blog selection system actually save blog UUIDs on entry and display the current blog names in the UI, but besides how complicated that would be, the time to do that would have been back in beta presumably (a migration process like #1071 isn't impossible, but is pretty clearly impractical).
