### ISSUE TITLE
Access to Quick Tag bundles from the post editor

### ISSUE THREAD

**Issue by Echoweaver** [AprilSylph/XKit-Rewritten#132]
It's great to be able to add tags from my tag bundles without opening the post editor, but that doesn't really match my process when I'm queuing up a lot of posts. I'd love to be able to add tags from the editor too.

Thanks for working on this! It's so nice to be running an XKit version where the features still work!

**Comment by AprilSylph** [comment]
Unfortunately, the new post editor is extremely difficult, bordering on impossible to manipulate. Considering it's still technically in beta, this may change in the future, but for now it's off the table.

**Comment by AprilSylph** [comment]
Hi! Sorry for dismissing this feature request at the time, but it really did seem impossible. However, with some help, I've now built internal utilities for both editing the (beta) post editor's tags and adding buttons to the form, and used them to make Quick Tags usable in the post editor with XKit Rewritten v0.6.0, just now approved by AMO.

You can use this feature today by updating manually (`about:addons` -> cog icon -> "Check for updates").

**Comment by Echoweaver** [comment]
I tried it, and it works! I am endlessly grateful for all your work on this X-Kit. It works incredibly well, and I can't imagine using tumblr without it.
