### ISSUE TITLE
Cleanfeed: Image cover label overlapping on small images

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#1324]
### Platform

Windows 10

### Browser

FF Nightly 121

### Addon version

v0.23.1

### Details

Small images hidden by Cleanfeed seem to have text labels that overlap instead of wrapping.
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/0395f469-65a6-42e7-91cb-cba95a424a89)
The image I noticed it on here had a default width of 68px and only displayed correctly when resized to 115px, but I tested some other hidden images and they all seemed to have different breakpoints based on the initial width.

**Comment by marcustyphoon** [comment]
Got an example post you can link? No worries if not.

**Comment by enchanted-sword** [comment]
https://www.tumblr.com/meowlgbt/733113897690775552/

**Comment by marcustyphoon** [comment]
Perfect, thanks!

**Comment by marcustyphoon** [comment]
I don't think I know enough CSS to make these wrap. One could do `white-space: nowrap` to at least not look like a huge mess, though?

**Comment by enchanted-sword** [comment]
Found our culprit: the cover is inheriting the default `line-height` property from the `imageBlock` class, which is zero.
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/3204f5da-dbc9-4500-b7cc-f87d9410d1ca)
Adding the rules `line-height: 16px;` and `text-align: center;` fix this.
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/81981111/a7f54863-646a-4c4c-b551-1dafb009fba4)
