### ISSUE TITLE
Please add an option to disable/enable Tumblr Live

### ISSUE THREAD

**Issue by clvgt12** [AprilSylph/XKit-Rewritten#1326]
### Concept

User story:

As a Tumblr X-kit user, I want the ability to optionally enable or disable seeing the Tumblr Live carousel on the web interface.   

![Screenshot_20231109_011945](https://github.com/AprilSylph/XKit-Rewritten/assets/15834506/3b00c362-941f-4f8d-b072-281210f74734)

The ability for me to select this option should be a part of the X-kit set of extension / add-on preferences.

![Screenshot_20231109_012336](https://github.com/AprilSylph/XKit-Rewritten/assets/15834506/408b293b-6a87-4cdb-8ca7-c4a874c66441)

**Comment by AprilSylph** [comment]
There is one, it's in Tweaks.
