### ISSUE TITLE
Tweaks: "Remove sticky effect from dashboard tab bar" not working

### ISSUE THREAD

**Issue by luxidoptera** [AprilSylph/XKit-Rewritten#1336]
### Platform

Windows 11

### Browser

Vivaldi 6.4.3160.47 (Stable channel) (64-bit) 

### Addon version

v0.23.1

### Details

Simple issue- the Tweaks function to disable the dashboard tab bar is currently not working. See screenshot:
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/15697751/2f2ac4c0-ffd8-450e-9e89-e49dc733c28a)

**Comment by AprilSylph** [comment]
That's the site header, not the tab bar.

**Comment by luxidoptera** [comment]
My bad. Thought they were the same thing lol.
