### ISSUE TITLE
recommended blogs are showing up despite having them disabled

### ISSUE THREAD

**Issue by taracdia** [AprilSylph/XKit-Rewritten#1339]
### Platform

Android 14 -latest

### Browser

Firefox nightly 122.0a1 (Build #2015988839), 1f91d01108+

### Addon version

v0. 23.0 beta

### Details

![Screenshot_20231201-194038](https://github.com/AprilSylph/XKit-Rewritten/assets/36205314/4777ca1d-1edc-4397-b457-d475b0c84095)
![Screenshot_20231201-193927](https://github.com/AprilSylph/XKit-Rewritten/assets/36205314/41bfb655-f257-4606-9b62-f892e14600ae)
I have the hide recommended blogs enabled but I'm still seeing recommended blogs

**Comment by luxidoptera** [comment]
Duplicate of #1335

**Comment by taracdia** [comment]
It's certainly similar but i wasn't sure if it was a duplicate because it was on mobile and recommended blogs instead of recommended tags. But now it's showing me recommended tags as well so i suppose I'll close this in favor of the other one
