### ISSUE TITLE
No Recommended: Recommended blogs not hidden on tagged pages

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1346]
### Platform

MacOS 13.6 arm64

### Browser

Chrome 117.0.5938.149

### Addon version

master 8c270824

### Details

<img width="1183" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/48c114db-1791-4012-ade2-9f28831a8386">

**Comment by enchanted-sword** [comment]
Whoops, it seems like those don't have the "Because you follow xyz" text, which is what the selector looks for. `blogLinkRecommendationWrapper` is probably a better selector to test for since it appears in all cases.
