### ISSUE TITLE
Narrow layout on Firefox Nightly

### ISSUE THREAD

**Issue by cl0udrecesses** [AprilSylph/XKit-Rewritten#1350]
### Platform

Windows 11

### Browser

Firefox Nightly

### Addon version

v0.23.3

### Details

dashboard tabs aren't visible as buttons, and layout is narrow from both sides, since the xkit update.

**Comment by marcustyphoon** [comment]
Can you attach a screenshot of what you're seeing?

**Comment by cl0udrecesses** [comment]
here it is. sorry, i thought i attached to the original post

**Comment by AprilSylph** [comment]
There's no screenshot in that comment, either. I'm not sure that GitHub supports uploading images via email attachment.

**Comment by cl0udrecesses** [comment]
![Uploading Screenshot_2023-12-15-14-32-54-54_984e1414ae90666a90f12ff17ec14a7f.jpg…]()

**Comment by cl0udrecesses** [comment]
here
![Screenshot_2023-12-15-14-32-54-54_984e1414ae90666a90f12ff17ec14a7f](https://github.com/AprilSylph/XKit-Rewritten/assets/109606219/01bc3064-ae4b-46dc-b62a-f4636bdb9888)

**Comment by AprilSylph** [comment]
That looks like Tumblr is just failing to load certain stylesheets... I don't believe XKit Rewritten can cause this.

Try closing the tab and quitting the browser before going to Tumblr again. Failing that, try clearing cache and cookies for `www.tumblr.com`, Also, if you have any content blockers, try adjusting or disabling them - uBlock Origin with its default settings should suffice for most purposes.
