### ISSUE TITLE
Not Loading on Firefox

### ISSUE THREAD

**Issue by AbelardTullus** [AprilSylph/XKit-Rewritten#1355]
### Platform

Windows 10

### Browser

Firefox 121.0 (64-bit)

### Addon version

0.23.3

### Details

The addon doesn't seem to be loading at all for me, I've tried loading up a private window running just Xkit and enabling "Run on sites with restrictions" but to no avail.  I've saved the console logs from loading without and with Xkit in case it helps at all.

Without Xkit
```
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified www.tumblr.com
main-d1882f73.js:87:1439
window.tumblr = 
Object { getCssMap: async getCssMap(), apiFetch: g(e, i), languageData: {…}, navigate: navigate(e), on: ev(e, t), off: ev(e, t) }
main-d1882f73.js:87:1474
The resource at “https://ads.pubmatic.com/AdServer/js/pwt/163304/10410/pwt.js” was blocked because content blocking is enabled. www.tumblr.com
Google Publisher Tags is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713685 for details. sandbox eval code:1:9
TypeError: n.googletag.defineSlot(...).setForceSafeFrame is not a function
    j https://assets.tumblr.com/pop/js/modern/6196-1a772e8b.js:1
    run https://securepubads.g.doubleclick.net/tag/js/gpt.js:494
    <anonymous> https://securepubads.g.doubleclick.net/tag/js/gpt.js:507
sentry-a1df3b01.js:18:18228
The resource at “https://assets.tumblr.com/pop/src/assets/fonts/favorit/favorit-medium-fbc7316f.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. www.tumblr.com
The resource at “https://assets.tumblr.com/pop/src/assets/fonts/favorit/favorit-85-cf2f6136.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. www.tumblr.com
```

With Xkit
```
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified www.tumblr.com
main-d1882f73.js:87:1439
window.tumblr = 
Object { getCssMap: async getCssMap(), apiFetch: g(e, i), languageData: {…}, navigate: navigate(e), on: ev(e, t), off: ev(e, t) }
main-d1882f73.js:87:1474
XHRGET
https://www.tumblr.com/api/v2/user/info
[HTTP/2 401  113ms]

Object { message: "APIError [401.0] at https://www.tumblr.com/api/v2/user/info ()", name: "ApiError", stack: "n@https://assets.tumblr.com/pop/js/modern/main-d1882f73.js:121:197218\ni@https://assets.tumblr.com/pop/js/modern/main-d1882f73.js:121:196997\np@https://assets.tumblr.com/pop/js/modern/main-d1882f73.js:3:2379\nasync*40658/B/g/h<@https://assets.tumblr.com/pop/js/modern/main-d1882f73.js:3:3550\npromise callback*g@https://assets.tumblr.com/pop/js/modern/main-d1882f73.js:3:3541\nxkit$injected@https://www.tumblr.com/:36:28\n@https://www.tumblr.com/:38:38\n", status: 401, path: "https://www.tumblr.com/api/v2/user/info", response: {}, detailedErrors: (1) […], body: {…} }
user.js:4:11
The resource at “https://ads.pubmatic.com/AdServer/js/pwt/163304/10410/pwt.js” was blocked because content blocking is enabled. www.tumblr.com
Google Publisher Tags is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713685 for details. sandbox eval code:1:9
TypeError: n.googletag.defineSlot(...).setForceSafeFrame is not a function
    j https://assets.tumblr.com/pop/js/modern/6196-1a772e8b.js:1
    run https://securepubads.g.doubleclick.net/tag/js/gpt.js:494
    <anonymous> https://securepubads.g.doubleclick.net/tag/js/gpt.js:507
sentry-a1df3b01.js:18:18228
```

**Comment by marcustyphoon** [comment]
Thanks for reporting this with details!

This may be a silly question, but just to confirm: you're logged into Tumblr, correct?

**Comment by AbelardTullus** [comment]
Not silly at all, I should've specified that I was logged out before, but the outcome is the same regardless, here are the logs anyway.

Without Xkit
```
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified www.tumblr.com
main-d1882f73.js:87:1439
window.tumblr = 
Object { getCssMap: async getCssMap(), apiFetch: g(e, i), languageData: {…}, navigate: navigate(e), on: ev(e, t), off: ev(e, t) }
main-d1882f73.js:87:1474
The resource at “https://ads.pubmatic.com/AdServer/js/pwt/163304/10410/pwt.js” was blocked because content blocking is enabled. www.tumblr.com
Google Publisher Tags is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713685 for details. sandbox eval code:1:9
TypeError: n.googletag.defineSlot(...).setForceSafeFrame is not a function
    j https://assets.tumblr.com/pop/js/modern/6196-1a772e8b.js:1
    run https://securepubads.g.doubleclick.net/tag/js/gpt.js:494
    <anonymous> https://securepubads.g.doubleclick.net/tag/js/gpt.js:507
sentry-a1df3b01.js:18:18228
TypeError: n.googletag.defineSlot(...).setForceSafeFrame is not a function
    j https://assets.tumblr.com/pop/js/modern/6196-1a772e8b.js:1
    run https://securepubads.g.doubleclick.net/tag/js/gpt.js:494
    <anonymous> https://securepubads.g.doubleclick.net/tag/js/gpt.js:507
sentry-a1df3b01.js:18:18228
```

With Xkit
```
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified www.tumblr.com
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. www.tumblr.com
main-d1882f73.js:87:1439
window.tumblr = 
Object { getCssMap: async getCssMap(), apiFetch: g(e, i), languageData: {…}, navigate: navigate(e), on: ev(e, t), off: ev(e, t) }
main-d1882f73.js:87:1474
The resource at “https://ads.pubmatic.com/AdServer/js/pwt/163304/10410/pwt.js” was blocked because content blocking is enabled. www.tumblr.com
Google Publisher Tags is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713685 for details. sandbox eval code:1:9
TypeError: n.googletag.defineSlot(...).setForceSafeFrame is not a function
    j https://assets.tumblr.com/pop/js/modern/6196-1a772e8b.js:1
    run https://securepubads.g.doubleclick.net/tag/js/gpt.js:494
    <anonymous> https://securepubads.g.doubleclick.net/tag/js/gpt.js:507
sentry-a1df3b01.js:18:18228
TypeError: n.googletag.defineSlot(...).setForceSafeFrame is not a function
    j https://assets.tumblr.com/pop/js/modern/6196-1a772e8b.js:1
    run https://securepubads.g.doubleclick.net/tag/js/gpt.js:494
    <anonymous> https://securepubads.g.doubleclick.net/tag/js/gpt.js:507
sentry-a1df3b01.js:18:18228
```

**Comment by marcustyphoon** [comment]
Ah, gotcha! Now, to confirm, how are you verifying that XKit Rewritten isn't loading? For clarification, the addon doesn't do anything to the page until you toggle on any of its functions from the extension options pane by clicking the icon (next to your browser's URL bar). Do you have functions enabled that you aren't seeing take effect?

(@AprilSylph, I know you don't like unnecessary console logging, but maybe we should put a single console statement in main.js? Maybe another in `runScript()` that would allow confirming that a specific script has at least attempted to be loaded, when people report that a specific script doesn't seem to be working?)

**Comment by AbelardTullus** [comment]
Enabling any of the functions doesn't seem to make any difference, even after reloading the page or restarting Firefox. Also given what you said, is there a better way to be sending console logs, what other information can I provide?

**Comment by AbelardTullus** [comment]
I'm sure uploading a screenshot isn't that helpful, but it is strange how no element of Xkit seems to be working at the moment. I also run the Dashboard Unfucker script, but that doesn't seem to make any changes either, I've tried having either Xkit or DU on exclusively, and neither seem to make a difference at all. My only thought is that maybe this is something on Tumblr's side? But I've looked through the other reported issues and no-one else seems to be encountering this issue, so I'm not sure if I've messed something up.
![image](https://github.com/AprilSylph/XKit-Rewritten/assets/20971561/9019ebb6-27b6-4ed1-bdfc-d9277cab5358)

**Comment by marcustyphoon** [comment]
Hm. Nothing seems super obvious and you're provided pretty much everything I can think to check. What happens if you disable everything besides XKit Rewritten in `about:addons`? Also, do you have Firefox enhanced tracking protection on "strict" (which I effectively think of as an extension even though it's built into the browser)?

**Comment by AbelardTullus** [comment]
Sorry for the late response, turns out it was an issue with the Dashboard Unfucker script I was using with TamperMonkey. Before now I thought they worked together with very few compatibility issues, so I'm not sure what's happened that they seem to cancel each other out.

**Comment by marcustyphoon** [comment]
Hm. I don't do support for that script, but I'm curious if loading it via violentmonkey works instead. It could be a script thing or a userscript extension thing.

**Comment by AbelardTullus** [comment]
> Hm. I don't do support for that script, but I'm curious if loading it via violentmonkey works instead. It could be a script thing or a userscript extension thing.

Yeah it's the script itself, which is a damn shame, it fixed up the layout nicely, but as of recent times it's just been straight up not working, I think as it tries to load it somehow cancels out Xkit, so it's not the issue of the devs here anyhow. Thanks for the help though, you've been terrific.

**Comment by lolacool98** [comment]
I have the same issue but don't have Dashboard Unfucker running. Xkit isn't even showing up in my Tumblr sidebar.

**Comment by marcustyphoon** [comment]
XKit Rewritten is configured using a button next to the URL bar in your browser instead of a button in the Tumblr sidebar/header!
