### ISSUE TITLE
Blog doesn't open in tab

### ISSUE THREAD

**Issue by cissipissi** [AprilSylph/XKit-Rewritten#1357]
### Platform

Windows 10

### Browser

Firefox 121.1

### Addon version

v0 23.3

### Details

When I click my avatar at the very top it doesn't open in a new tab anymore, but in tumblr. Clicking on avatars otherwise works in tabs.

**Comment by marcustyphoon** [comment]
Is this with the "dashboard unfucker" user script?

**Comment by cissipissi** [comment]
Yes, does the issue lie there?

**Comment by marcustyphoon** [comment]
Tumblr doesn't have an avatar at the top of the dashboard without that script, so yes! An option that adjusts what that element does when clicked would have to come from the script that added it.
