### ISSUE TITLE
Tweaks: Change keyboard shortcuts in narrow screen mode

### ISSUE THREAD

**Issue by shinobody** [AprilSylph/XKit-Rewritten#1358]
### Concept

For some reason, Tumblr behaves differently when the browser window has a very small width. I think this is meant as a hacky detection of mobile devices, but what it actually results is is that when I use my browser at half-screen width when drawing (using art program on other half of the screen), it breaks.

They keyboard shortcut in question are left-right keyboard arrows - on normal width they allow user to quickly swap between pictures in an open photoset, but at half-width (and only then) they get implemented as navigation between next/previous page of the dashboard (with infinite scrolling disabled). In normal width they work too, but then photoset navigation takes precedence (correctly) so you can still use them.

(My browser is Firefox in case that matters for glitch reproduction).

I know this is an extremely niche glitch that affects extremely few people (like me) but it is really infuriating. If there was a Tweaks option to disable that I'd be in heaven.

**Comment by marcustyphoon** [comment]
Submit this as a bug report to tumblr.com/support! I didn't get a chance to look closely at what you described, but the keyboard shortcut situation you described sounds like a bug. (The mobile layout being used is, of course, not, but it should work with a keyboard.)

**Comment by AprilSylph** [comment]
I know XKit has this reputation as some kind of magic fix-everything for Tumblr, but actually fixing Tumblr bugs is not in the scope of the project.
