### ISSUE TITLE
Quick Reblog: quote characters in tags don't work

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#138]
- The browser I'm using is: Firefox 
- My browser version is: 88.0; MacOS 10.14.6
- My XKit Rewritten version is: Beta 0.2.9

---

Reblogging a post with quick tags and entering e.g. `this tag has "a quote" in it` results in the tags `this tag has in it` and `a quote` rather than `this tag has "a quote" in it`.

I see the comma separated tags are just sent directly to `/posts`, so presumably this is just a Tumblr API thing.

**Comment by AprilSylph** [comment]
this is indeed just a part of the tumblr API; this behaviour can be observed with either of Tumblr's own post editors as well. as far as i know, there is no way around it.
