### ISSUE TITLE
Quick Tags: Added tags disappear when scrolling

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1380]
### Platform

MacOS 14.2.1 arm64

### Browser

Chrome 120.0.6099.216

### Addon version

0.23.3

### Details

When one adds tags to a post via Quick Tags, XKit Rewritten edits the added tags onto the post itself (Tumblr's code isn't aware of this). Due to the "virtual scroller" performance improvement code, Tumblr removes posts from the page when they're scrolled off of the screen and adds them back when they're scrolled back on; this process removes XKit's tag edits and doesn't ask the server if the post has changed, so the post will appear as if Quick Tags' edits weren't done. Refreshing the timeline in question or navigating to a different Tumblr page fixes this, of course.

This would be a lot of work to fix any way that I can think of and is fairly minor, so my guess is that we won't fix it, but I'll report it anyway so that it's documented.

**Comment by AprilSylph** [comment]
Hmm, is the post element consistent between cell renderings? If it is, we could have another `WeakMap` or something to mark it for re-processing...

...yeah, maybe not worth it.

**Comment by marcustyphoon** [comment]
I have [implemented it before](https://github.com/AprilSylph/XKit-Rewritten/pull/827/commits/5c609588917d6f7fbcbb85795d30e53b8adb0368), but yeah, it's pretty ridiculous.

**Comment by AprilSylph** [comment]
If we don't intend to fix this, but it is an issue, we should apply the wontfix label. Someone can always come along and dispute it later.
