### ISSUE TITLE
Block Post Button Not Showing Up

### ISSUE THREAD

**Issue by bxysgirl** [AprilSylph/XKit-Rewritten#1410]
### Platform

Windows 11

### Browser

Firefox 123.0.1 (64-bit)

### Addon version

0.23.3

### Details

Hello,

I've been using XKit-Rewritten for a while now, and thankfully haven't needed to block posts since I started, but now that I want to the block button doesn't exist? Or, at least, isn't showing up for me. Below is an example-post of what I *do* see:

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/40473893/d6ce1175-26b2-453d-bcd7-6a1bf70473fe)

It doesn't show up in the post menu either using the 3 dots:

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/40473893/df9582d8-5b96-4965-b18d-6d969c815b76)

And, I figured I would check, but it's not in the send menu as well:

![image](https://github.com/AprilSylph/XKit-Rewritten/assets/40473893/2cede19e-ad72-4dd6-b3e2-6876f38eac08)

I'm not sure where the block post button would be otherwise, so I've come to the conclusion that the block post button isn't showing up at all, or may be broken. I'm not sure, but I figured it'd be best to submit this.

Please let me know if there's anything I can do on my end about this!

**Comment by marcustyphoon** [comment]
Check out your second screenshot at the very bottom of the menu! (We added the [XKit] label to make sure it was distinguishable from Tumblr's user block button, but if you're used to the way it used to look I'm sure your brain just skips right over it :D)

**Comment by bxysgirl** [comment]
> Check out your second screenshot at the very bottom of the menu! 

Oh gosh, I feel silly haha. I absolutely overlooked it because I was expecting to see the old XKit "button." So sorry and thank you!
