### ISSUE TITLE
Posts not appearing.

### ISSUE THREAD

**Issue by elidangerous** [AprilSylph/XKit-Rewritten#1415]
### Platform

Windows 11

### Browser

Chrome

### Addon version

v.0.23.3

### Details

My posts are disappearing after a certain amount (specifically around four) but when I disable xkit, it loads fine. I contacted Tumblr Support about this but determined it may be an add on problem, and the only thing helping is disabling xkit. Which I don't want to have to do permanently. I've uninstalled and reinstalled, uninstalled Chrome as well, and neither of those things are helping. Any help would be appreciated. Thank you.

**Comment by marcustyphoon** [comment]
Do you use the "Dashboard Unfucker" user script or any other extensions? Does this occur with **only** XKit Rewritten enabled, and everything else disabled (including ad blockers)?

**Comment by ChangelingRain** [comment]
Do you have any badges? The Dashboard Unfucker script appears to be causing posts by/reblogged by people with badges to not load on the first load - may also be a conflict with xkit but I'm not sure *why*.

**Comment by ChangelingRain** [comment]
https://www.tumblr.com/pixiel/723402150351437824/anyway-i-created-a-stylish-stylus-that is apparently a still-maintained replacement for Dashboard Unfucker.
