### ISSUE TITLE
Scroll to Bottom Issues in Queue

### ISSUE THREAD

**Issue by emmah92** [AprilSylph/XKit-Rewritten#1421]
### Platform

MacOS 13.0.1

### Browser

Firefox

### Addon version

 v0.23.4

### Details

When I go into my queue and use the Scroll to Bottom feature, it struggles to get to the bottom without me clicking it multiple times. Then, when I move a post from the bottom of my queue to the top, it randomly moves me part of the way up in the queue rather than keeping my view where I was last active. After trying to move a post to the top of my queue, I also find that the posts are the top of my queue are now out of order and the one I just moved up isn't visible unless I refresh the page. After moving a post up, if I scroll back down to the bottom of my queue, I find that most of the posts are showing up doubled or even tripled. 

I've tried disabling the Scroll to Bottom feature from XKit Unwritten and then scrolled down manually and tried moving posts from the bottom of my queue to the top and these issues no longer exist.

**Comment by marcustyphoon** [comment]
Hmm, that's odd. Most of those sound like things only a bug in Tumblr's code would cause, but if you're not observing them if you scroll down manually... hmmmm.

To clarify, when you say moving posts to the top, you mean by clicking the up arrow button at the bottom of the post in question, right?

Also, when these things are happening, is the scroll to bottom button the highlighted (yellow, on most palettes) color that it is when it's scrolling, or does it go back to the same color as the scroll to top button? E.g. you're saying it stops scrolling before it gets to the bottom; does the button stay lit up as if it's trying to keep scrolling, or does it seem like it thinks it's done?

**Comment by emmah92** [comment]
Yes, I mean by clicking the button. And the scroll to bottom button stays yellow even though it has not yet reached the bottom!

**Comment by marcustyphoon** [comment]
Thanks! Hm, so when the scrolling stops mid-page...
- Does the page respond to mouse movement, e.g. if you put your mouse over someone's avatar does the little blog card pop up, or is the page kinda frozen?
- Does manually scrolling up and down a bit cause the automatic scrolling to resume without interacting with the scroll to bottom button?

**Comment by emmah92** [comment]
The page does respond to mouse movement and when I scrolled down a little, it did resume the automatic scrolling.

**Comment by marcustyphoon** [comment]
Gotcha! I'll keep trying to reproduce some of these—haven't managed it yet.
