### ISSUE TITLE
Block Suggested/Popular Tags When Making A Post? 

### ISSUE THREAD

**Issue by tigerintheflightdeck** [AprilSylph/XKit-Rewritten#1442]
### Concept

The last several months, when I start typing in the tag box, it will pop up with other recommended tags to include based on what's popular. The problem being is that most of these tags are absolutely disgusting. For example, if I tag something with Food, all the recommended tags that are suggested are about eating disorders. If I tag something Trans, all the tags that are suggested are pro-terf, and transphobic. Is there a way to block popular tags from being suggested?

**Comment by marcustyphoon** [comment]
Strange. I get tags like "food porn," "baking," "trans joy," and "nonbinary." Send a screenshot of what you're seeing to https://www.tumblr.com/support.

Using [Stylus](https://github.com/openstyles/stylus#releases) with this code is one way to hide that element:

```css
.DxQ0f:has(> div > .ZdQlM) {
  display: none;
}
```
