### ISSUE TITLE
Quick Reblog menu Scaled too Big

### ISSUE THREAD

**Issue by Avakining** [AprilSylph/XKit-Rewritten#1474]
### Platform

macos 14.5

### Browser

Firefox 126.0.1

### Addon version

v0.23.5

### Details

The quick reblog popup seems to be drawn twice as large as previously.

![Screenshot 2024-05-31 at 15-53-10 Tumblr](https://github.com/AprilSylph/XKit-Rewritten/assets/25210618/134163c1-4f54-45f8-b949-6d1e93e60ede)

**Comment by marcustyphoon** [comment]
Huh. I can't figure out? why this is only happening now? when nothing seems to have changed?

It looks like all we need to do is to apply f3efc2f to quick reblog.
