### ISSUE TITLE
Orignal post tab no longer showing on blogs

### ISSUE THREAD

**Issue by Pyroptical** [AprilSylph/XKit-Rewritten#1480]
### Platform

Windows 11

### Browser

Firefox 12.0.1

### Addon version

v0.23.5 (beta)

### Details

The original posts tab that used to appear on blogs is no longer showing

![firefox_13vhfcN27G](https://github.com/AprilSylph/XKit-Rewritten/assets/29610877/09cdf9a9-f313-4894-a2f4-9aa09e643657)
![firefox_Dc7aZQYh9F](https://github.com/AprilSylph/XKit-Rewritten/assets/29610877/6d2df577-de06-4536-8408-aaf3a48c19e0)
![firefox_hXR0nC95lB](https://github.com/AprilSylph/XKit-Rewritten/assets/29610877/02580dc0-da82-4cc3-bb8c-cdc0b8eaf486)

**Comment by marcustyphoon** [comment]
Thanks for the report; can confirm! I'm going to have to bug Tumblr staff about this one, I think.

**Comment by Pyroptical** [comment]
Thanks for such a quick reply, love you guys 💜

**Comment by AprilSylph** [comment]
> Thanks for the report; can confirm! I'm going to have to bug Tumblr staff about this one, I think.

We actually need to accommodate the new timeline identifier, `data-timeline-id`. Timelines won't be exposing their exact endpoint going forward, but will have unique identifiers. It's annoying, especially when not all timelines are migrated to this new system yet, but the architecture on the Tumblr side is way too different.

**Comment by marcustyphoon** [comment]
Gotcha! Do you know if the ones that do exist are (to a first approximation) in their final state and whether the plan (to a first approximation) is to have them on every timeline? I can start looking into that.

**Comment by AprilSylph** [comment]
This will be fixed in v1.0.0, releasing (hopefully) soon!
