### ISSUE TITLE
Make the shop/canges carousel separating line tweak follow theme color

### ISSUE THREAD

**Issue by breadguy69** [AprilSylph/XKit-Rewritten#1497]
### Concept

have the line color match the dashboard background color so it doesn't stick out so much

**Comment by marcustyphoon** [comment]
Hm. It currently does adjust its color based on the theme; it should match the Tumblr logo and the currently highlighted dashboard tab. In theory it could match a currently-not-highlighted dashboard tab, instead, which would be a bit more subtle.

If you literally mean matching the background color exactly, that's equivalent to just not showing it, right? I wouldn't think of that as a color change; rather, I think of that as an alternative function.

**Comment by breadguy69** [comment]
Oh aye, for me on the dark theme it's pure white which stands out more than any other inline UI element

**Comment by marcustyphoon** [comment]
| "selected" color | "unselected" color |
| - |  - |
| <img width="1080" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/894ff31f-a333-4dca-9521-97d1daa57110"> | <img width="1080" src="https://github.com/AprilSylph/XKit-Rewritten/assets/8336245/3f0946ec-7773-45f7-8c2b-600a92fe1a46"> |

**Comment by breadguy69** [comment]
I think part of it is the sharp edges compared to the rest of the dash, the second one does look better to me though
