### ISSUE TITLE
Vanilla Video no longer functioning

### ISSUE THREAD

**Issue by wordywarlock** [AprilSylph/XKit-Rewritten#1498]
### Platform

Windows 10

### Browser

Firefox version 126.0.1

### Addon version

v0.23.6

### Details

Vanilla videos no longer buffer or play. Videos are stuck at 0:00 and pressing play doesn't do anything.

**Comment by marcustyphoon** [comment]
Haven't managed to reproduce this yet, but I'm on MacOS and don't have access to Windows right now to test properly.

**Comment by wordywarlock** [comment]
I've discovered that opening the post in its own tab allows the video to play, so it may be something specific to the dashboard/search interface

**Comment by marcustyphoon** [comment]
Silly question: have you opened a new Tumblr tab since this has started yet? How about closed and reopened Firefox?

**Comment by wordywarlock** [comment]
Opening a new Tumblr Tab hadn't done anything, but I just restarted Firefox for an update and it appears to have started working again. It may have been a Firefox issue. Thank you!
