### ISSUE TITLE
Trim Reblogs Button Larger Than Normal

### ISSUE THREAD

**Issue by chrrycvke** [AprilSylph/XKit-Rewritten#1503]
### Platform

Windows 11

### Browser

Chrome

### Addon version

v0.23.6

### Details

I logged on Tumblr today and I saw that the Trim Reblogs button has moved from it's original spot and has gotten quite bigger than before. It's like this on any original post I've made or any post I've added something to. The only 'solution' I've found is diabling it and reenabling it didn't solve it like I was hoping it would.

![Screenshot 2024-06-16 203636](https://github.com/AprilSylph/XKit-Rewritten/assets/173015006/b6f1bc91-9659-41f7-afe5-56020834c69e)

**Comment by marcustyphoon** [comment]
Is this fixed if you press the browser refresh button or open a new Tumblr tab?

**Comment by chrrycvke** [comment]
I did try both of those before opening the issue. However, out of curisoity, I checked again just now and it's back to normal. On both laptop and desktop. I've no clue what happened.

**Comment by marcustyphoon** [comment]
Oh, on multiple devices, even—wow, that is weird. I know what would cause that appearance (the browser not loading our https://github.com/AprilSylph/XKit-Rewritten/blob/master/src/content_scripts/control_buttons.css file), but I have no idea why it would happen on two devices at the same time and then not anymore.
