### ISSUE TITLE
Tag Tracking+ no longer updates read posts

### ISSUE THREAD

**Issue by ElijahKujo** [AprilSylph/XKit-Rewritten#1510]
### Platform

Windows 11

### Browser

Firefox 127.0.1 (64-bit)

### Addon version

V0.23.6

### Details

Using Tag Tracking+, the number of read posts on tags no longer seems to go down. It does go up but never clears. I've refreshed the page multiple times, logged in and out of my tumblr account, and its still stuck

**Comment by AprilSylph** [comment]
This will be fixed in v1.0.0, releasing (hopefully) soon!

**Comment by ElijahKujo** [comment]
Happy to hear it :) thank you!

**Comment by arcanetrivia** [comment]
Yayyy it's working now :)
