### ISSUE TITLE
Seen Posts may not dim posts on soft refresh

### ISSUE THREAD

**Issue by Avakining** [AprilSylph/XKit-Rewritten#1539]
### Platform

macOS 14.5

### Browser

Firefox 128.0

### Addon version

v1.0.0

### Details

As of a few days ago, clicking the 'Home' button on the Tumblr dashboard no longer dims posts that were just seen. Only a full refresh of the page correctly dims newly seen posts.

https://github.com/user-attachments/assets/08b5770c-cee9-4e6b-81ba-2d5003ca73ac

**Comment by marcustyphoon** [comment]
Confirmed (dependent upon certain internal account flags; not everyone will experience this quite yet).

This is an interesting one; in essence, Tumblr has updated its navigation to be smarter, and that includes not destroying and recreating posts that aren't changed in that case, which is normally a good thing for performance. For the sake of this feature we want to behave as though the refreshed timeline actually disappeared and reappeared, presumably; I'll have to look at some internal stuff to see how easily we can do that.

(#1294 does not help with this, annoyingly.)
