### ISSUE TITLE
Quick Tags: option for how many tag bundles show up at once

### ISSUE THREAD

**Issue by JustDownloadin** [AprilSylph/XKit-Rewritten#1607]
### Concept

Quick Tags is awesome, but can be annoying to use when you have more than 5-6 tag bundles. As you can tell by the size of the scrollbar in the screenshot, I really like making tag bundles. Would it be possible to let us change the maximum amount of bundles that display without having to scroll down?
![imagen](https://github.com/user-attachments/assets/efa15811-af98-44a4-b148-6b0ef8da6999)

**Comment by marcustyphoon** [comment]
Duplicate of #867!
