### ISSUE TITLE
Import Setting Failed

### ISSUE THREAD

**Issue by nananarc** [AprilSylph/XKit-Rewritten#1608]
### Platform

Win 10

### Browser

Firefox 130

### Addon version

1.0.3

### Details

When I copy the backup code into the Import box, this message appears:

"Failed to parse back up content"

The important thing is I lost my custom quick tag bundles, other options are easy to recreate.

**Comment by AprilSylph** [comment]
Make sure you're copying the entire thing. Missing the starting `{` or ending `}` is enough to break it.
(This is why we offer the "Copy all" and "Download" buttons.)

Also make sure you're not trying to import a New XKit backup; that doesn't work. If you want to import New XKit tag bundles into XKit Rewritten, you have to open the New XKit control panel → Quick Tags → "Copy tag bundles to XKit Rewritten".

**Comment by nananarc** [comment]
Thanks for replying!

I'm not using New Xkit. And I have made very sure to copy the whole code, but it still said Failed somehow.
Does this have to do with the fact that there are some "special" characters in my tags because I used my local language with non-english characters? I notice that it failed to parse if they are there too. If so, is there anyway to overcome this?

**Comment by nananarc** [comment]
Ah I solved it!
There were some missing " ," while i was editing it. Still couldn't explain why I couldn't even import a non edited backup tho. Either way it works now.

**Comment by marcustyphoon** [comment]
Hmm, I'd have to see some of the actual tags and/or copied data to be able to guess or determine what's going on here.
