### ISSUE TITLE
Mass Privater: "(checked {x})" count can be incorrect

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#1609]
https://github.com/AprilSylph/XKit-Rewritten/blob/18298b6ad8127ced464852b4d5be539ae9b163d4/src/features/mass_privater.js#L202-L214

If Mass Privater fetches posts that are already privated, it doesn't count them in the "(checked {x})" text.

This can lead to a state where the feature is fetching pages upon pages of already-privated posts (since there is no way to request "only public posts" from the API, or pretend that we're logged-out when fetching...) but the UI is not updated for minutes or potentially even hours at a time.

**Comment by marcustyphoon** [comment]
...Whoops.
