### ISSUE TITLE
Tag Tracking+: Tab/window title is not updated when switching tracked tag within same tab

### ISSUE THREAD

**Issue by arcanetrivia** [AprilSylph/XKit-Rewritten#1613]
### Platform

Windows 10

### Browser

Firefox 130.0

### Addon version

1.0.3

### Details

If I left-click on a tracked tag to continue re-using the same tab as I am already in (rather than middle-click to open in new tab), the tab/window title does not update to reflect the tag that I am currently viewing:

![image](https://github.com/user-attachments/assets/8817389f-faa7-4d70-86d1-877e3e17cc4b)

It looks like when I navigate in this way, it is doing some kind of "hot swap" of the page content without fully reloading the page. (Is that "soft navigation"? https://github.com/AprilSylph/XKit-Rewritten/issues/933) If I open the tracked tag in a new tab, the title is as expected (after all, it's loading a page from scratch in that case).

This is a really minor issue, but can make it difficult to find a particular tab again if I click away from it. "I was sure I was looking at #david tennant; where the heck did that tab go?" well, it's the one reading "campbell bain".

**Comment by marcustyphoon** [comment]
Actually, wait, no, this is a Tumblr bug in general! If I go to a tagged page and click a tag on a post, I'll go to another tagged page but the tab title won't update. Let's send this in to https://www.tumblr.com/support!

**Comment by marcustyphoon** [comment]
Nope, crap, I was wrong about that, sorry. This one is our fault actually :D
