### ISSUE TITLE
Limit Checker replaces blog stats in the sidebar on tumblr.com/blog/USERNAME

### ISSUE THREAD

**Issue by Aelfwind** [AprilSylph/XKit-Rewritten#1628]
### Platform

Windows 10

### Browser

Brave Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)

### Addon version

v1.0.3

### Details

If Limit Checker is enabled while viewing my own blog at tumblr.com/blog/USERNAME, then the sidebar element that shows blog stats and links (blog name, number of posts, number of followers, etc.) disappears instantly after loading and is replaced by Limit Checker. If I stop the page from loading before either element finishes loading, then the blog stats load and Limit Checker does not. The behavior I'm expecting is for both blog stats and Limit Checker to be available.
This behavior occurs both with and without other extensions and other XKit Rewritten modules enabled.

**Comment by marcustyphoon** [comment]
Do you have any Stylus user styles or uBlock Origin custom filters (created by the element zapper, typically)? Try disabling any of those extensions and refreshing. This is almost always caused by something hiding the (for example) second sidebar item without checking what is actually in it, which the element zapper tends to do.

**Comment by Aelfwind** [comment]
> (Brave may have some sort of element zapper equivalent, I don't know; check that as well if it's not an extension. I don't use Brave. Try disabling Brave's ad blocking/whatever as well; it may have some of these rules.)

Ah, you're absolutely right: that fixed it. I disabled my other extensions but I'd forgotten Brave had one built in. Thank you very much, and sorry for the erroneous report.

**Comment by marcustyphoon** [comment]
No worries; glad we found it! Interesting; I was poking around in Brave trying to reproduce it but didn't manage to.
