### ISSUE TITLE
Not Hiding Own Posts

### ISSUE THREAD

**Issue by RABIDYOTE** [AprilSylph/XKit-Rewritten#1632]
### Platform

Windows 11 (10.0.22621)

### Browser

Firefox Developer Edition 131.0b9 (64-bit)

### Addon version

v0.23.6

### Details

It seems like hiding your own posts, whether they are reblogs or original posts, isn't currently working. I have both the tweak "Hide my own posts on the dashboard" and the "Show Originals" plugin enabled, with "Always show my own reblogs" disabled, and neither seems to make a difference. Disabling and re-enabling also doesn't fix the issue, neither does enabling each on their own.

**Comment by marcustyphoon** [comment]
v0.23.6 is quite a few versions old! See if you've accidentally (or purposefully) disabled automatic updates in `about:addons`.

**Comment by RABIDYOTE** [comment]
Oh, updates were disabled! I feel a bit silly. Sorry for the false report!

**Comment by marcustyphoon** [comment]
No worries :D Glad we got it fixed!
