### ISSUE TITLE
Trim Reblogs "APIError [400.0]"

### ISSUE THREAD

**Issue by TrippySin** [AprilSylph/XKit-Rewritten#1637]
### Platform

macOS11

### Browser

Chrome

### Addon version

v.1.0.3

### Details

Trim reblogs is no longer working. Saying that there is an issue anytime i try to do it. 
This is what it says. 
" Internet strangeness. Try again.

APIError [400.0] at https://www.tumblr.com/api/v2/blog/t:gFNlvP7UQ9wvuwAZb9dQaQ/posts/765003956648804352 () "

**Comment by marcustyphoon** [comment]
I've seen a few reports like this and I have a _vague_ idea why they might happen, but not a lot of specifics. I assume the post in question is in your drafts, so I wouldn't be able to actually look at it to see the internal data. Is it a legacy chat post? Is someone in the thread deactivated? Is it NSFW? Is it a chat post? Is it an ask?

**Comment by TrippySin** [comment]
i’m not sure if it’s legacy or beta post. yes it’s in my drafts but the
other person didn’t deactivate their account. it’s a text post. it was
working two days ago but last night and today it has been giving me the
error message.

**Comment by marcustyphoon** [comment]
Based on what the error message is, I would assume it's specific to that post, rather than it being a scenario where it stopped working at a certain time. Can you check that? (Like, draft a reblog of some totally irrelevant reblog chain from a totally different blog and try trimming the draft.)

**Comment by TrippySin** [comment]
I can try that or even delete the post so i can reblog it and draft it
again. i notice it’s not working on my side log but my main blog it works
