### ISSUE TITLE
Control buttons misaligned... kind of?

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#1638]
### Platform

MacOS 14.4.1 arm64

### Browser

Chrome 130.0.6723.59

### Addon version

master

### Details

![image](https://github.com/user-attachments/assets/8ef3c225-4946-47c7-9883-ff1173df5f4b)

I haven't figured out exactly what the vertical alignment of the existing icons actually is. Maybe this is more of a Tumblr inconsistency and we just get the choice of which one to match?

**Comment by AprilSylph** [comment]
the vertical alignment of the new tumblr iconset should be better. might have enough variety to ditch remixicon usage outside of the control panel, too.
