### ISSUE TITLE
Quick Tags blog URL

### ISSUE THREAD

**Issue by AnOctopus** [AprilSylph/XKit-Rewritten#1663]
### Concept

Add an option to include as a tag the URL of the blog a post is being reblogged from. (Awkward to describe the feature, but it was in New XKIT)

This is the only functionality I still use from New XKIT, and it would be nice to have in Rewritten so I can fully switch over. It's not a critical feature, but I have used that setting for ages and would like to maintain continuity.

**Comment by marcustyphoon** [comment]
Quick Reblog has this included within the "suggest tags from the post being reblogged" checkbox, but a) you have to manually click in the tags box and add it from the suggestion dropdown, and b) hm, that label totally doesn't describe that part of the feature, does it :D

**Comment by AnOctopus** [comment]
Oh yeah that was not obvious from the description. I'd still prefer something automatic, since it would be annoying to use like this, but it could work as a fallback if I really needed to.
