### ISSUE TITLE
PostBlock completely not working

### ISSUE THREAD

**Issue by pixierings** [AprilSylph/XKit-Rewritten#1670]
### Platform

Windows 11

### Browser

Firefox 133.0.3

### Addon version

v1.0.5

### Details

The PostBlock, despite being toggled on, is not working at all. It shows no icon on Tumblr.

**Comment by marcustyphoon** [comment]
Postblock adds an item to the three-dots "meatball" menu on the top-right corner of each post; do you see it in there?

**Comment by pixierings** [comment]
Yes, thank you!
