### ISSUE TITLE
Textarea-based scripts do not refresh

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#172]
- The browser I'm using is: Firefox MacOS
- My browser version is: 89.0.1
- My XKit Rewritten version is: 0.4.1 and 0.3.0

---

Hide Avatars and Show Originals do not take any action when their textareas are updated. The textareas quietly revert back to their previous contents when the popup is closed.

This occurs in v0.3.0, but does not in v0.2.10. (I wish I knew how to use git bisect :P)

I assume it's either a product of the modules transition or a bug or oversight in the autoRestart -> onStorageChanged transition? Still looking.

**Comment by AprilSylph** [comment]
currently, looks like the issue is trying to use `event.currentTarget` when the listener function is debounced. that change wasn't introduced in v0.3.0 though, so if you're right, there's another problem underneath. i'll take a look at it today.
