### ISSUE TITLE
Shortcuts and remembering previous blog for Quick Reblog?

### ISSUE THREAD

**Issue by ginsengtime** [AprilSylph/XKit-Rewritten#180]
Is it possible to add a shortcut for Quick Reblog, like how New XKit's "T" shorcut opened the reblog dialog? And could the blog that we last posted to be stored?

**Comment by AprilSylph** [comment]
I'm not interested in adding keyboard shortcuts, although I am vaguely planning to show the popup upon element focus as well to accommodate keyboard-only webpage navigation. I also believe it best to always reset every field in the popup after usage, for simplicity's sake if nothing else.
