### ISSUE TITLE
originals only only works on the dash?

### ISSUE THREAD

**Issue by gguimlk** [AprilSylph/XKit-Rewritten#182]
- The browser I'm using is: firefox
- My browser version is: latest
- My XKit Rewritten version is: latest

---
hi ! i was wondering why the extension originals only only works on the main dashboard and not on my own blog? (in dash view) it used to before but i can still see my own posts and reblogs despite ticking the preferences  ; v ; thanks so much btw!

**Comment by AprilSylph** [comment]
this is intentional. also, "latest" is not a version
