### ISSUE TITLE
Popup is cut off if pinned to the Firefox overflow menu

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#183]
- The browser I'm using is: Firefox MacOS
- My browser version is: 89.0.1 (proton disabled); 90.0b12 (proton enabled)
- My XKit Rewritten version is: 0.4.4

---

When you have the XKit Rewritten icon pinned to the overflow menu in Firefox, it appears to gain a header when clicked on that shifts the content downward in a way that messes up the scroll bar. This happens in both my Firefox installs. Edge and Chrome appear fine.

The overflow menu in Firefox appears to do fairly bad things to basically all of my webextension popups, so I'm not exactly surprised, but.

(This screenshot is scrolled all the way down. The last menu item is completely hidden, so this is unfortunately a functional as well as cosmetic issue, albeit an easy-to-workaround one.)

![Screen Shot 2021-07-18 at 8 38 00 PM 256](https://user-images.githubusercontent.com/8336245/126099487-0c82440f-14d7-4b5a-89d6-e6ef227f8431.png)

**Comment by AprilSylph** [comment]
I've also noticed this. I'm assuming it's a Firefox bug, but it would be great if there were a solution/workaround applicable to the popup code.

**Comment by AprilSylph** [comment]
Tracked down the Bugzilla issue, and Raymond Hill (author of uBlock Origin) notes the exact same thing. [Bug 1448276](https://bugzilla.mozilla.org/show_bug.cgi?id=1448276#c3)

I assume this means there's nothing that can be done, but I'll keep this issue open so that people can see it's a known problem.

**Comment by Avakining** [comment]
It looks like Firefox 106.0 fixed this?
