### ISSUE TITLE
Colons in filenames causing issues cloning repo on Windows

### ISSUE THREAD

**Issue by turtleseason** [AprilSylph/XKit-Rewritten#191]
Hi there! Sorry to be That Windows User 😅 but I get an "invalid path" error during checkout when cloning the repository - seems like it's objecting to the colons in the some of the docs filenames:

```
$ git clone git@github.com:turtleseason/XKit-Rewritten.git
[...]
Resolving deltas: 100% (3162/3162), done.
error: invalid path 'docs/Chapter 1: Introduction.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Would it be possible to rename the files? I was able to work around it by excluding the docs directory locally with sparse-checkout, but it'd be great to avoid the issue altogether if possible.

**Comment by AprilSylph** [comment]
Yep, sorry! I was aware of this and planned to fix it today, but didn't get the chance to.
