### ISSUE TITLE
Display alt text below images

### ISSUE THREAD

**Issue by turtleseason** [AprilSylph/XKit-Rewritten#192]
I think it'd be nice to have an option to make alt text visible to users not using screenreaders by inserting it as captions below the images, sort of like the "visible captions" option that used to exist back when tumblr image captions were a thing: https://github.com/new-xkit/XKit/blob/master/Extensions/accesskit.js#L407

I've been poking around at a rough draft of this, but I wanted to check first whether it sounds like a feature you'd be interested in adding atm (and also whether you're currently open for random new feature contributions at all, or if it'd be better to wait until the rewrite is further along/out of beta?)

**Comment by AprilSylph** [comment]
That sounds like a great idea! Anything to help reduce people so helpfully re-describing images...

I am taking contributions, but for original ideas (such as this) which have no exact predecessor, I do feel it's best to discuss the idea first so I can clearly understand the purpose of a pull request before I start reviewing its code. If this had been an XKit 7 feature and it's not on the list of [intentionally excluded features](https://github.com/AprilSylph/XKit-Rewritten/wiki/Excluded-features), there would be no need for discussion.

**Comment by turtleseason** [comment]
That makes sense, thanks!

I got a draft working that inserts a figcaption in the image block next to any image with non-default alt text - it's not very pretty to look at though lol (any styling suggestions would be very welcome 😅) Would opening up a draft PR with this code be a good idea, or better to continue discussing here for now?

![test_screenshot](https://user-images.githubusercontent.com/48301106/127084319-228c514c-6f7e-4eb3-baac-289719d28a54.png)

I was also thinking it might be nice to add a choice between always showing all captions, or having a button that reveals the text for specific posts/images only as needed (maybe similar in appearance to the video pop-out button) - but that 1) would probably necessitate making this its own extension vs sticking it in AccessKit/Tweaks or something (unless nested preferences are/will be a possibility), and 2) might be a little overkill anyway?

**Comment by AprilSylph** [comment]
I like the basic concept, so feel free to open a PR! I think it'd work best as a basic AccessKit option which actions on every image. I might have some styling suggestions, but I'd rather put them as code suggestions in the PR itself.
