### ISSUE TITLE
Tag Tracking+ post counts include recommendation carousels

### ISSUE THREAD

**Issue by turtleseason** [AprilSylph/XKit-Rewritten#199]
- The browser I'm using is: Firefox
- My browser version is: 90.0.2
- My XKit Rewritten version is: 0.5.0

---

Really minor issue - I only even noticed because I track a tag with no posts in it (url of a blog) and was curious why its count was showing as 2+. I think filtering `elements` on `objectType === 'post'` here (or skipping items with no timestamp) would fix it? I could make a PR if that'd be helpful.

https://github.com/AprilSylph/XKit-Rewritten/blob/82e1cc90018b6795d2428d000747ed74e1ec1bf4/src/scripts/tag_tracking_plus.js#L60-L63

(Also, this feels almost too insignificant to mention, but while looking into this I noticed that tags with no posts always have a count of 0+ instead of just 0 - I have no idea whether people who aren't me bother tracking empty tags lol so I don't know if this warrants changing, but thought I'd mention it just in case)

**Comment by AprilSylph** [comment]
Ah, I thought this might be the case. I thought that maybe the lack of timestamps would mean no changes were needed, but then forgot to ever check the code to be sure.

Always feel free to open PRs for filed bugs you can reproduce! I do want to take a look at this myself, but I would do so anyway as part of the review process.
