### ISSUE TITLE
Wiki: Update link to content moved from contributing.md

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#209]
The [wiki's installation section](https://github.com/AprilSylph/XKit-Rewritten/wiki/Installation#chrome) describes instructions for installing a webextension in developer mode and links to https://github.com/AprilSylph/XKit-Rewritten/blob/master/CONTRIBUTING.md, but this content has been moved to https://github.com/AprilSylph/XKit-Rewritten/blob/master/docs/Chapter%202%20-%20Getting%20started.md.

(Can't believe you can't PR a Github wiki! Seems like an odd omission.)

**Comment by AprilSylph** [comment]
Done!

Also yeah, wiki permissions are weird. Either everyone can edit it, or only members/collaborators. Opening it to everyone would be ideal if force-pushes are disallowed and I got notifications for edits, but I would have to test that to be sure.
