### ISSUE TITLE
exposeTimelines is broken by >1 "timeline" CSS class existing

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#210]
- My browser version is: Edge 92 (MacOS), Firefox 90 (MacOS)
- My XKit Rewritten version is: 0.6.1

---

https://github.com/AprilSylph/XKit-Rewritten/blob/f3efc2f822e27398e61688ecfa16c4336a8ff8e1/src/util/react_props.js#L44-L48

`exposeTimelines` is missing `descendentSelector`-style code to  handle >1 "timeline" CSS class existing.

This breaks the extensions that use it (seen posts, show originals, and the hide my posts tweak). Okay, I didn't actually test all 3, but it probably does.

**Comment by AprilSylph** [comment]
I'm actually not seeing any of these features break, but I agree that this is an oversight.
