### ISSUE TITLE
Force tag page Recent sort instead of Top

### ISSUE THREAD

**Issue by lihatt** [AprilSylph/XKit-Rewritten#222]
Tumblr decided to force tag pages to the Top view instead of Recent (see https://changes.tumblr.com/post/661325788557246465). Choosing Recent doesn't stick across pageloads, and there's no user-set preference, so if you want Recent you have to click it on every tag, every time, which is a big pain when looking for new posts in tracked tags. Would it be possible to add a switch to TT+, or wherever would be appropriate, to provide a choice to always load the Recent sort?

**Comment by AprilSylph** [comment]
I could add an on-by-default preference to Tag Tracking+ that changes the behaviour of followed tags in the search dropdown, but hopefully I won't need to. Given that nobody asked for this change and ~everyone it affects it affects negatively, I expect it to be reverted (or for followed tags specifically to link to `?sort=recent`) based on user feedback.

If you haven't added your voice already, [send a ticket to Tumblr support](https://www.tumblr.com/support) in the "Feedback" category. If sending a support ticket is too tall an order, a comment or reply on the Changes post is also better than nothing.

If there's no indication within the next week that our use-case for tag pages will be accommodated, I'll gladly make Tag Tracking+ force followed tag links to go to the Recent view, even if it does break Tumblr's soft navigation.

**Comment by AprilSylph** [comment]
I got a reply from Tumblr Support regarding this and it seems like followed tags were never supposed to be included in this change. Hopefully we'll see this listed as fixed in the next Changes post.

**Comment by AprilSylph** [comment]
Reverted as per the latest Changes post!

**Comment by lihatt** [comment]
Phew!
