### ISSUE TITLE
Blog Tracker

### ISSUE THREAD

**Issue by gabrieldelirium** [AprilSylph/XKit-Rewritten#226]
I would like to request an option to track blogs, like New XKit had. I was surprised to not find it here, especially because the tracker had started malfunctioning heavily in New Xkit, to the point where I had to go to the Members section of a sideblog to even see the tracker. Perhaps that's the reason why it couldn't make a comeback, but if it were possible and not an absolute nightmare to make, I would definitely love to see it make a comeback. It was one of my favourite functions, if not my absolute favourite.

Thank you very much for your time and efforts!

**Comment by AprilSylph** [comment]
https://github.com/AprilSylph/XKit-Rewritten/wiki/Excluded-features#blog-tracker
