### ISSUE TITLE
Sponsored Posts blocker.

### ISSUE THREAD

**Issue by tradanbattlan** [AprilSylph/XKit-Rewritten#228]
This was a vital feature of the previous New XKit. Inline ads must be defeated once more.

**Comment by AprilSylph** [comment]
https://github.com/AprilSylph/XKit-Rewritten/wiki/Excluded-features#anti-capitalism

**Comment by AprilSylph** [comment]
(if uBlock Origin isn't blocking sponsored post containers for you, try enabling all the AdGuard filters within it!)

**Comment by kaerstyne** [comment]
For anyone else with the same issue, here's how I set up uBlock Origin to block these:

Enable the **AdGuard Base** filter list in the Ads section to get rid of inline sponsored posts.

None of the filter lists worked for me to get rid of the Sponsored section in the sidebar, so I used a custom filter:
```
tumblr.com##aside h1:has-text(Sponsored):upward(3)
```
(That's likely to break if Tumblr changes the HTML, but it seems to work for now at least.)

**Comment by AprilSylph** [comment]
I've just added this to the wiki, but I've created a [script for generating EasyList-compatible filters](https://gist.github.com/AprilSylph/275bf9ba829fd5f3bdfb632f549b81da), and I've started contributing to EasyList.
