### ISSUE TITLE
No quick tags button

### ISSUE THREAD

**Issue by CarminaHughes** [AprilSylph/XKit-Rewritten#231]
- The browser I'm using is: Chrome with duck duck go privacy essentials extension (2021.9.2)
- My browser version is: 93.0.4577.63 
- My XKit Rewritten version is: 0.7.0

--- I added all the tag bundles I wanted, made sure quick tags was turned on, but there's no button for me to click in the tags area. Tried in regular and incognito modes, tried tumblr's "shiny new post editor" or not, turned off the duck duck go extension, even remembered to delete the old xkit, no button!

**Comment by AprilSylph** [comment]
XKit Rewritten does not affect any part of Tumblr's old interface; the button is only present on the beta post editor, next to the "Post now" button.

![image](https://user-images.githubusercontent.com/28949509/132252097-dd605884-daba-4153-a621-ff477e632d6f.png)

Do you not see it here? If not, what about if you enable the beta post editor, then close and reopen the new post form?

It may also be useful to know in what context you're opening the post form. I've previously observed issues with the reblog interface but not with the regular new post form, for example.

**Comment by CarminaHughes** [comment]
My new text post didn’t look anything like your picture, but I clicked on the ‘shiny new editor’ button and it did show up. Guess I wasn’t on the beta! Thanks for replying and showing me what it should look like <3


Sent from Yahoo Mail for iPhone


On Monday, September 6, 2021, 1:22 PM, April Sylph ***@***.***> wrote:




XKit Rewritten does not affect any part of Tumblr's old interface; the button is only present on the beta post editor, next to the "Post now" button.



Do you not see it here? If not, what about if you enable the beta post editor, then close and reopen the new post form?

It may also be useful to know in what context you're opening the post form. I've previously observed issues with the reblog interface but not with the regular new post form, for example.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
