### ISSUE TITLE
Option to scroll Quick Tags on Quick Reblog popup

### ISSUE THREAD

**Issue by daskiiii** [AprilSylph/XKit-Rewritten#233]
For users with a long list of Quick Tags, the Quick Reblog popup extends down the dashboard to the point of scrolling. Having the option to put Quick Tags in a scroll box like (old) New XKit 7 would be beneficial.

**Comment by SomethingBlue42** [comment]
Would also be great if the tags box was on top vs underneath the long list of tags like (old) New XKit 7
