### ISSUE TITLE
Other very helpful features to migrate from New Xkit, if possible

### ISSUE THREAD

**Issue by e-t-l** [AprilSylph/XKit-Rewritten#235]
I didn't see any mention of these within Excluded or Removed features in the wiki, nor elsewhere in this repo. If it's feasible from a coding perspective, please consider re-adding the following features that we found very helpful!

- Outbox
- Scroll-to-Bottom
- Glowing Follow (Could be a sub-option of Mutual Checker)
- (for Quick Reblog), One-Click Postage's ability to add tags AND caption directly from the popup

**Comment by AprilSylph** [comment]
- Outbox is planned as its own addon: https://github.com/AprilSylph/Outbox-for-Tumblr
- Scroll to Bottom is planned: https://github.com/AprilSylph/XKit-Rewritten/projects/4
- Glowing Follow will not be implemented on blog themes (on-blog controls are based on Tumblr's old code)
- Quick Reblog already allows adding a plaintext caption, the option is just disabled by default
