### ISSUE TITLE
Tag Tracking in the SideBar

### ISSUE THREAD

**Issue by schleeb** [AprilSylph/XKit-Rewritten#236]
The New XKit had a little Tag Tracking viewer that went in the sidebar and was super helpful; it actually took me a minute to realize the Tag Tracking in Rewritten was functional, because I was so used to the sidebar. It's minor, but I'd greatly appreciate it if this could be added!

**Comment by AprilSylph** [comment]
I decided to de-implement this as to avoid the question of how often to refresh the counts. See #100 for the full discussion regarding this!
