### ISSUE TITLE
Anti-Capitalism feature similar to old "New xkit"

### ISSUE THREAD

**Issue by zarunohn** [AprilSylph/XKit-Rewritten#240]
Hiya :)
Just started using your xkit yesterday, hoping to see an ad removing feature if possible? I use an adblocker and other script editors to remove ads, so there are no ads on my dash, but there 
is still a white square that has the "sponsored" symbol between posts occasionally. 
Would love to see this feature again.

Thanks! (I've attached a screenshot below)

![image](https://user-images.githubusercontent.com/90234754/132284696-9266eb9f-bb0e-4562-8b45-cd5883a3393c.png)

**Comment by invalidCards** [comment]
Please see the discussion on #228.
