### ISSUE TITLE
Quick tags missing

### ISSUE THREAD

**Issue by briangr2021** [AprilSylph/XKit-Rewritten#243]
- The browser I'm using is: Chrome
- My browser version is: 93
- My XKit Rewritten version is: 0.7.0

---
Quick tags option appears on reblogs, but not on original posts.  I disabled all of the other extensions to make sure they weren't interfering.  I have my default input set to HTML, but if I change n individual post to rich text it has no effect on the availability of quick tags. Since I can still use New Xkit the quick tag option from that will appear on original posts.

**Comment by invalidCards** [comment]
Please see April's response on #231. If it does not work for you, please provide the answers to the questions in that response here.

**Comment by AprilSylph** [comment]
>  I have my default input set to HTML, but if I change n individual post to rich text it has no effect on the availability of quick tags. Since I can still use New Xkit the quick tag option from that will appear on original posts.

You're definitely using the old post editor, which XKit Rewritten cannot affect. Continue using XKit 7 if you don't want to use the beta post editor.
