### ISSUE TITLE
Not starting up on tumblr for install

### ISSUE THREAD

**Issue by winterbells1** [AprilSylph/XKit-Rewritten#249]
- The browser I'm using is: Chrome
- My browser version is: 93.0.4577.63
- My XKit Rewritten version is: 0.7.0
 After installing the extension to Chrome through the chrome store, I  open tumblr in another tab and nothing happens. 
I reloaded the page and still nothing happened. I logged out and relogged in, still nothing.
Xkit Rewritten is enabled in the extension manager. What am I doing wrong?
---

**Comment by AprilSylph** [comment]
The addon doesn't do anything by default. You need to enable its options via the addon menu - click the icon in the browser toolbar to open the control panel. I believe in Chrome this is hidden under a generic "Extensions" icon by default.

**Comment by winterbells1** [comment]
Ah now I get how to use it. Thank you!
