### ISSUE TITLE
quick tags issue

### ISSUE THREAD

**Issue by ignorantdemise** [AprilSylph/XKit-Rewritten#252]
- The browser I'm using is: Microsoft Edge
- My browser version is: 93.0.961.38
- My XKit Rewritten version is:  0.7.1

---

the quick tags icon is far too large for the rest of the post and its causing some weird stuff to happen in the mobile blog view. this happens in the dashboard view of posts, and in the beta editor also.

![date](https://user-images.githubusercontent.com/15834707/132627050-0129573f-f819-4bee-971e-ff861523855e.PNG)
![beta](https://user-images.githubusercontent.com/15834707/132627596-19f1fdec-9be6-4373-a85b-381020e89a87.PNG)

**Comment by AprilSylph** [comment]
Unable to reproduce with XKit Rewritten 0.7.1 on Microsoft Edge Version 93.0.961.38 (Official build) (64-bit).

Does this still occur with all other extensions disabled?

**Comment by ignorantdemise** [comment]
somehow after restarting my computer and going into the profile, it seems to have resolved itself. not really sure what the conditions were for this to happen in the first place, but i guess it fixed itself.
