### ISSUE TITLE
Shuffle queue feature

### ISSUE THREAD

**Issue by tetrafacet** [AprilSylph/XKit-Rewritten#259]
Hi, glad to see someone is trying to make a version of xkit that works on the new version of tumblr. Is it possible to add a shuffle queue feature like the original xkit had?

**Comment by AprilSylph** [comment]
[Tumblr has a Shuffle Queue button already](https://new-xkit-support.tumblr.com/post/633581703605239808/is-enhanced-queue-on-the-docket-for-an-update).
