### ISSUE TITLE
Reverse sort Queue page

### ISSUE THREAD

**Issue by wovenstarlight** [AprilSylph/XKit-Rewritten#284]
### Concept

With a lot of queued posts, I'm having to scroll for ages to get to my most recently queued post (usually to change something small like an incorrect tag or the caption added). Reversing the order in which they're shown, so that the most recently queued shows up at the top, would save a lot of time.

**Comment by AprilSylph** [comment]
Not feasible, sorry. While it would be possible to visually reverse the queue, Tumblr would still load it in the same order, requiring you to still scroll down to load the most recent queued post.

**Comment by marcustyphoon** [comment]
This sounds like a feature to contact Tumblr support with! I'll bet they'd consider it.
