### ISSUE TITLE
Issue with garbage ads appearing in feed

### ISSUE THREAD

**Issue by erravit** [AprilSylph/XKit-Rewritten#285]
- The browser I'm using is: Chrome
- My browser version is: 93.0.4577.82
- My XKit Rewritten version is: 0.8.4

---Been seeing these garbagy sponsored posts/ads showing up in the feed lately. I know its not just a browser specific issue because they also are showing up on the mobile version of the website when I visit tumblr on my iphone using safari. I run ublock origin and updated all my filters multiple times, but it does nothing. I have all filters engaged on ublock as well, and even using the element picker doesn't work, it just comes back the next time you visit tumblr. Is there any way you can get rid of these? Thanks!
![crapihate](https://user-images.githubusercontent.com/91498509/134974060-628294f4-8fcb-4d94-95ef-0dbaa48c701e.PNG)

**Comment by AprilSylph** [comment]
Adblocking is out of scope for this addon, but I sympathise with not wanting to see ads. See easylist/easylist#9095 for some cosmetic filters you can add to the "My Filters" section in uBlock Origin to block current ads.
