### ISSUE TITLE
Quote Replies

### ISSUE THREAD

**Issue by ThibautNicodeme** [AprilSylph/XKit-Rewritten#287]
### Concept

There used to be a feature in older XKit implementations that let you take a reply to your post and let you make a new post to reply to that. Is that still possible with the way replies are now handled? It was better than having to also answer in the post's replies, which could quickly get crowded and are hard to keep track of.

**Comment by AprilSylph** [comment]
It should be possible, but it won't be the same; there's no way to safely populate the new post editor's content, so a custom interface will have to be built for it.

**Comment by marcustyphoon** [comment]
I am curious if Staff's mention of WordPress' Gutenberg editor that one time in a Changes post will culminate in the editor being materially different. Curious if we'd be able to control it more then. (I haven't looked at Gutenberg at all, so this could very well be an obvious dead end line of thinking to anyone who knows about it.)

Anyways, yeah, that was my thought too.

**Comment by AprilSylph** [comment]
Renaming the issue to match what I plan to use for the feature title. "One-Click Reply" isn't particularly descriptive IMO.
