### ISSUE TITLE
waterfox build

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [AprilSylph/XKit-Rewritten#300]
### Concept

xkit is falling apart I can't even hide my own posts anymore I need this for waterfox asap please

**Comment by neurodiverseEsoteric** [comment]
Why did you close this

**Comment by invalidCards** [comment]
If you're on the modern version of Waterfox, the site claims to be compatible with all web extension "shops", so you can download it from any of them.

If you're on the Legacy version, there is no way to port the extension to its extension framework as it is heavily outdated, and work will not be put into trying to support it.

**Comment by AprilSylph** [comment]
I'm not going to put any special effort in for any Firefox fork. If it's based off a new enough version it will work, if not there is nothing I am willing to do about it.

**Comment by marcustyphoon** [comment]
Sounds like XKit works fine in it (it's Firefox 93) and they're asking if you would recommend it as a browser. Which, I assume based on not having heard of it you have no informed opinion on.

**Comment by neurodiverseEsoteric** [comment]
> Sounds like XKit works fine in it (it's Firefox 93) and they're asking if you would recommend it as a browser. Which, I assume based on not having heard of it you have no informed opinion on.

Yes that's what I meant...
