### ISSUE TITLE
Autocomplete Tags on Quick Reblog

### ISSUE THREAD

**Issue by martinaj10** [AprilSylph/XKit-Rewritten#309]
### Concept

I had this happening on New XKit a long time ago on a different laptop where the tag field would give autocomplete suggestions as I typed and actually quite enjoyed it, as I tag in a consistent order but have too many possibilities across too many blogs for Quick Tags to be helpful.

Is this or something like it a possible feature that could be added?

**Comment by AprilSylph** [comment]
I suppose it would be possible to implement as a checkbox option.

**Comment by ZaCloud** [comment]
Voting in favor. :3

**Comment by AprilSylph** [comment]
@ZaCloud please follow the [issue guidelines](https://github.com/AprilSylph/XKit-Rewritten/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by AprilSylph** [comment]
I'm rejecting this feature because it would likely interfere with (or be outright broken by) suggested tags from posts, a feature I've just implemented in 0dddbcf029be01661711972e0c08dc7f36cbe206.
