### ISSUE TITLE
Postblock hiding un-liked posts

### ISSUE THREAD

**Issue by riftclaws** [AprilSylph/XKit-Rewritten#332]
### Platform

Windows 10

### Browser

Firefox 93.0 and 94.0.1

### Addon version

0.9.2

### Details

Unliking any post will remove it from the timeline as though it has been hidden. I first noticed this while running Firefox 93.0 and updated assuming it was the conflict, but this didn't fix the issue. Clicking "unhide the last hidden post" does seem to bring the post back. Example gif in link below:

https://imgur.com/QjpYSx7

(the same behaviour is present on my windows 7/firefox 94.0.1 installation/machine so it's reproducible at least in that version of firefox; i do not have new xkit installed so i don't think it could be conflicts. please let me know if you need a list of other addons i'm using but they aren't the same across both machines)

**Comment by marcustyphoon** [comment]
Based on that gif it looks like you might mean that *liking* the post causes it to vanish rather than the other way around; is that true?

Anyway, does this occur with all of your other extensions disabled?

**Comment by AprilSylph** [comment]
Unable to reproduce on Firefox 94.0.1. Liking or unliking posts does not hide them.

Is it definitely PostBlock's fault? Unblocking a post causes a style recalculation for all visible posts, so it could actually be something else, e.g. a weird adblocking filter list.

Please let me know if it still occurs
1. with all other browser addons disabled (you'll need to restart Firefox after doing so to be sure they aren't still active)
2. with all other XKit Rewritten features disabled (you'll simply need to refresh Tumblr after doing so, again just to be sure)

**Comment by AprilSylph** [comment]
this is probably caused by #335
