### ISSUE TITLE
Quick Tags button on a post that isn't mine

### ISSUE THREAD

**Issue by wordywarlock** [AprilSylph/XKit-Rewritten#334]
### Platform

Windows 10

### Browser

Firefox v94.0.1

### Addon version

v0.9.2

### Details

When I refreshed my dashboard, the post at the top had the Quick Tags button even though it belonged to someone else. It was positioned all the way to the right, ahead of the like button, and clicking on it brought up the drop-down with my tag bundles. I then refreshed the page again, returning it to normal. I didn't think to test if it would've allowed me to actually alter someone else's tags.

**Comment by AprilSylph** [comment]
It certainly wouldn't, but it seems post modifications are... fucked, right now. I've also noticed that Mutual Checker is being inconsistent, and just now have seen Vanilla Video failing to activate.
