### ISSUE TITLE
Tumblr reusing post elements breaks all post modification features

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#335]
XKit Rewritten's way of detecting and modifying posts is now broken due to a new ~~optimisation to~~ *bug with* Tumblr web which means post elements get reused rather than replaced upon soft refreshing.

This only affects the first four posts on the dashboard. Any modifications to these posts will stay on the posts, even when they become different posts. Doing a full page refresh, or switching between timelines, will make everything behave as expected until the next soft refresh.

Affected features:
- CleanFeed (incorrect retention of flagged blog status)
- Mutual Checker (incorrect retention of mutual status)
- PostBlock (incorrect retention of post blocked status)
- Quick Tags (incorrect retention of own post status) #334 
- Shorten Posts (incorrect retention of reported post height)
- Show Originals (incorrect retention of reblog status, author username)
- Timestamps (incorrect retention of post timestamp)
- Trim Reblogs (incorrect retention of own post status)
- Tweaks
  - "Hide filtered posts entirely" (incorrect retention of filtered status)
  - "Hide my own posts on the dashboard" (incorrect retention of own post status)
- Vanilla Audio (unable to detect new audio players until more posts are loaded)
- Vanilla Video (unable to detect new video players until more posts are loaded)

Any further bug reports detailing effects caused by this underlying issue will be closed. Please subscribe to this issue for updates instead of opening your own.

**Comment by AprilSylph** [comment]
This is going to be a huge task to fix.

Each feature currently assumes that any modifications made to a post should stay there until the post disappears, or until the user disables the feature.

This means that not only do modifications need to be made again to existing post elements, but that modifications any feature makes need to be undone upon that post element's `data-id` attribute changing. The new posts event will need to accept a new listener (`addCleaner`?) which cleans the post of modifications... or another solution for clearing modifications will be needed.

What a nightmare!

**Comment by AprilSylph** [comment]
cc @pfernandez at request of Kat

affected code is... the entire way posts are expected to be inserted, and the expectation that modifications to posts will not become modifications to other posts.

https://github.com/AprilSylph/XKit-Rewritten/blob/2ddb65a02158b476aa32a48d40fe0dcbc993747d/src/util/mutations.js#L44-L51

**Comment by AprilSylph** [comment]
Stopgap implemented in b38a06a and released with v0.9.3.

**Comment by marcustyphoon** [comment]
- The number of affected posts isn't always 4; for example, it's usually 17 on blog pages. I assume this is related to the pagination used in API fetches.
- Based on my (quite rudimentary) React knowledge, I would assume this is because post elements are currently using their array index as their React key, so when the dashboard is mutated, React diffs the elements with the element in the same numerical spot instead of inserting them. If so, I would imagine that qualifies as a fixable Tumblr bug rather than a performance optimization (as this would be a performance regression).

**Comment by pfernandez** [comment]
> I would assume this is because post elements are currently using their array index as their React key, so when the dashboard is mutated, React diffs the new elements with the old element in the same numerical spot instead of inserting them.

@marcustyphoon Yep, you're dead on, that's exactly what it was. @AprilSylph sorry for the trouble. Thanks so much for catching it and raising the issue. The fix is being deployed as I write this 😄
