### ISSUE TITLE
Quick Queue Fails to Queue

### ISSUE THREAD

**Issue by TumblrGirlWarlock** [AprilSylph/XKit-Rewritten#346]
### Platform

Windows 10

### Browser

Firefox 94.0.2 (64-bit)

### Addon version

0.10.0

### Details

The feature to quickly queue a post using the "Quick Reblog" configuration feature returns an error "Posting failed. Please try again."

Issue persisted through closing tumblr tab and restarting browser then opening tumblr tab again.

**Comment by AprilSylph** [comment]
This is an issue with Tumblr. Queueing via the beta post editor also fails.

Drafting posts through Quick Reblog and then queueing them from the drafts page works fine, in the meantime.

**Comment by AprilSylph** [comment]
This should be fixed now. In future, please be sure that any issues with Quick Reblog are not actually issues with Tumblr by attempting the equivalent action with Tumblr's beta post editor.
