### ISSUE TITLE
Enhanced Mass Post Editor

### ISSUE THREAD

**Issue by technopoet** [AprilSylph/XKit-Rewritten#350]
### Concept

I use the mass post editor a lot, and I think it'd be really cool if there was a way to publish/queue posts from it, and/or to make it so that when you right-click on a post, you can get a link to that drafted post, and not a "Not Found" page like it is now.

I have seen scripts that do this (like [this one](https://greasyfork.org/en/scripts/372566-tumblr-mass-post-editor-features), for example) but they're not updated often, and so they break whenever tumblr updates something.

I have no idea how hard this would be to implement - I just think it'd be really helpful. (...Mostly because I have a truly enormous amount of drafts, and it's becoming a problem xD)

**Comment by AprilSylph** [comment]
Since Tumblr's mega editor is based on legacy code, this is impossible for XKit Rewritten until it is updated.
