### ISSUE TITLE
QuickTags no longer working

### ISSUE THREAD

**Issue by RobBoyBlunder** [AprilSylph/XKit-Rewritten#359]
### Platform

windows 10

### Browser

chrome (64-bit)

### Addon version

v0.11.0

### Details

just yesterday the quick tags were working fine but today when I put them in on the quick reblog pop up, the tags aren't showing up after I hit the reblog. It still is reblogging the posts just fine, but it's not adding the tags i put in the quick tag box for some reason? I double-checked to make sure it's not user error on my part (yes i'm using the tags box and not the comment box and all that) and was wondering if this was a new issue?

**Comment by AprilSylph** [comment]
This is a bug with v0.11.0 which was patched in v0.11.1. Please force-update your extensions via chrome://extensions -> Developer mode to receive the fix.

**Comment by RobBoyBlunder** [comment]
thank you for the quick help, i appreciate your work a lot!
