### ISSUE TITLE
Quick Reblog Isn't Retaining Tags

### ISSUE THREAD

**Issue by fleurite** [AprilSylph/XKit-Rewritten#361]
### Platform

Windows 10 Home version 21H1

### Browser

Firefox 94.0.2.7993

### Addon version

Beta 0.11.0

### Details

The tags I add when using Quick Reblogs are not present on the post when published. This happens whether it's a reblog, drafted post, or queued post.

**Comment by AprilSylph** [comment]
This was fixed in v0.11.1. Update your addons to receive the fix.
