### ISSUE TITLE
Trim Reblogs - "legacy posts cannot be trimmed"

### ISSUE THREAD

**Issue by kailsera** [AprilSylph/XKit-Rewritten#364]
### Platform

Windows 10 ver 21H1

### Browser

Google Chrome ver 96.0.4664.93 64-Bit

### Addon version

0.11.1

### Details

Certain posts the trim reblogs function will not work. I had found it didn't work on old posts that had been using New xKit (not xKit Rewritten) but posts made using the old editor on browser (not the new beta editor) appear to not work.

However -- I have noticed the trim reblogs works fine if the _first_ post made was made using the new editor (the two instances it worked for me, the first/initial post was made by mutuals I know are limited to mobile). If you switch to/make your post with the new beta editor, then it is trimmable; if you're using the old version editor, it prompts the error that "legacy posts cannot be trimmed" -- even if there is zero formatting in the post. 

Initial posts I posted -- the bottom two are made with the new (beta) editor on desktop, the top two are made with the old legacy editor.
![image](https://user-images.githubusercontent.com/95714384/145873858-49c0b384-a529-4ee1-9ed9-91d26ce70a5f.png)

In the drafts, the bottom one cut with no issues, but the top one gives the error that "legacy posts cannot be trimmed". There is no formatting in the other posts. 
![image](https://user-images.githubusercontent.com/95714384/145873925-5b41e502-acbd-4972-b878-b3f2eae0d070.png)

I _have_ determined that if you go in and edit the original post -- the first reblog--on a mobile device (which changes it to the new format), it will then cut properly with no issues.

**Comment by AprilSylph** [comment]
That's correct. None of what you described is a bug; posts saved in the legacy format do not trim correctly, and Trim Reblogs refuses to action on them.
