### ISSUE TITLE
Quick Tags feature not working in existing Drafts posts

### ISSUE THREAD

**Issue by ghost** [AprilSylph/XKit-Rewritten#388]
### Platform

macOS 12.0.1

### Browser

Google Chrome 97.0.4692.71

### Addon version

0.12.2

### Details

It seems that Quick Tags feature is not working when you already have something in your drafts without any tags — it does not apply any tags from pre-made bundles

**Comment by AprilSylph** [comment]
Unable to reproduce. Reporter deleted their GitHub account, so no further troubleshooting is possible.
