### ISSUE TITLE
No Recommended: Block recommended posts

### ISSUE THREAD

**Issue by Avakining** [AprilSylph/XKit-Rewritten#394]
### Platform

macOS 12.1

### Browser

Firefox 96.0.1

### Addon version

0.13.0

### Details

Sometime today, the 'No Recommended' toggle no longer works (see attached screenshot
<img width="1216" alt="Screen Shot 2022-01-18 at 18 21 23" src="https://user-images.githubusercontent.com/25210618/150034557-93153902-66cb-4432-a4b6-3aaefc632a23.png">
)

**Comment by luxidoptera** [comment]
Having the same issue here.

![image](https://user-images.githubusercontent.com/15697751/150094919-04391025-3028-4acb-ad88-66fc44023f12.png)

**Comment by AprilSylph** [comment]
To be clear, this is not a bug. No Recommended does not inherently do anything, and there is no option for blocking recommended posts (as you can clearly see).

I will be implementing a new on-by-default option to block these new recommended posts which can't be opted out of via the dashboard settings.
