### ISSUE TITLE
Hide "Check out this post!"

### ISSUE THREAD

**Issue by xSke** [AprilSylph/XKit-Rewritten#395]
### Concept

Occasionally I see some random post show up at the top of my feed under a "Check out this post!" banner. I can't find a way to hide this either in Tumblr settings or XKit (No Recommended doesn't seem to catch this either).

Is there a way to block this? I do not want to check out that post.

![image](https://user-images.githubusercontent.com/16242158/150181132-867dc1fb-4628-4b65-8392-4d0a07490754.png)

**Comment by AprilSylph** [comment]
I don't have this update, so I'll need the HTML of the post container (with the `data-id` attribute) and the preceding `<div>` which contains the title text. I won't be doing any more work today, but if someone can put that here, I'll try to get it done tomorrow morning.

**Comment by xSke** [comment]
Is this what you need?

```html
<div class="So6RQ" tabindex="-1">
    <div class="ge_yK" tabindex="-1">
        <div class="HphhS">Check out this post!</div>
    </div>
</div>
<div class="So6RQ xkit-shorten-posts-done xkit-mutual-checker-done xkit-no-recommended-posts-done" tabindex="-1" data-id="672798190926528512">
    <!-- this is the post it's suggesting -->
</div>
```

The next sibling element is the "You're caught up" container (or the first "real" post).

**Comment by cyle** [comment]
FYI this is an experiment we're running at Tumblr currently for a subset of users, it'll be removed sometime soon-ish (this week I believe). If it comes back, we'll make its visibility controlled by one of the Dashboard Preferences, so hopefully you won't have to do anything with XKit. 😅

**Comment by AprilSylph** [comment]
Alright, I'll hold off on implementing this, then. Addon updates take a ~day to reach everyone, so if this test is only going to last another day or two, it's not worth doing.

I'd like to keep this issue open until the test is over. @xSke let me know on Sunday if it's still there, and I'll build something to get rid of it. Otherwise, feel free to close the issue yourself once it's gone.

**Comment by AprilSylph** [comment]
https://changes.tumblr.com/post/674010574294843392/friday-january-21st-2022
> We were testing out a new "Check out this post" and "Look at this post you made" recommendation at the top of the Following feed; this has been disabled. Thank you everyone who sent in feedback about this!
