### ISSUE TITLE
Option to only show verbose timestamps

### ISSUE THREAD

**Issue by amconners** [AprilSylph/XKit-Rewritten#398]
### Concept

If "Show extra verbose timestamps in post headers" is enabled, the shorter timestamp at the bottom of the post becomes redundant. An option to only show the verbose header timestamp would let users have access to all the information in that timestamp without also forcing there to be two timestamps on every post.

**Comment by AprilSylph** [comment]
This will be basically possible with the next release, as TimeFormat will allow you to customise Tumblr's native timestamps (which only appear in the post header, reblog headers, and on notes). Timestamps itself will probably be removed in a release after.
