### ISSUE TITLE
Timestamps Additional Position

### ISSUE THREAD

**Issue by transbimbozone** [AprilSylph/XKit-Rewritten#399]
### Concept

Nothing too complex tbh, just a small edit to propose an additional timestamps position. I just think it fills the space nicely is all lol
![image](https://user-images.githubusercontent.com/73834086/150449703-628e921e-8700-4708-9867-e08fac1d67b4.png)
Couldn't find any mention of this specifically in Feature Progress or the like, so hopefully this isn't already treaded waters
post unrelated lmaoo

**Comment by AprilSylph** [comment]
Timestamps is now in its sunset stage and will not be receiving feature updates. It will be replaced by TimeFormat, a feature which allows customising Tumblr's native timestamps, which you can enable in your [dashboard settings](https://www.tumblr.com/settings/dashboard).
