### ISSUE TITLE
Scroll to Bottom: Performance regression from 4-level descendantSelector

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#403]
### Platform

MacOS 10.14.6

### Browser

Edge 97.0.1072.69

### Addon version

0.14.0

### Details

<img width="1199" alt="Screen Shot 2022-01-21 at 5 00 04 PM" src="https://user-images.githubusercontent.com/8336245/150618185-6f41f8c9-33b7-49fc-9506-2af872f70214.png">

Scroll to Bottom's onBaseContainerMutated callback fires an expensive enough query selector that it causes a significant performance impact, especially since at present Tumblr is doing DOM mutations every time you scroll. (Haven't pinned down exactly why yet, but regardless).

What is this selector string? Funny you should ask. I was going to paste it here, but it is 40,000 characters long. Nested descendent selectors are a uniquely hilarious animal.

<img width="1376" alt="Screen Shot 2022-01-21 at 5 06 13 PM" src="https://user-images.githubusercontent.com/8336245/150618482-795674a5-a428-41e2-bffb-4747b9cd2ec5.png">

**Comment by AprilSylph** [comment]
Yikes!

I'll move the querySelector call. Hopefully I can reduce the size of this descendant selector too.

**Comment by marcustyphoon** [comment]
👍
