### ISSUE TITLE
Quick Reblog, Quick Tags, Timestamps, Mutual Checker all non-working

### ISSUE THREAD

**Issue by fallslikeicarus** [AprilSylph/XKit-Rewritten#409]
### Platform

Windows 10

### Browser

96.0.2 (64-bit)

### Addon version

v0.14.0

### Details

As of 20:00 GMT+8, XKit Rewritten's functions don't seem to be connecting to Tumblr. 
-One-Click postage lags on "Processing" stage when queuing/reblogging/drafting. 
-Time stamps shows 'loading' circle. 
-Quick tags button shows up, but doesn't add tags to the post
-Mutual Checker not loading

**Comment by AprilSylph** [comment]
This is now fixed in XKit Rewritten v0.14.2, available now from AMO and the Chrome Web Store.

Receive this update immediately
- on Chrome: `chrome://extensions` -> Developer mode -> Update all
- on Firefox: `about:addons` -> Gear icon -> Check for Updates
