### ISSUE TITLE
Quick reblog does not remember last blog selected between pages

### ISSUE THREAD

**Issue by irradiatedsnakes** [AprilSylph/XKit-Rewritten#412]
### Platform

Windows 10

### Browser

Firefox 96.0.2 (64 bit)

### Addon version

0.14.1

### Details

When the "remember the last blog selected in the popup" option for quick reblogs is selected, the selection only lasts on the current page- when a new page is opened or the page is reloaded, it defaults to the primary blog and the correct blog has to be selected again.

**Comment by AprilSylph** [comment]
That's correct. XKit Rewritten is account-neutral and does not store your blog name in its storage anywhere.
