### ISSUE TITLE
"Compact buttons" CSS to put reblog/like/etc buttons back in the bottom right corner of posts

### ISSUE THREAD

**Issue by e-t-l** [AprilSylph/XKit-Rewritten#413]
### Concept

This CSS should put the buttons back into the bottom right corner and make the whole post footer more compact. I haven't tested it in multiple screen resolutions, so let me know if there's any problems. I can open a PR with this ass a css src script if you like, but I don't know the details of the other scripts required to add a button to the popup, trigger the script, etc. 
```
.tOKgq {
  margin-top: 15px !important;
  padding-bottom: 10px !important;
}
.gstmW {
  height: 0px !important;
}
.G6mnk .MCavR {
  border-top: none !important;
  justify-content: flex-end !important;
  margin: 0px var(--post-padding) 0 var(--post-padding) !important;
  margin-top: -5px !important;
  padding: 0px !important;
  position: relative !important;
  bottom: 20px !important;
}
.sfGru {
  padding-left: 20px !important;
  top: 15px !important;
}
```

And this should be added if timestamps are enabled
```
.tOKgq {
  margin-top: 0px !important;
}
.sfGru {
  top: 5px !important;
}
:not(:empty) + .xkit-timestamp {
  position: relative !important;
  top: 25px !important;
}
```

**Comment by AprilSylph** [comment]
You're looking for the Tweaks option "Attempt to revert the post footer redesign".

**Comment by e-t-l** [comment]
Ah. Well now I just feel silly.

**Comment by AprilSylph** [comment]
No worries! I will probably need a CSS approach in future, so I might come back and reference this if I don't manage to grab the raw styles in time. Thanks for showing such a vested interest in the project.

If you'd like to learn more about the framework, check out the `doc/` folder at the repository root. If anything doesn't make sense, open a documentation issue and I'll see how I can improve it!

**Comment by AprilSylph** [comment]
Here's my CSS solution (using the util functions for taking advantage of Tumblr's CSS map):

```js
Promise.all([
  descendantSelector('post', 'footer'),
  descendantSelector('post', 'footer', 'controls'),
  descendantSelector('post', 'footer', 'controlIcon'),
  descendantSelector('post', 'footer', 'postActivityWrapper')
]).then(([postFooterSelector, controlsSelector, controlIconSelector, postActivityWrapperSelector]) => {
  styleElement.textContent += `
    ${postFooterSelector} {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding-bottom: 12px;
    }
    ${controlsSelector} {
      justify-content: flex-end;
      padding: 0;
      padding-right: var(--post-padding);
      border: none;
      margin: 0;
    }
    ${controlIconSelector} {
      margin-left: 20px;
    }
    ${postActivityWrapperSelector} {
      margin-top: 12px;
    }
  `;
});
```

I'm just going to stash this locally until it's needed, but I thought I'd put it here too for potential review / in case of disaster.
