### ISSUE TITLE
Mutual Checker not showing up?

### ISSUE THREAD

**Issue by LunarFirefly** [AprilSylph/XKit-Rewritten#414]
### Platform

Windows 10

### Browser

Firefox

### Addon version

0.14.1

### Details

Popped into my blog this morning, refreshed, and poof, mutual checker icons on the dash have disappeared.  No errors.  Disabled new xkit to make sure it wasn't interfering with Xkit rewritten, checked my other blogs to see if it impacted them as well, and restarted firefox.  Other blogs seem to still have mutual checker.  However I've had to contact tumblr a couple times because of weird bugs, and some of my blogs look and act different than the one missing mutual checker.  Like they've been updated, or features added by tumblr.  Last time I talked to tumblr support, they said that one of my blogs was selected for 'experimental features' or some suchness.  So there's varying differences between blogs. Two things changed with the one having issues.  The icons got larger and sit in a thick row at the bottom of the post.  Quick tags is no longer there either.  And I got an update notification from new xkit I think?  That two extensions had been updated.  I can't remember which exactly.

**Comment by AprilSylph** [comment]
Update to v0.14.2.
