### ISSUE TITLE
Various features not working

### ISSUE THREAD

**Issue by sunvulture** [AprilSylph/XKit-Rewritten#415]
### Platform

Windows 11

### Browser

Firefox 96.0.2 (64-bit)

### Addon version

Beta 0.14.2

### Details

Reblogs just say "Processing..." indefinitely. "Block this post" button doesn't respond at all. Timestamps are missing.

**Comment by adityahdes** [comment]
Mutual Checker is also not working, the indicator doesn't show up anymore.

**Comment by cheydinhal** [comment]
I am also having the indefinite processing issue, so I cannot reblog, queue, or add to my drafts.

**Comment by sunvulture** [comment]
As of right now, all is working again on my end!

**Comment by marcustyphoon** [comment]
Anyone commenting on this with a similar problem: please include what version of the extension you have! v0.14.2 should resolve many issues, so we need to distinguish between issues that are solved in that version and issues that may be persisting after it :)

**Comment by adityahdes** [comment]
Had to uninstall and reinstall on Firefox to get v0.14.2, but after updating it's all working again.
