### ISSUE TITLE
AccessKit Visible Alt Text: Visual issues with embedded tweets

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#421]
### Platform

MacOS 10.14.6

### Browser

Edge 97.0.1072.69

### Addon version

Master b1578fc (0.14.3 prerelease? ¯\\\_(ツ)_/¯); 0.14.2

### Details

AccessKit's visible alt text function causes some strange visual effects on an NPF-embedded tweet. Noticed on `https://transienturl.tumblr.com/post/674527432627372032`.

If I recall these correctly, these are: a) current master branch (after 4bd216b / d79907d) with `show all alt text`, 0.14.2 with `show all alt text`, and either with `only show image descriptions.` Apologies for not cropping.
<img width="1436" alt="Screen Shot 2022-01-27 at 3 19 36 AM" src="https://user-images.githubusercontent.com/8336245/151349771-d99009e3-24d9-4db9-beb4-aec09b81417b.png"> | <img width="1436" alt="Screen Shot 2022-01-27 at 3 23 34 AM" src="https://user-images.githubusercontent.com/8336245/151349796-0245e014-cbe2-44a4-ba11-23c37018432c.png"> | <img width="1436" alt="Screen Shot 2022-01-27 at 3 19 44 AM" src="https://user-images.githubusercontent.com/8336245/151349784-6553af6b-ade9-42a1-b8f7-64c37988e87f.png">
-- | -- | --
 
I didn't fully understand the CSS at play here. The `height: 100%` CSS is applied to `processedClass` (and thus every image even if we are not adding a caption), which definitely causes the gap in the third image, but is of course innocuous normally. Didn't check what is different in this case.

**Comment by AprilSylph** [comment]
I fixed this in abf3479a69f4bccd70979d25dc6608d693409d89.

**Comment by marcustyphoon** [comment]
...Uhm. Oops. This is what happens when you don't press fetch.
