### ISSUE TITLE
New Xkit menu hidden from dashboard in the top hotbar

### ISSUE THREAD

**Issue by lucasrosenberg** [AprilSylph/XKit-Rewritten#423]
### Platform

macOS 10.14.6

### Browser

Firefox Version 96.0.2 (64-bit)

### Addon version

0.14.3

### Details

In the top hotbar the New Xkit button is now gone. New Xkit is still enabled as an extension in my Firefox and its features seem to still be active? No way to open New Xkit settings though. I dont know the technical term for the hotbar I'm talking about so I'll post my screenshot below but the New Xkit menu used to be accessed between the activity and profile buttons iirc 
![image](https://user-images.githubusercontent.com/58640671/151390339-159957c0-e7bd-4d3c-9d9a-037cf6448685.png)

**Comment by AprilSylph** [comment]
This is not the New XKit issue tracker. Your issue is logged at new-xkit/XKit#1869.
