### ISSUE TITLE
Causing issues with Instagram for some reason??

### ISSUE THREAD

**Issue by rowantobias** [AprilSylph/XKit-Rewritten#424]
### Platform

Windows 10

### Browser

Firefox (96.0.3)

### Addon version

0.14.3

### Details

Went to Instagram, as one does, but screen was white. Firefox console reads as such:
ErrorUtils caught an error:

```
t.user_data is undefined

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs. 3c766806a7fc.js:4:7510
Error: Promised response from onMessage listener went out of scope background.js:841:170
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://graph.instagram.com/logging_client_events. (Reason: CORS request did not succeed). Status code: (null).
```

And I can't remember what I did to get this one, but another error that pointed me in XKit's direction:
![unknown](https://user-images.githubusercontent.com/11569229/151643654-f5a055d3-060e-4187-9c05-dd90d20ffc0b.png)

And so, I disabled the addon, and when I did that and reloaded, Instagram finally loaded. I don't really know why this happened. I am sorry. Thank you.
​

**Comment by marcustyphoon** [comment]
Not an expert, but I don't see anything in those messages suggesting that XKit Rewritten is related to this problem (first one is definitely Instagram's React code); it seems likely that refreshing the page fixed it on Instagram's side independently of the extension being toggled!

**Comment by AprilSylph** [comment]
XKit Rewritten does not interact with webpages which do not match `"*://www.tumblr.com/*"`. If you run into the latter error again and can tell me more about it, please open a new issue describing what you were doing when it occurred.
