### ISSUE TITLE
Mutual checker: Inconsistency in inbox(?)

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#427]
### Platform

MacOS 10.14.6

### Browser

Edge 97.0.1072.69

### Addon version

0.14.3 (plus likely-irrelevant dev commits)

### Details

Mutual checker does not indicate you are mutuals with the sender of an ask if the ask is to any of your blogs that you are not following. I think. Something like that.

(To be clear, this isn't a hypothetical bug; I'm pretty sure I am missing mutual indicators on asks sent to my main, but I see some on asks sent to my alt. Not 100% sure I have the specifics right though.)

---

I was reading through the mutual checker code for an unrelated reason (thinking about unmemoized timelineObject intricacies) and I remembered that I didn't quite understand the code added in eb0ad270964fb2454726448dd2560ad71ee01312, so it seemed like a reasonable idea to suggest commenting or refactoring it a bit. Sure, I don't have to understand every piece of code in this repo, but it seems like a decent litmus test for whether someone else might understand it in general.

Then I tried to figure out how it works, and maybe potentially found a bug?

I see from the commit label that this code handles the inbox, and I observe that - I think - in the inbox, the `blog` timelineObject property is the blog that receives a message rather than the one who sent it. Assuming this is an accurate description, the current code short circuits based on whether you are following the blog which was the message recipient (i.e. one of your own blogs), so if you are not, it does not get to the code which is supposed to handle the inbox discrepancy.

If my assumptions are correct, and
```
if (blogName === blog.name) {
  // use timelineObject.blog
} else {
  // ignore timelineObject.blog; apiFetch based on blogName
}
```
is correct, I could PR this. However, I wanted to make sure I understood it first, as I am aware that more types of content can wind up in the inbox than I can enumerate offhand (something something private replies to a sideblog?) and so I'm not confident I can visualize/test the entire set of possible situations without help.

**Comment by AprilSylph** [comment]
https://github.com/AprilSylph/XKit-Rewritten/blob/f313a2862c26cd710dfb3a7ee2924675774850fc/src/scripts/mutual_checker.js#L28-L29

Yep, this is erroneous. I forgot that the "inside Tumblrs" labs experiment is not default and that it's possible not to follow your own sideblogs.
