### ISSUE TITLE
Default tag for reblogs

### ISSUE THREAD

**Issue by Hannah-GBS** [AprilSylph/XKit-Rewritten#434]
### Concept

I see that the Quick Tags feature has options for default tags for created posts and asks, but not for reblogs. This is a feature that old Xkit had in Auto Tagger. Was this specifically not included or just missed?

**Comment by AprilSylph** [comment]
It has not been included because of the questionable merits of including the feature in addition to the queue tag option in Quick Reblog.

**Comment by Hannah-GBS** [comment]
I'm not sure how using the queue feature is related to wanting to be able to one-click reblog stuff with a default tag

**Comment by AprilSylph** [comment]
The reason that was presented to me for using a queue tag was twofold:
1. announcing that you are not online, and
2. categorising queued content as "filler", i.e. not related to what you usually *post* about, i.e. reblogs.

Setting a queue tag in Quick Reblog will only apply that tag to queued reblogs. Ergo, it doubles as a reblog tag if you queue all your reblogs.

I suppose my judgement is somewhat skewed by my personal habits; I don't use a queue tag, but I do queue the vast majority of my reblogs. If I did use a reblog tag, it would be functionally identical to using a queue tag. If you could explain in more depth how your experience differs, it would be helpful in deciding if the feature is worth adding.

**Comment by Hannah-GBS** [comment]
Ah see I literally never queue stuff, I just straight reblog it.

Not arguing the utility of the queue tag for sure, just meant to say it doesn't replace the default tag from Auto Tagger for my use-case. As it is I _can_ 2-click by just having a "Default" tag bundle set in Quick Tags and clicking that before Reblog in the Quick Reblog menu, but I've forgotten to apply it half the time as I adjust to it.

**Comment by AprilSylph** [comment]
What's your reason for adding the same tag to all your reblogs?

**Comment by Hannah-GBS** [comment]
I don't tag _all_ my reblogs with it but most things I reblog I tag with `#GNU Terry Pratchett` and have done since he died.

I feel like there are definitely other less weird uses for a default tag but it's possible it is in fact super super niche.
