### ISSUE TITLE
Attempt to revert post footer design shifts to left side with Timestamps enabled

### ISSUE THREAD

**Issue by dottiekh** [AprilSylph/XKit-Rewritten#435]
### Platform

Windows 10

### Browser

Firefox 96.0.3 (64-bit)

### Addon version

0.14.4

### Details

Reverted footer design gets shifted below notes when the buttons run out of room. This was made noticeable with the added note type icons next to the notes number. Easily reproduced with Timestamps enabled, & more noticeable on self reblogged/posted posts.

Footer without Timestamps:
![image](https://user-images.githubusercontent.com/34873184/151943989-282f1f0d-6131-4a0e-acc1-71ae546f1059.png)
![image](https://user-images.githubusercontent.com/34873184/151944005-e16fe9d9-2cfe-451e-a13e-167f38e92fea.png)

Footer with Timestamps:
![image](https://user-images.githubusercontent.com/34873184/151944123-13174496-4376-477e-a9a6-ebdee5181620.png)
![image](https://user-images.githubusercontent.com/34873184/151944138-6ba79fd2-1b10-41fc-892a-3b9133533e45.png)
![image](https://user-images.githubusercontent.com/34873184/151944156-65cc0114-95fe-411e-91ae-369db6b07441.png)
![image](https://user-images.githubusercontent.com/34873184/151944434-0efabac0-a776-46e7-9aab-e87fe85ee465.png)

**Comment by marcustyphoon** [comment]
(Note that this happened before the post footer change if you had the new notes view, as both of my accounts have had for a while. So this isn't an issue specifically with the code that reverts the footer change. Either way, it's quite annoying, and I would definitely like a more elegant way to handle it!)

**Comment by AprilSylph** [comment]
Disable Timestamps - it is a sunset feature which will be removed at a future date. Enable Tumblr's own timestamps in your dashboard settings and customise them with TimeFormat instead.

**Comment by marcustyphoon** [comment]
Even without timestamps, it's possible for the footer to run out of space.

![image](https://user-images.githubusercontent.com/8336245/151946892-2aa171f3-7825-49be-8ed0-d7073b294951.png)
