### ISSUE TITLE
Vanilla Video Not Removing Original Tumblr Video

### ISSUE THREAD

**Issue by kevin-pwt** [AprilSylph/XKit-Rewritten#449]
### Platform

Windows 10

### Browser

Firefox 96.0.3

### Addon version

0.14.6

### Details

Vanilla Video is failing to remove Tumblr video embed.
![image](https://user-images.githubusercontent.com/98774468/152510887-1b82347c-8621-41bf-bcd2-440433989b49.png)
![image](https://user-images.githubusercontent.com/98774468/152510913-5e9ab8b8-6ea3-47bc-96d1-cfbbaaf7c5b6.png)

**Comment by AprilSylph** [comment]
Does this still occur after reloading the page? Vanilla Video's repetition prevention was changed in v0.14.6, and Firefox runs updated versions of addons immediately on pages, easily resulting in this effect until you perform a page reload to properly clear the effects of the previous addon instance.

**Comment by dottiekh** [comment]
Ah, yeah, it went away after a refresh.
