### ISSUE TITLE
Hide Filtered Posts tweak: Possible to desync UI / caching discussion

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#452]
### Platform

MacOS 10.14.6

### Browser

Edge 97.0.1072.76

### Addon version

Master c1b577f

### Details

Because the filtered posts tweak uses timelineObjectMemoized, and because some of the Tumblr settings page is now part of the new web platform (React/Redpop), it is possible to desync its UI from the current state by navigating to settings, filtering or unfiltering a word or tag, then navigating back to a page with a post containing the relevant word or tag. The hidden/unhidden state will have been cached from before the preference change.

This is obviously nearly impossible to run into or notice and may not be worth solving, but it does serve as a good example of the principle that we should be somewhat careful using timelineObjectMemoized as more of the site migrates to soft refreshes. I see no instances in the current codebase where this would be a significant issue, but there are a few minor ones and it's something to keep in mind for the future.

I had some ideas about caches that conditionally clear themselves, which could be a way to solve things like this in the future while still taking advantage of a cache. For example, a cache like timelineObject or userBlogs could be instructed to clear itself if you navigate off of a settings page, ensuring that whatever settings you may have changed cannot be the cause of unintended behavior.

**Comment by AprilSylph** [comment]
I think a better solution in this case would simply to skip reading the `timelineObject` at all. The tweak could instead simply find filtered screens within posts and hide the ancestor `article`.

I think I relied on it a lot more than I really needed to because of the pain of constructing good selectors, which is all but trivialised by `resolveExpressions`.
