### ISSUE TITLE
Tag bundles in Quick Reblog are squished

### ISSUE THREAD

**Issue by schwizzlers** [AprilSylph/XKit-Rewritten#466]
### Platform

macOS 10.14.6

### Browser

Chrome 98.0.4758.80

### Addon version

0.14.6

### Details

When hovering over the reblog button on the dashboard, the tag bundles in the Quick Reblog popup appear squished/cut off.
If it helps, I'm loading the extension in from Github Desktop, I'm not using the Chrome Web Store version.
I tried toggling the Quick Tags integration option on/off, as well as clearing cache, but the issue persists. The tag bundles appear normally in the Quick Tags popup window when creating a post. Running the latest version of Chrome for my device.

<img width="207" alt="Screen Shot 2022-02-09 at 9 14 04 PM" src="https://user-images.githubusercontent.com/48602645/153330727-9fd6f222-c979-43ee-bd4a-3657cdb225a4.png">

**Comment by marcustyphoon** [comment]
👍  Thanks for specifying that you're running directly off the master branch! This appears to be a side effect of 3eb7934!

**Comment by AprilSylph** [comment]
I'm unable to reproduce this on Chrome 100.0.4867.0 (Official Build) dev (arm64) with 25319e18886d5baaada9311f54c3f810874f1c4f, but I'll loosen up the overflow rule to see if it helps.

P.S. If you're not installing from AMO or the Web Store, put the commit you're running in the version field!

**Comment by AprilSylph** [comment]
@schwizzlers Please let me know if the latest commit solves this problem for you!

**Comment by marcustyphoon** [comment]
Making sure I definitely grabbed the right commit, but I am still seeing it. Edge 98.0.1108.43. Did you make enough tag bundles so they don't all fit, April? Do yours scroll?

**Comment by marcustyphoon** [comment]
Yep, still seeing it in both Firefox (98.0b2) and Edge. Setting `overflow-x` to anything except `visible` seems to make flexbox squish the element's size down, and I have no clue why that would be related.

**Comment by AprilSylph** [comment]
Okay, yep, I see the problem, and the solution. Honestly, not sure why this wasn't a problem before. Flexbox interacts with non-flexbox properties in strange ways sometimes...
