### ISSUE TITLE
exposeTimelines utility can give stale results in peepr

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#467]
### Platform

MacOS 10.14.6

### Browser

Edge 98.0.1108.43

### Addon version

Master 25319e1

### Details

When Peepr is opened by clicking on a blog's username in certain cases, it opens the blog in question with the single post you clicked on and a "show all posts" button that navigates to the typical view of that user's blog.

This "show all posts" button's functionality is not implemented in Tumblr's code by unmounting the timeline element, evidently, because exposeTimelines doesn't detect any attribute-less elements after it's clicked, and the data attributes remain as what they were when Peepr was initially opened, i.e.`data-timeline="/v2/blog/nostalgebraist-autoresponder/posts/675762381622804480/permalink"` rather than `data-timeline="/v2/blog/nostalgebraist-autoresponder/posts"`.

This could be solved by unconditionally processing every timeline each time exposeTimelines is run, which feels a bit wasteful. Thinking about a better way to do this.

**Comment by marcustyphoon** [comment]
I did just realize that, assuming the "show all posts" button in Peepr (both old and new beta versions) is the only place where this happens, this could be ignored and the state of the timeline could be inferred from `location.pathname` in scripts that care about this (currently only Show Originals) instead.

However, I still think it makes sense to fix this (instead of, I dunno, putting a warning in the JSDoc or something).

**Comment by AprilSylph** [comment]
Just ran into the same problem with Tag Tracking+. Tried switching to a timeline RegExp approach instead of just peepr-excluding, but changing between followed tags doesn't unmount the timeline itself.

**Comment by marcustyphoon** [comment]
...Wow. Huh. Okay. I guess the React developer side of me is like, "oh neat, you avoided unnecessary DOM manipulation!" and the extension developer side is like, really?

**Comment by AprilSylph** [comment]
Hopefully this can someday be solved perfectly by Tumblr including the `data-timeline` attribute itself like I want it to...
