### ISSUE TITLE
Video ad container not caught by Anti-Capitalism

### ISSUE THREAD

**Issue by luxidoptera** [AprilSylph/XKit-Rewritten#477]
### Platform

Windows 10

### Browser

Vivaldi 5.1.2567.39

### Addon version

v0.15.0

### Details

I figured I would leave an issue here to provide an alert about this new (or at least new-to-me) video ad container that appears at the top of the dashboard, which currently is not caught by Anti-Capitalism (nor is it caught by my adblocker).

![image](https://user-images.githubusercontent.com/15697751/153654176-cecf73a6-e2e6-412f-8e73-110b2dda588a.png)

**Comment by AprilSylph** [comment]
I've already contributed a filter to EasyList for this (easylist/easylist#10825) which is pending approval. By the time I was finished with that PR, the video ad was gone, so I was unable to test a fix for Anti-Capitalism. Hopefully I'll get another chance next week.
