### ISSUE TITLE
Notifications util: display in new blog view sidebar

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#483]
I guess the new priority list should be
- drawerContent sidebar
- drawerContent
- sidebar
- body

(unless I'm forgetting something)

**Comment by marcustyphoon** [comment]
Hmm... the sidebar in the new blog view drawer (er... not drawer anymore, I guess, but anyway) isn't unmounted when the page width changes; it looks like it's just a media query. That's a bit of a pain. I'll look if anything else changes. Not the end of the world, though; we can just use `window.getComputedStyle` to check.
