### ISSUE TITLE
Quick Tags/Quick Reblog: Warn about quotes in tags

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#489]
### Concept

It would be nice to have a warning when you put more than one `"` character in a quick tags/quick reblog tag, which causes it to be split into multiple tags in a strange way. This behavior comes from Tumblr, and the native post form doesn't warn you about this, but it would still be nice. (I try to put quotes in tags... a lot.)

Are there other ways to input text into the tags box that will have unexpected results? I don't know of them off the top of my head, but I feel like there must be; consider this a request to warn on those also.

If you think this is a good idea and we have a good list of conditions, I can self assign this. (First thought: check with a regex in `updateTagSuggestions`; add a 1px red outline. Could also use the regex attribute and `::invalid`, I assume, if it still allows you to submit.)

**Comment by AprilSylph** [comment]
I've thought about just silently replacing the doublequotes with that one looks-like-doublequotes-but-isn't-the-same-codepoint character which I would have to find again. If people want to use quotes in tags, I think we should let them! I've misplaced the unicode character, though.

**Comment by AprilSylph** [comment]
Okay, looks like I'm misremembering (there *is* a homoglyph for commas), so we have three options for doublequote replacement:

1. `.replace(/"/g, '\'\'')` (two singlequotes)
2. `.replace(/"/g, '\u201D')` ("double right quotation mark")
3. `.replace(/ "/g, ' \u201C').replace(/"/g, '\u201D')` (very basic attempt at smart quotes)

Examples of all three visible at https://april-codes.tumblr.com/post/676567426892251136/quotes-me-captain

**Comment by marcustyphoon** [comment]
Oh, cute! I think I like 3 the best. 1 looks good visually as well but seems somewhat counterintuitive if you go to the tagged page, copy-paste a tag, etc. 3 feels at least plausibly like a native site feature, which I think is generally a good sign (as long as we don't make too many people think XKit features actually are native site features :D)
