### ISSUE TITLE
Certain plugins crash Firefox Nightly

### ISSUE THREAD

**Issue by Astral-Crescent** [AprilSylph/XKit-Rewritten#494]
### Platform

Windows 11

### Browser

Firefox Nightly 99.0a1

### Addon version

0.15.4

### Details

As of yesterday, any XKit Rewritten feature that modifies the appearance of Tumblr simply crashes the tab. Access Kit, Tweaks, etc.  

How to replicate: Open Tumblr on Firefox Nightly, install XKit Rewritten, and enable plugins that alter the appearance of Tumblr.

![firefox_QQkENLx3aU](https://user-images.githubusercontent.com/92853912/155568100-51b87b86-e32f-4059-8755-e0bbd8c6fbbc.png)

**Comment by marcustyphoon** [comment]
Can reproduce in 99.0a1 in MacOS 10.14.6. The distinction seems to not be whether a script modifies Tumblr, but whether it's in AccessKit, No Recommended, or Tweaks: the ones whose frameworks use dynamic import() outside of main.js.

**Comment by AprilSylph** [comment]
AccessKit/NR/Tweaks could probably be changed to use static imports either way, at the cost of extra internal complexity. Definitely something to report on bugzilla though.

**Comment by AprilSylph** [comment]
Reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1757071

**Comment by marcustyphoon** [comment]
This appears to be fixed in Nightly 99.0a1 (2022-02-24) 20220224214601.
