### ISSUE TITLE
Open In Tabs not working from Activity

### ISSUE THREAD

**Issue by amconners** [AprilSylph/XKit-Rewritten#500]
### Platform

Arch Linux 5.16.8-arch1-1

### Browser

Firefox 97.0 (64-bit)

### Addon version

0.15.4

### Details

Prior to the new Tumblr update clicking a link on the Activity dropdown or on the Activity page itself would open the resulting post in a new tab by going to the target blog (i.e. `blogurl.tumblr.com`). After the update, it'll still open a new tab, but it opens the `tumblr.com/blog/view/blogurl` link instead.

**Comment by AprilSylph** [comment]
Open in Tabs is working correctly. Opening notification links in new tabs via other methods (the right-click menu or CTRL+click) would produce the same result.

Please [report this to Tumblr support](https://www.tumblr.com/support). Hopefully they at least explain what the motivation was behind this change.

**Comment by AprilSylph** [comment]
Reopening since the blog view change appears to be intentional, with more links changing to use it too. Open in Tabs specifically sells itself as a way to disable the blog view, so even though the current behaviour is technically working, it no longer accomplishes what people want it for.
