### ISSUE TITLE
Panorama only works on some posts

### ISSUE THREAD

**Issue by Skaramuche** [AprilSylph/XKit-Rewritten#531]
### Platform

Win10

### Browser

Firefox 98.0.1

### Addon version

v0.17.3 beta

### Details

Panorama widens the white column of posts, but only actually widens the _content_ on roughly _half_ of posts.

![Screenshot 2022-03-23 191138](https://user-images.githubusercontent.com/10238225/159811745-58c8f9df-f1fc-4f5e-9179-bcd5ac42eca0.png)

I don't see any immediate reason why given posts are or aren't wide; it doesn't seem to go by post type or by poster. I even saw someone self-reblog their own post, and one version was wide, then the second one wasn't.

I only switched from New XKit to Rewritten today because the same issue just started affecting New XKit so I assume this problem is new to XKR as well and caused by some change tumblr-side.

**Comment by AprilSylph** [comment]
This was fixed in e7a90c1812adf38b3b6c1af490567d7ad31317be. Look out for v0.18.0 tomorrow!
