### ISSUE TITLE
Accesskit's pause gifs is incompatible with tumblr's shorten post setting

### ISSUE THREAD

**Issue by Pandasaurus-Rex** [AprilSylph/XKit-Rewritten#536]
### Platform

Windows 10

### Browser

Chrome 99.0.4844.84 (Official Build) (64-bit)

### Addon version

Beta 0.19.0

### Details

When using tumblr's new 'Shorten Posts' setting along with Accesskit's 'Pause gifs until hovered over' setting it creates an issue in any shortened post where the 'Expand' bar would lay on top of a gif. When going to expand the post you can't because the gif tries to play at the same time the expand banner is trying to pop up, so you just get a ton of flickering. This happens both with xKit's Shorten Post turned on and when it's turned off. If I turn off the pause gifs setting then tumblr's expand bar works as intended. 
![flicker2](https://user-images.githubusercontent.com/25313241/160452986-35379376-988e-4418-b329-fe65174622e2.gif)

**Comment by marcustyphoon** [comment]
Ah, interesting - tumblr's expand button isn't z-indexed, so it will be underneath the disable gifs canvas element unless we either remove the z index on the canvas or add one to the expand button, I assume?

**Comment by AprilSylph** [comment]
The z-index on the canvas cannot be removed without breaking the feature, as `<img>` elements are removed by Tumblr when scrolled away from and appended back to their containers as needed, making it impossible to rely on the canvases being after the images in the DOM and thus drawn on top.

The expand button will need to given an increased z-index to fix this.

**Comment by AprilSylph** [comment]
I imagine this also affects CleanFeed.
