### ISSUE TITLE
Using Quick Tags removes image descriptions

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#542]
From an ask:
> When I use Quick tags to add another tag to one of my posts, if there is an image, it wipes the image description of it back to "Image". I'm using Firefox + Xkit Rewritten.

This seems strange to me as everything about the post other than `tags` should be preserved.

**Comment by marcustyphoon** [comment]
Confirmed. And I would assume this is a Tumblr bug similar to the one that made editing a post with the actual Tumblr editor discard image description data.

**Comment by AprilSylph** [comment]
As I thought, the `GET` request for the post receives every variable in camelCase because it's coming from redpop, but the server (presumably) only accepts snake_case. It looks like the editor just converts everything back to snake_case...

**Comment by AprilSylph** [comment]
While I think about how to make a function which doesn't suck that recursively replaces camelCase keys with snake_case keys I'm gonna cc @cyle to see if he's aware of this oddity. 🤭
