### ISSUE TITLE
XKit 7 compatibility: Disable Gifs label

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#550]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 100.0.1185.36

### Addon version

v0.19.2

### Details

Because XKit 7 and XKit Rewritten both use the `xkit-gif-label` classname, their styles conflict.
<img width="551" src="https://user-images.githubusercontent.com/8336245/162836415-56c8acf6-6061-438f-ab8f-6e96c71e8f73.png">

**Comment by marcustyphoon** [comment]
I can go think of something else to change this class to (and maybe check some more classnames manually); do you think there's anything to be done about this in general, or should we not worry about it considering that xkit 7 is so unlikely to be updated and cause future conflicts?

**Comment by AprilSylph** [comment]
I'm not a fan of prefixing everything with `xkit-rw-` or anything similar, if that's what you're asking.

**Comment by marcustyphoon** [comment]
Yeah, me neither. Just wanted to make sure you didn't have anything in mind that I hadn't thought of!
