### ISSUE TITLE
Show Originals: Blacklist

### ISSUE THREAD

**Issue by avalonv** [AprilSylph/XKit-Rewritten#551]
### Concept

Implement a toggle that turns the whitelist in Show Originals into a blacklist, i.e. always show reblogs from everyone _except_ from these users.

**Comment by AprilSylph** [comment]
Options for hiding reblogs from specific users is something I have planned for the revival of Mute

**Comment by avalonv** [comment]
I see. I look forward to seeing that implemented. Love this extension.
