### ISSUE TITLE
Old Footer Change not Working

### ISSUE THREAD

**Issue by BarryAllen2024** [AprilSylph/XKit-Rewritten#553]
### Platform

macOS 11.6.5

### Browser

Chrome Version 100.0.4896.88

### Addon version

v0.19.2

### Details

The footer change to the original one is back to the current update. This only happened a couple of minutes ago, and worked fine during the rest of the day. Restarting Tumblr did not help. I have the "tweaks" part on, along with "attempt to revert the post footer design" checked off.

**Comment by AprilSylph** [comment]
Work partially done in https://github.com/AprilSylph/XKit-Rewritten/issues/413#issuecomment-1025789036, needs updating & implementing
