### ISSUE TITLE
Option to hide the new Tip button

### ISSUE THREAD

**Issue by hedgehog1029** [AprilSylph/XKit-Rewritten#572]
### Concept

Add an option to Tweaks to hide the new tip button on some posts.

(I prefer to keep dashboard posts clear in order to take clean screenshots)

**Comment by marcustyphoon** [comment]
Hm. You could do this for a screenshot with the Javascript snippet `[...document.querySelectorAll('button[aria-label="Tip"]')].forEach(element => element.style.display = 'none')`.

**Comment by AprilSylph** [comment]
I don't think this aligns with the project. The ability to monetise your own content on Tumblr does not significantly impose upon others' experience.

If tip buttons are somehow unsightly for screenshots, you can always edit them out, or use the snippet above if your dashboard language is set to English.
