### ISSUE TITLE
Inconsistent quick reblog/quick tags position w/ slim footer

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#573]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 100.0.1185.44

### Addon version

0.19.3 / master b736949

### Details

Very minor CSS inconsistency:

https://github.com/AprilSylph/XKit-Rewritten/blob/b736949d4d6dd9d45874f2af3734cc771b9a1eb0/src/scripts/tweaks/footer_unredesign.js#L28-L30

These tweaks to the quick reblog and quick tags popup positions apply in the narrow-ish form of the blog view only when it is a modal over the screen. If I recall correctly, this part of the CSS was exclusively created to deal with the old peepr modal and can be removed assuming that that code is no longer served.

**Comment by AprilSylph** [comment]
This was intentional. See the commit message on 115f46674490fb0e7d98d41b404346daeacde3a4

**Comment by AprilSylph** [comment]
> only when it is a modal over the screen
Nope, you're right, this could be an oversight regarding the non-modal form of the blog view. Do the popups get cut off by the boundaries of the non-modal blog view?

**Comment by marcustyphoon** [comment]
Oh, I see what you're saying! They do not, so this is fine 👍 

![image](https://user-images.githubusercontent.com/8336245/164996534-7b9dfe2a-21b6-4ce4-b70a-9a94e7d234ab.png)
