### ISSUE TITLE
apply dashboard posting shortcut to post composition mode

### ISSUE THREAD

**Issue by Circeus** [AprilSylph/XKit-Rewritten#577]
### Concept

I think on the worst usability failure of tumblr was switching to form elements that aren't actual form elements and cannot be triggered from the keyboard. If I want to queue a post in composition mode, I have to do three mouse clicks on desktop (open the hidden menu, select queue and then click to actually queue) instead of just tabbing to the d*** form element and pressing enter (as I used to do before this wretched system was introduced). Given that right now I can't even _use_ a mouse (dominant arm injured) and have to do this all with the mouse keys, it's just preposterous.

Is it possible to make the alt+Q and alt+R keyboard shortcuts functional in composition mode?

**Comment by marcustyphoon** [comment]
Do you have the beta post editor enabled (using the toggle in the top right of the compose screen)? I observe that tab navigation fails to select the post/queue/draft button with the beta **disabled** and works perfectly with the beta **enabled**.

![image](https://user-images.githubusercontent.com/8336245/165354820-256ff45d-a7fe-4dcf-be17-72b49c653aa8.png)

**Comment by Circeus** [comment]
I don't use the beta post editor because it means losing my tag history and thus the tag autocomplete feature. Or at least it did the last time I tried.

**Comment by marcustyphoon** [comment]
I believe tag history in the beta post editor was improved at one point, but I don't recall if the issues people had about it were completely solved, as I did not familiarize myself with those issues at the time.
