### ISSUE TITLE
Tag Replacer not showing on site

### ISSUE THREAD

**Issue by makoizu** [AprilSylph/XKit-Rewritten#583]
### Platform

Windows 10

### Browser

Chrome 100.0.4896.127

### Addon version

0.19.3

### Details

when enabling tag replacer, when i go to a specific blog page, there isnt an option to replace tags anywhere in my sidebar, when i enable it it just makes the tumblr radar show back up for some reason

**Comment by marcustyphoon** [comment]
Do you have Tumblr Savior installed?

**Comment by AprilSylph** [comment]
That's exactly what will happen if you use Tumblr Savior's default options to hide recommended blogs and the radar. The options in XKit Rewritten's No Recommended actually do what they describe instead of simply hiding the first and second children in the sidebar.

**Comment by makoizu** [comment]
i disabled tumblr savior and it still doesnt show up

**Comment by makoizu** [comment]
> That's exactly what will happen if you use Tumblr Savior's default options to hide recommended blogs and the radar. The options in XKit Rewritten's No Recommended actually do what they describe instead of simply hiding the first and second children in the sidebar.

i disabled tumblr savior and it still doesnt work

**Comment by marcustyphoon** [comment]
Does this occur if you disable every browser extension besides XKit Rewritten in `chrome://extensions/` and refresh the page?
