### ISSUE TITLE
Quick Tags/Quick Reblog: Tag length validation

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#584]
### Concept

The quick tags text box could provide a visual warning when its contents would result in a tag being longer than Tumblr's 140-character tag limit and thus getting truncated. I run into this a fair amount!

**Comment by AprilSylph** [comment]
I wonder if it would be possible to set up a regex for this and slap it on the text inputs as a `pattern` attribute. I think it should be simple to test for 140 consecutive non-comma characters; question is if we can reverse that and fail the input when it does match that pattern.

**Comment by marcustyphoon** [comment]
Seems like a fun puzzle solving problem, but I'm not sure if there's a way to do it that would be comprehensible enough for me to feel good committing it :D

`^(?!.*[^,]{141,}$).*$` might work, though it doesn't account for whitespace trimming.

**Comment by AprilSylph** [comment]
Regex has an incomprehensibility floor that rises with the complexity of what you're trying to do. I say commit what works anyway. If it's *really* bad, add a comment on it that describes **exactly** what it does.

Using comments as a substitute for writing readable code is lazy, but when the code is difficult to read due to the nature of its syntax - when the code can't be made more readable - comments are helpful, though only so long as they are perfectly accurate.

**Comment by marcustyphoon** [comment]
`^(?!.*[^,]{141,}).*` Oh, this isn't too bad and probably(?) works. Still no whitespace handling, though - can't figure out a way to do that. I guess cutting it down to `139` and assuming up to two spaces after a comma sort of works.

Anyway, yeah, I would be fine using generally-incomprehensible code if *I* could comprehend it. In this case, though, I think I will be neither confident in the correctness of the functionality nor confident in my ability to troubleshoot or fix problems that might stem from edge cases in the implementation.

**Comment by AprilSylph** [comment]
It looks like you could simplify it down to `^(?!.*[^,]{141})`. Assert that the start of the string is not followed by zero or more characters followed by 141 consecutive non-comma characters.

I don't think I would have thought of combining the `^` boundary match with a negative lookahead for simple inversion - very nice!

Also, I'd say it's fine to ignore the `.trim()` inaccuracy.

**Comment by marcustyphoon** [comment]
Looks like the `pattern` attribute has to match the input string, so `^(?!.*[^,]{141}).*` works!

One thing I didn't realize is that - apparently - there's no default style change on `input:invalid`. The `setCustomValidity()` method doesn't really care about this much, since it creates an informative message when invalid input is entered, but a pure `pattern` method does if we want real-time feedback before the user attempts to submit the form.

I'm not sure what styling would work well here. (I was hoping you could use a pseudo element in an `input` similar to Material UI's "adornment" element, but it looks like you can't.) A red border or red coloration kind of works?

**Comment by marcustyphoon** [comment]
Note to self: you have to implement this for both quick tags and quick reblog, silly.
