### ISSUE TITLE
[Feature Request] Add option to hide non-mutuals in Mutual Checker

### ISSUE THREAD

**Issue by salazarbarrera** [AprilSylph/XKit-Rewritten#588]
### Concept

What the title says, allow to hide non-mutuals in dashboard, similar to how Show Originals allows to hide posts without original content.

**Comment by marcustyphoon** [comment]
Suggest this to Tumblr Staff as well! They've been working on new filtered dashboards like https://www.tumblr.com/timeline/crushes and https://www.tumblr.com/timeline/blog_subscriptions; I bet a "mutuals" dashboard would make a lot of sense along with those.

**Comment by salazarbarrera** [comment]
Great idea! Also, I didn't know it was possible to access to those on web. I saw the Labs experiments in the app, but nothing on browser.

**Comment by marcustyphoon** [comment]
Yeah, they certainly feel a bit unfinished :D They've been hanging out semi-secretly for a while, but I think they might get an actual release with a proper UI soon!

**Comment by salazarbarrera** [comment]
I just realized one single bug after two days using my patch: the browser scrolls to the top when 'k' is pressed. I know `show_originals` already solved this, but since this is the first time code a web extension, I'm not sure how. Does it have anything to do with that `getLocation()` function? I've been reading the [commit history](https://github.com/AprilSylph/XKit-Rewritten/commits/master/src/scripts/show_originals.js) of that script, but I can't find anything about that specific problem.

**Comment by marcustyphoon** [comment]
This happens when you set `display:none` on a post directly, and it's the one Tumblr's code tries to scroll to when you press K. We hide the `article` element to avoid this!

(I don't know if April thinks this feature is a good idea for the script or not and was waiting for her comment, but I could review your code's implementation details!)

**Comment by salazarbarrera** [comment]
Thanks! It was way easier than I thought and was overly complicating things. And in any case, even if it isn't accepted, it has been an entertaining thing to do. It has been a long time since I coded anything just for fun.
