### ISSUE TITLE
feature request (from new xkit) - hide liked posts

### ISSUE THREAD

**Issue by komaedalove** [AprilSylph/XKit-Rewritten#594]
### Concept

I saw it's not in the xkit rewritten removed/wont implement list and it's broken in new xkit

the extension would hide posts that are already "liked"

**Comment by marcustyphoon** [comment]
Question: Would you like this feature to hide a post immediately if you press the like button, or to only hide posts as they load if they have previously been liked (similar to the way Seen Posts marks posts you have already seen previously, but of course does not mark posts in real time as they come into view)?

My gut feeling is that the second behavior is better, as it prevents the "I accidentally liked a post and now it's gone" phenomenon.

**Comment by komaedalove** [comment]
yes, only hide after posts loaded, not immediately! so for example if i go to the "cats" hashtag, it hides all the posts i liked previously, but the posts i liked right now still stay :)

thank you!
