### ISSUE TITLE
hide Tumblr's pop-in labels for control buttons

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#595]
### Discussed in https://github.com/AprilSylph/XKit-Rewritten/discussions/575

<div type='discussions-op-text'>

<sup>Originally posted by **faefangirl** April 25, 2022</sup>
I would like to see a feature that turns off the hover animation/text when you hover over the Like button. The hover delay often causes my likes to not register and I have to like again or wait for the animation. </div>

**Comment by marcustyphoon** [comment]
My guess is that XKit Rewritten hiding these would not fix the "clicks not registering" problem (if I had to guess, there's a performance issue with Tumblr's code). That doesn't mean this isn't worth doing, of course.

**Comment by AprilSylph** [comment]
They're annoying for sure. I often go to like a post only for the label to get in the way, requiring me to click slightly further down into the button.
