### ISSUE TITLE
Anti-Capitalism hides asks in the inbox

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#602]
Looks like `videoCTA` is no longer in Tumblr's CSS map, somehow causing Anti-Capitalism to go a little haywire here:

https://github.com/AprilSylph/XKit-Rewritten/blob/1695fbe056dee86a92f1c6397e5c3135e7478a5e/src/scripts/anti_capitalism.js#L63

I wonder what `keyToCss('videoCTA')` is being evaluated to. We really should have better protections in place for CSS map key removal.

**Comment by marcustyphoon** [comment]
Oh my god. Asks' postAttribution elements actually have the css class `undefined`. Legendary.

**Comment by marcustyphoon** [comment]
I'll run anti-capitalism with show all ads on to see if a video ad pops up. I guess there's no need to specifically remove this code once the fix is implemented.

**Comment by AprilSylph** [comment]
I don't think Tumblr is running any takeovers right now, so... the code might work again when they run their next one? Or it won't, but might be similar enough to be easily adapted. I guess we'll have to see.
