### ISSUE TITLE
show originals working even when disabled?

### ISSUE THREAD

**Issue by sickbvbblegum** [AprilSylph/XKit-Rewritten#604]
### Platform

macOS 12

### Browser

chrome version 101

### Addon version

 v0.19.4

### Details

two nights ago i opened the control panel and saw Show Originals had been enabled. i disabled it and since then it has stayed disabled, but still my tumblr dash only shows original posts. i've restarted my browser a few times now and went through every option to see if i somehow had an interference but i've found nothing.

**Comment by marcustyphoon** [comment]
Weird. Can you log in on another browser that doesn't have XKit Rewritten installed and confirm that there are posts which appear on your dashboard in that scenario that don't appear in your main browser? Do you have "best stuff first" enabled in <https://www.tumblr.com/settings/dashboard>, which perhaps might be rearranging your posts in a way that makes it seem like Show Originals is enabled? Do you have any other browser extensions like Tumblr Savior?

**Comment by sickbvbblegum** [comment]
@marcustyphoon i've checked on my tumblr mobile app multiple times and my dash is fine on there, but only on web does it do this. the only extensions i have that interact with tumblr are new xkit, tumblr savior, and xkit rewritten but i've gone through the options and features for all three of those and found nothing that should be causing this? when i turn xkit rewritten off, however, my dash is fine so i'm assuming it has to be something from that specific extension

**Comment by marcustyphoon** [comment]
Sounds like you were pretty thorough. Hm.

- Are you actually observing the same posts but with all of the reblog credit removed? Tumblr Savior does this unless you disable that option, for... some reason. You said disabling XKit Rewritten fixes it, so I assume it's not this.
- Does disabling every XKit Rewritten script, but leaving the extension itself enabled, fix the problem? (You can back up your settings in the backup tab before doing this if you'd like). If so, which script causes the problem to occur when you enable it?
- Does disabling every extension *except* XKit Rewritten fix it, in the same way that *only* disabling XKit Rewritten does? That would imply that this is an interaction between the extensions.

**Comment by sickbvbblegum** [comment]
@marcustyphoon its definitely only showing me original posts, not reblogged posts w/o credit. so i tried the second option of disabling each script while leaving the extension enabled and added them back one at a time and by processes of elimination and trial and error figured out that it was the anti-capitalism function? when i turn it off, the posts show up as normal, and when i turn it on its only original posts and no reblogs again. i have no idea why the script did this since these posts arent ads in any way, just regular reblogged posts?

**Comment by marcustyphoon** [comment]
Oh neat! I wonder if this is another result of the problem described in #602. I'm not seeing it happening on my end but if there's some experimental Tumblr code running around that I don't have on my account that uses the word `undefined` in a component that's part of reblogs then that could definitely happen.

If it is, this should - hopefully - be resolved in the next release.

**Comment by sickbvbblegum** [comment]
@marcustyphoon thank you for all your help!!

**Comment by marcustyphoon** [comment]
@sickbvbblegum Once you receive v0.19.5, you should be able to re-enable Anti-Capitalism and see if this is fixed!
