### ISSUE TITLE
No Recommended: Split recommended blogs sidebar preference

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#605]
### Concept

I kind of like having the recommended related blogs in the blog view sidebar, but not having the generic recommended blogs in the dashboard sidebar. No Recommended could have separate options for these (and they can inherit their states from the current single preference.)

**Comment by char-lock** [comment]
Is your ideal to see the split as just two options, or were you thinking to leave the single option and add two additional ones that are both able to be set to false or true via the single one, depending on user desire?

Judging from the current setup of script preferences, there isn't such a thing as "sub-preferences", although I imagine *that* would be the ideal -- displaying the two options if the single option is selected on, and hiding them if it is off.
