### ISSUE TITLE
Asks not appearing when the extension is enabled

### ISSUE THREAD

**Issue by universefactorie** [AprilSylph/XKit-Rewritten#606]
### Platform

Windows 10 Pro

### Browser

Chrome 101.0.4951.67 (Official Build) (64-bit)

### Addon version

0.19.4

### Details

![image](https://user-images.githubusercontent.com/95934310/169264551-51fc6d66-860a-4b9e-82d1-3592a23d9163.png)

This just started happening yesterday. I tried disabling XKit, and when I did the asks started appearing again. It doesn't seem to be an issue with tumblr itself as I had reached out to staff and still got similar results. Also tried updating the extension to no avail. Hope this can be fixed as I find using tumblr unbearable without the extension, haha. Thank you so much for all the work you put into this!

**Comment by marcustyphoon** [comment]
Temporarily disable anti-capitalism until the next version update! (See: #602, though it's closed already so I don't blame you for not seeing it :D)

**Comment by universefactorie** [comment]
Thank you very much! <3
