### ISSUE TITLE
Inbox not loading when enabled

### ISSUE THREAD

**Issue by Bengesko** [AprilSylph/XKit-Rewritten#607]
### Platform

Windows 10

### Browser

Firefox 100.0 (64-bit)

### Addon version

0.19.4

### Details

When Xkit is enabled, the inbox shows for a split second, then reverts to an infinite loading screen. When disabled, inbox works as intended. Checked for updates, refreshed, cleared cache, re-enabled Xkit, and the issue returned.

**Comment by hx41455** [comment]
Seems to be anti-capitalism specifically. Inbox loads when this is turned off.

**Comment by Bengesko** [comment]
Ah, yeah looks like it. Thanks so much, I'll turn that off for now!

**Comment by AprilSylph** [comment]
This is the third duplicate of #602 this week, but to be fair it's hard to give visibility to closed issues.

Keeping open until this week's release.

**Comment by AprilSylph** [comment]
This is now fixed in **v0.19.5**, which you should receive soon.
