### ISSUE TITLE
Anti WebP/GifV

### ISSUE THREAD

**Issue by bitchcakes** [AprilSylph/XKit-Rewritten#608]
### Concept

hello,

i am sure i'm not alone when i say that encountering a webp or a gifv makes me want to sit in the dishwasher and turn it to maximum hot so here is my concept

tumblr does not delete source files when converting them to webp/gifv as far as i've seen. so those lovely gifs and pngs are still there under the same name on the server just with a different extension. my suggestion is to just search for those images in the page and then replace them on the dash or blog viewer with their god-given filetypes so that one may simply right click and save.

if i still remembered any amount of regex i would give you one for this but i try to keep evil magic rock spells out of my head (for my own sanity)

thank you for your consideration xoxo

**Comment by komaedalove** [comment]
hii its a temp solution but theres an extension for firefox "dont accept image/webp"  and "GifsOnTumblr" u could try them out in the meantime if this isn't implemented into xkit
