### ISSUE TITLE
Disable Gifs fails on gifs with transparent backgrounds

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#617]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 101.0.1210.53

### Addon version

master

### Details

It... almost seems implausible to me that this has always been true and no one reported it, but I can't really think of how any recent (or even non-recent!) change could have produced it. I mean, not almost. It seems very implausible.

Anyway, a gif with a transparent background results in a disable gifs canvas element with a transparent background, through which one can see the animated gif element.

Ex: <https://www.tumblr.com/blog/view/wrender/675764854081093632>

**Comment by AprilSylph** [comment]
Should be pretty easy to just add `background-color: rgb(var(--white));` to the canvas elements?
