### ISSUE TITLE
Scroll to Bottom stays stuck "on" between pages

### ISSUE THREAD

**Issue by lihatt** [AprilSylph/XKit-Rewritten#619]
### Platform

Windows 10

### Browser

Firefox 100.0.2 (64 bit)

### Addon version

v0.19.4

### Details

When I hit the Scroll to Bottom arrow, it turns yellow and does its thing. Cool. But then if I change pages, say going from my queue to my drafts, the arrow is still yellow upon page load and immediately scrolls the page down to the bottom without me interacting with it. I can work around this by remembering to click the arrow again before changing pages, but I feel like this script didn't used to behave like a cross-page toggle, and would always begin in the "off" state when a page where it could apply was loaded. (I don't remember for sure when I updated from 0.19.3 to 0.19.4, although it was within the past 10 days most likely. Unfortunately I think I also applied a Firefox update within the same timeframe, so that possibly muddies the waters.)

I noticed also that at first (meaning right after one or the other update) the down arrow was duplicated on the pages where it appears. That was fixed by turning off the toggle for the script and then turning it on again (I haven't seen it since).

**Comment by marcustyphoon** [comment]
Hmm, I think I remember the feature turning itself off successfully on navigation before, so I think you're right. Based on our current code (which turns off the feature if the button that we add is removed from the page), my guess is that a slight change to Tumblr's code results in the button no longer being removed, and so we need a different way to detect this.

**Comment by lihatt** [comment]
Ah, if Tumblr changed something slightly then it might not be related to either extension or browser update. I just remember seeing it start to happen sometime within the past few days on two different computers (but both Win/Firefox of similar versions).

**Comment by AprilSylph** [comment]
It looks like the main problem here is that scrolling doesn't stop when there are no more posts on the page. I just experienced this after loading my whole queue, then going to a different page. When all posts are loaded, scrolling should stop.

https://github.com/AprilSylph/XKit-Rewritten/blob/e764557adf7d1f8212ecec8141bb74129f97d8b9/src/scripts/scroll_to_bottom.js#L23-L25
