### ISSUE TITLE
AccessKit Visible Alt text: Hide Tumblr's alt labels...?

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#620]
### Concept

With the visible alt text feature enabled, the new Tumblr `alt` labels seem kind of redundant.

Then again, maybe this is confusing.

(I'm sure people will want a toggle for the `alt` labels in Tweaks, but I assume this makes more sense to discuss later only if Staff does not implement said toggle as part of the rollout.)

**Comment by marcustyphoon** [comment]
![image](https://user-images.githubusercontent.com/8336245/170582374-d7141034-0d6e-41a5-9560-6fdf659f669a.png)

Looks like if we don't do this we'll also have to tweak the positioning of the label.

**Comment by AprilSylph** [comment]
```diff
- "Show alt text as captions below images"
+ "Move alt text to captions below images"
```
