### ISSUE TITLE
AccessKit: Visible Alt Text can become unreadable with Themed Posts

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#626]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 101.0.1210.53

### Addon version

v0.20.0

### Details

<img width="603" src="https://user-images.githubusercontent.com/8336245/172023852-0950d79b-298f-40b8-b2f1-0cfa3f7928a9.png">

We need to reset the text color for the visible alt text element (and possibly others?)

**Comment by marcustyphoon** [comment]
I had a Firefox (103.0b9) tab in which this fix was not doing anything, but the `rgba(var(--black),.07);` background color value showed up in dev tools, and would work once the checkbox next to it was toggled off and on.

Not sure if this was a firefox bug... triggered by a race condition in which accesskit went first and so that css was set before themed posts changed the variable, or something? Anyway, haven't gotten it to happen again, so maybe it was nothing.

**Comment by AprilSylph** [comment]
CSS variables are supposed to account for changes on the fly, so if it is a Firefox bug, it'll be a little more complex than that. Definitely sounds like a browser bug or glitch than anything else, though.
