### ISSUE TITLE
NotificationBlock can't be used on Blazed posts

### ISSUE THREAD

**Issue by tylclem** [AprilSylph/XKit-Rewritten#627]
### Platform

macOS Big Sur 11.6.5

### Browser

Firefox

### Addon version

v0.19.6

### Details

I can't block notifications. When I press the meatball thing, I only see [this](https://64.media.tumblr.com/2898e3f0b959eed44c63f86b31d2a0d4/690cc01f5c73a6db-75/s540x810/903236bca8b0a7b2bcbf917220de3ac9d3bb2f33.png). I've for sure got it turned on as you can see [here](https://64.media.tumblr.com/a64d0fb739951858978092c62af0f802/690cc01f5c73a6db-db/s1280x1920/714095fe5509fad2a6a57f1a3b4f0dc192ec64e6.png) but it's still giving me notifications for this post in my activity tabs. Thank you please help.

**Comment by marcustyphoon** [comment]
Hm, that's not a good sign. Thanks for the report! Neither of my accounts seem to have this problem yet (still trying some things) but maybe it's a change in Tumblr's code that I have't received yet. Unfortunately, the code in question is pretty complicated.

**Comment by marcustyphoon** [comment]
...wait, that is your own post, right? It has no edit button or delete button. Is it a post from a group blog you have edit access to, but that you did not create?

**Comment by tylclem** [comment]
It's my own post on a solo blog, [here](https://64.media.tumblr.com/627ec6ba30f5af086cf91d50da002921/690cc01f5c73a6db-e0/s1280x1920/bfe32b07884ce17ac4f6f3d8b9bd04249f3f0ec2.png)'s the bottom of it.

**Comment by tylclem** [comment]
Oh this is interesting, it's working on reblogged and other original posts.

**Comment by AprilSylph** [comment]
NotificationBlock currently uses a very simple check for if you can edit the post to determine if you own it, but with actively-Blazed posts taking the ability to edit the post away, it's not a reliable indicator anymore.

We'll need to modify how we determine post ownership with this in mind, and then apply it to NotificationBlock. In the meantime, you should be able to use NotificationBlock on posts *before* you Blaze them, though you also wouldn't be able to unblock notifications until the campaign is over.

**Comment by marcustyphoon** [comment]
...wait, it doesn't? Oh wow, can't believe I missed that! Will do!

**Comment by marcustyphoon** [comment]
...oh hold on. Do you receive notifications for notes on a different set of posts than the set which we are defining as yours?

**Comment by AprilSylph** [comment]
I *think* it's possible to see the activity page for a blog you're not admin of, which would mean yes, but I'm considering that an edge-case. Using `isMyPost` is still an expansion of NotificationBlockable posts compared to the `canEdit` check.

**Comment by AprilSylph** [comment]
Something that would solve the can't-block-all-notifications issue entirely and improve the UX overall is to also add buttons to notifications themselves (reusing Quote Replies' code), but that's obviously going to be more complex than just modifying a couple of conditions.

**Comment by marcustyphoon** [comment]
> I think it's possible to see the activity page for a blog you're not admin of

Looks like it is. It seems somewhat confusing to me if there are edge cases with missing controls where they would make sense, but it wouldn't be hard to fix this? I'll demo what I'm thinking in a PR.
