### ISSUE TITLE
Themed Posts: Script overrides pinned post text color

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#628]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 101.0.1210.53

### Addon version

v0.20.0

### Details

<img width="600" src="https://user-images.githubusercontent.com/8336245/172024255-e69298ef-f55c-4e39-9589-879c15967217.png">

The "pinned post" text here probably shouldn't be themed, which might require some css specificity trickery? Probably applies to recommended post labels as well.

**Comment by AprilSylph** [comment]
Not a bug, I introduced this on purpose in 751614f8e6e7668dcaa21b9122c01e1bac561f1f.

**Comment by marcustyphoon** [comment]
Oh! Neat, gotcha.
