### ISSUE TITLE
NotificationBlock stops working when changing tabs in the activity dropdown

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#635]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 102.0.1245.39

### Addon version

f318547

### Details

When I switch from the "all" tab to the "mentions" tab and back in the activity dropdown, the notifications that are hidden with notificationblock reappear.

**Comment by AprilSylph** [comment]
This is actually a Tumblr bug; same React key thing we had to deal with with posts ages ago. I've noticed myself that switching tabs highlights the wrong notes as mutuals too.

**Comment by AprilSylph** [comment]
Fixed on Tumblr's side!
