### ISSUE TITLE
Mass Deleter non-working on Chrome

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#640]
> Lynn Lyon gave you **3 stars** and said:
_"I can't get the Mass Deleter function to work. I would like to clear out all my drafts, but I am unable to. The "next" button refuses to do any input. Otherwise it's a pretty neat extension."_

**Comment by marcustyphoon** [comment]
Confirmed; the input elements's `valueAsDate` attribute is `null` in my Edge 102.0.1245.41.

**Comment by AprilSylph** [comment]
Ah, great.

**Comment by AprilSylph** [comment]
Weird, `valueAsDate` is listed as having full support beginning in Chrome 5 on MDN... Did they just recently drop it?

**Comment by marcustyphoon** [comment]
Wow, the documentation for `datetime-local` throughout the web is terrible. Assuming we're looking at the same MDN page (generic one for every type of HTMLInputElement) I get the impression that this never worked in Chrome, and it's just so ill-defined that there's no concrete answer to whether it's supposed to? No idea though.

Unless you did test this functionality in Chrome before and it worked, of course. (Evidently I should have, but the idea of deleting drafts is so foreign to me that I didn't even register that it existed :P)
