### ISSUE TITLE
Tweaks "Use a slim layout for post footers" does nothing except move the Blaze button slightly to the right

### ISSUE THREAD

**Issue by exoglot** [AprilSylph/XKit-Rewritten#642]
### Platform

Windows 10

### Browser

Firefox 101.0.1 (64-bit)

### Addon version

v0.20.1 Beta

### Details

Toggling the "Use a slim layout for post footers" checkbox doesn't change post footers' appearance at all, except for, for my own original posts, to shift the "Blaze" button over a bit to the right.

Disabled:
![image](https://user-images.githubusercontent.com/73374565/175308766-691e5ffd-8bb9-49a6-a1d1-2c6b282352b0.png)

Enabled:
![image](https://user-images.githubusercontent.com/73374565/175308899-00fa356d-8cca-4124-9b3b-fd4572f3cc67.png)

Sorry if you're already aware of this, and thank you for taking a look! I really appreciate the existence of XKit and all the work put into it.

**Comment by AprilSylph** [comment]
That footer design is currently in a testing state. If it becomes final and the other design is removed (the one with the spaced control icons) this tweak will be removed altogether. If it doesn't, this won't happen anymore.
