### ISSUE TITLE
"You're caught up" is no longer an accurate descriptor

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#643]
### Platform

MacOS 10.14.6 x86

### Browser

Edge

### Addon version

v0.20.1

### Details

We still refer to the "You're caught up" element as such in the description of its hiding checkbox in Tweaks, but it no longer has that text, so new users won't know what the option refers to!

What should it be called, that would be clear and obvious? I have absolutely no idea. It's, you know, super great.

**Comment by AprilSylph** [comment]
The changes blog has been referring to it as that since after it was changed, so I'm opting to leave as-is until we see a new official name for it.

**Comment by citrusella** [comment]
For what it's worth, I was advised to use Rewritten to hide those once New XKit's Anti-Capitalism stopped doing it, and even though I knew what the caught up feature was, I had not made the connection that those were that--I think that situation triggered the creation of this issue. (Of course, once I was told, I was like "oh! of course!" ~~and it was like I had all the knowledge of the universe at my fingertips~~ but before then...)

On the other hand, I don't know that there's a good way to communicate that those are the same while still calling it the official name, even if it was, say, some sort of addendum on the features wiki page and not a change to the Tweaks preference text.

**Comment by AprilSylph** [comment]
It seems the most accurate term is now simply "the dashboard carousel".

**Comment by marcustyphoon** [comment]
That is... certainly... a term that describes it, I suppose, yes.
