### ISSUE TITLE
Tweaks: Hide Dashboard Tab Bar

### ISSUE THREAD

**Issue by fleurite** [AprilSylph/XKit-Rewritten#645]
### Concept

It appears [Tumblr's dashboard carousel test](https://changes.tumblr.com/post/687327480683593728/friday-june-17th-2022) has been extended to my account, or this is something new entirely. I'm not a fan of it, and unfortunately I can't use uBlock Origin to block the elements responsible as I typically do with unwanted website clutter. When I did try blocking it, the tab menu disappeared but the dashboard behaved no differently with avatars still displaced about 20px down when the top of a post is at the top of the dash. 

![Screenshot 2022-06-28 105529](https://user-images.githubusercontent.com/95893576/176250357-6fbb0798-d5ac-4f95-aea5-561858915220.png)

The **Manage...** link leads to Tumblr Labs which only lists Inside Tumblrs, Queue 2.0, Reblog Graphs, Fast Queue, and Tumblr to Discord Webhooks. I was unable to find any relevant settings in the Account and Dashboard pages either.

I am a simple blogger. I follow blogs so their content appears on my dash. If I want something else, I can search for it or click on the Explore link that's been around for years. And I imagine others use Tumblr similarly. It would be lovely if the Tweaks app contained a function to 1) hide the tabs and 2) prevent the displacement of avatars. (I will be sending in a support ticket to Tumblr as well. ✌🏻)

EDIT: This subheader deal is also cramping the style of post headers when I use J+K to navigate. It does this even when I disable Mutual Checker and Timestamps.

![Screenshot 2022-06-28 120620](https://user-images.githubusercontent.com/95893576/176263279-3d2c415f-2130-43c2-8c29-19d8ddedc443.png)

ADDTNL EDIT: The Changes blog just published [the Tuesday update](https://changes.tumblr.com/post/688332652095356929/tuesday-june-28th-2022#notes) which puts a name to this feature.

**Comment by fleurite** [comment]
> The **Manage...** link leads to Tumblr Labs which only lists Inside Tumblrs, Queue 2.0, Reblog Graphs, Fast Queue, and Tumblr to Discord Webhooks. I was unable to find any relevant settings in the Account and Dashboard pages either.

I can view the settings in Tumblr Labs now, but it's just to add more tabs. 😖

**Comment by stacybrock** [comment]
@fleurite I was able to block the new dashboard tab bar in uBlock Origin using the following custom filter:
```
www.tumblr.com##:xpath(//main/div[4])
```
I've only tested this in Firefox so YMMV. I'm hoping this will be enough to tide me over until this feature request (hopefully) makes it into XKit-Rewritten. Unfortunately, my JavaScript skills aren't good enough to try adding this feature myself.

**Comment by fleurite** [comment]
@stacybrock I appreciate the thought, but that is the same exact uBlock filter I tried as described in the first paragraph. And it still displaces avatars as you scroll. I can't demonstrate the effect entirely without recording my browser somehow, but this screenshot shows how the avatar is misaligned with the top of the post when I haven't completely scrolled past the Post Type bar. 

![Screenshot 2022-06-28 200507](https://user-images.githubusercontent.com/95893576/176342446-0adb9fd1-a853-46fd-a7c3-d5ce9d4ffc4d.png)

**Comment by piotrmil** [comment]
Yewah, please fix this it is extremely annoying how tumblr thijks I would like what they want for me

**Comment by fleurite** [comment]
It looks like Tumblr updated the dash again and now everything behaves well!

**Comment by piotrmil** [comment]
Now there is another cringeworthy ad for their shop..
![Schowek01](https://user-images.githubusercontent.com/1182094/177606305-7d652368-7a96-4d59-bf15-aeb67933b6df.jpg)
.

**Comment by marcustyphoon** [comment]
Not relevant to this thread.
