### ISSUE TITLE
New intrusive Stranger Things advertising campaign (Anti-Capitalism?)

### ISSUE THREAD

**Issue by luxidoptera** [AprilSylph/XKit-Rewritten#647]
### Concept

This isn't really an enhancement but isn't really a bug either, so I'm putting it under here. Quick alert that a new Stranger Things-themed advertising campaign has popped up on the front page of Tumblr, and alongside the usual video ad it also has a new, extra-intrusive element in the form of a grandfather clock on the left side of the dashboard; this follows your scrolling and flips your dashboard when clicked. While admittedly cute, it is something that should probably be blocked regardless due to its intrusivity.

![image](https://user-images.githubusercontent.com/15697751/176631375-8d11e634-96b8-49d1-b0ad-25261d2df7ff.png)
![image](https://user-images.githubusercontent.com/15697751/176631485-5e19d762-e0f7-4417-a938-301997a1b768.png)

**Comment by AprilSylph** [comment]
These types of advertising campaigns are by nature temporary. It cannot be blocked pre-emptively and will likely be over by the next XKit release.
