### ISSUE TITLE
Add tweak to make one own's avatar always visible in the Reblog view

### ISSUE THREAD

**Issue by salazarbarrera** [AprilSylph/XKit-Rewritten#659]
### Concept

**Summary**

Add a tweak to make the destination blog's avatar always visible in the new post editor. 

---
**Reasoning and proposal**

When one scrolls through the dash, the avatar of the currently focused blog is always visible, since it moves down along with the screen.
![imagen](https://user-images.githubusercontent.com/68821455/178337080-fbf5bba6-468e-49b0-acf4-21cc46645ad0.png)

This behaviour is not present in the post editor, which is unfortunate because when one hits the reblog button, the browser automatically scrolls down to where the caret in the editor is.
![imagen](https://user-images.githubusercontent.com/68821455/178337199-92e9e242-c9bf-49eb-bce5-493f1d279465.png)

My tweak proposal is to make the avatar always present on said screen, so one can immediately know which one of the side or primary blogs is being selected as destination without scrolling to the top every time.
![imagen](https://user-images.githubusercontent.com/68821455/178338048-f5deb9b4-24fa-4f8e-bd52-1175ee6e3f87.png)

I've been injecting for some time this custom CSS to enable said behaviour in the Beta post editor, but I'm not sure if the selectors used follow X-Kit Rewritten's logic.

```
 /* Absolute positioning the div above the "controlled-popover-wrapper",
    making it independent from the rest of the document flow  */

#glass-container .l8blt .dzJuF .rN5a6 {
  position: absolute;
  margin-right: 77px;
}

/* Positioning the avatar (aria-label="avatar" role="figure") to the right.
To be honest, this is a leftover from a previous try, I'm almost sure this
block could be replaced just by a "position: relative;" or even deleted */

#glass-container .l8blt .dzJuF .rN5a6 .nZ9l5 {
  position: absolute;
  right: 0;
}

/* Making the avatar wrapper fixed */

#glass-container .l8blt .dzJuF .rN5a6 .nZ9l5 .BPf9u {
  position: fixed;
}

/* This was based on this concept: https://stackoverflow.com/a/3303944 */
``` 

 I could do something similar for the legacy post editor, but I was not sure if X-Kit Rewritten could include tweaks for the interface from the pre-React era. Also, I didn't know if the tablet/mobile view would benefit from a similar feature (for example, making the top bar of the editor fixed or something). 

What do you think?

**Comment by AprilSylph** [comment]
I think this is a good idea, and one that might even see implementation in Tumblr proper. I encourage you to submit a feature request to Tumblr support for this!

As for this CSS, you're right, it doesn't follow XKit Rewritten logic at all. Instead of referencing the generated classnames (which are subject to change) we target the source names, and let our utilities tap into Tumblr's CSS map to translate them. If you'd like to try your hand at writing it yourself, the docs in this repo and the existing options in Tweaks are a good way to learn up.

I use this snippet in the browser console to reveal Tumblr's source names in the DOM inspector:
```js
tumblr.getCssMap().then(cssMap => {
    const keys = Object.keys(cssMap);
    const elements = document.querySelectorAll("[class]");
    for (const { classList } of elements) {
        for (const className of classList) {
            const mappedClassName = keys.find(key => cssMap[key].includes(className));
            if (mappedClassName) classList.add(`tumblr--${mappedClassName}`);
        }
    }
});
```

XKit Rewritten does not target non-React pages. The legacy editor is planned for deprecation anyway.

**Comment by salazarbarrera** [comment]
I finally got the time to try this and I was surprised, I didn't know Tumblr had this getCssMap function implemented. Where do you think this should be added? To Tweaks? Or as a separate script?

**Comment by AprilSylph** [comment]
I think it would belong in Tweaks.

**Comment by salazarbarrera** [comment]
In the whole month I couldn't find time to do this, but since Tumblr seems to have impleted this themselves, probably this should be closed.

**Comment by AprilSylph** [comment]
You can close your own issues! But yes, I implemented it on the Tumblr side so it doesn't need to go in XKit.
