### ISSUE TITLE
Scripts stuck offscreen at bottom of control panel

### ISSUE THREAD

**Issue by umbralOptimatum** [AprilSylph/XKit-Rewritten#660]
### Platform

OS X 10.14.6

### Browser

Firefox 102

### Addon version

v0.20.3

### Details

The bottom couple of scripts on the control panel are stuck offscreen for me. I'm able to see them if I scroll down farther but Firefox does the bounce-back-up thing like any other time you scroll down farther than the end of a page. This persists after restarting the browser. I've been messing about with Arkenfox, so that could be related but no clue what privacy settings would affect a scroll bar...

<img width="398" alt="Screen Shot 2022-07-14 at 10 26 01 PM" src="https://user-images.githubusercontent.com/12092270/179135136-05033fb3-2e46-454a-9238-2f16c4a0d1af.png">

This screenshot is taken at the farthest down it'll stay. I have vanilla audio and video enabled so I'm pretty sure Tweaks is the only one offscreen.

**Comment by marcustyphoon** [comment]
See #183! Does this still occur if you "pin" xkit rewritten to the menu bar, then click it?

**Comment by marcustyphoon** [comment]
I think it would be possible to implement a workaround for this, just by unconditionally adding a blank space at the bottom of the extension menu, though it wouldn't look great of course. Not sure if that's something April is interested in.

**Comment by AprilSylph** [comment]
Yeah, I'd prefer not to. Note also that it's still possible to access the settings for any feature by filtering to it, or by accessing the settings from `about:addons`.
