### ISSUE TITLE
Vanilla Video breaks GIFS served as MP4

### ISSUE THREAD

**Issue by EIworsley** [AprilSylph/XKit-Rewritten#662]
### Platform

MacOs Monteray

### Browser

Firefox 102

### Addon version

0.20.3

### Details

As of [this update](https://changes.tumblr.com/post/689599079880228864/tuesday-july-12th-2022), if you have Vanilla Videos enabled, when Tumblr tries serving a GIF as an MP4 it appears as a broken/empty video

**Comment by AprilSylph** [comment]
This was fixed in 0f624931973ca7492b1723dcf07962a647395818, which will be released with v0.20.4.
