### ISSUE TITLE
AccessKit: pause GIFs using Tumblr's poster elements

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#664]
GIF posters are out to everyone now, so if GIFs as MP4 have the same poster structure, the whole option could be changed to take advantage of them and implement this in the process.

Otherwise, they will need to be specifically dealt with.

**Comment by marcustyphoon** [comment]
Looks like they do, I believe! This should be fairly easy. (Not assigning myself until I actually start looking at this.)

**Comment by AprilSylph** [comment]
The GIFs-served-as-MP4 experiment is on hold for now.
