### ISSUE TITLE
XKit Rewritten and Endless Scrolling

### ISSUE THREAD

**Issue by NamelessRumia** [AprilSylph/XKit-Rewritten#668]
### Platform

Windows 10

### Browser

Firefox 102.0.1 (64-bit)

### Addon version

v0.20.4

### Details

Endless Scrolling on Tumblr is usually seamless, but there's something about XKit that makes Endless Scrolling after 12 hours of posts (about 500 posts) difficult, causing both Tumblr and XKit to lag. This issue is especially noticeable when "Hide recommended blogs between posts" under No Recommended is enabled.

**Comment by marcustyphoon** [comment]
Hmmmmm. Interesting. There was a change we made to no recommended's blog carousel hiding that I just confirmed is still working, so apparently that's not it.

**Comment by marcustyphoon** [comment]
Tumblr recently fixed both performance-impacting bugs I knew about that aren't in the ads code. So, especially if you have an ad-free subscription (but even if not; those bugs were fixed in either case), I would be curious to see if you still observe this.
