### ISSUE TITLE
Show Originals: Mode inconsistency in /blog/view using blog UUIDs (extremely minor)

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#676]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 103.0.1264.71

### Addon version

master

### Details

Today I learned that you can navigate directly to /blog/view using a blog UUID, i.e. https://www.tumblr.com/blog/view/t:Fft_7iTGnBlHdl-UtlllwQ.

This causes the timeline's data attribute to be e.g. `data-timeline="/v2/blog/t:Fft_7iTGnBlHdl-UtlllwQ/posts"` and thus breaks this line in Show Originals, leading to an original posts toggle on blogs on which you have the feature disabled that does nothing.

https://github.com/AprilSylph/XKit-Rewritten/blob/4e0e3d932cfda3d68988c3243a8975764b89ee94/src/scripts/show_originals.js#L78

This is minor enough, and annoying enough to fix unless I'm overlooking something, that I probably wouldn't bother? (The behavior is relevant for implementing #674, though.)

**Comment by AprilSylph** [comment]
UUIDs in blog view URLs now get replaced/redirected with blog names.
