### ISSUE TITLE
refactor control buttons CSS

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#687]
Now that the second post footer redesign is out to everyone, the conditional CSS that accounts for it should no longer be conditional.

**Comment by marcustyphoon** [comment]
I think this is a yes, but: this includes making the quick reblog position tweak that fixes this standard, right? Or should this be another issue?

![image](https://user-images.githubusercontent.com/8336245/183157908-e7bdadd3-e692-4aa7-8026-b855aff5f284.png)

**Comment by AprilSylph** [comment]
Yeah, I'm planning on fixing that in the same sweep. Probably gonna do it tomorrow.

**Comment by AprilSylph** [comment]
oops, forgot to put the issue number in my commit.

resolved via 440552d2692cdf7a50b4d7a7473ce57b65fae97c
