### ISSUE TITLE
Recommended blogs and the Tumblr Radar show up in the sidebar even when disabled

### ISSUE THREAD

**Issue by enchanted-sword** [AprilSylph/XKit-Rewritten#694]
### Platform

Win10

### Browser

Firefox Nightly 105.0a1 (64-bit)

### Addon version

0.20.6

### Details

A few days ago, the disabled recommended content started appearing again. At the time, I was using v0.20.5 of XKit, but the problem still persists in v0.20.6. 
![image](https://user-images.githubusercontent.com/81981111/183418890-59fd9c27-c8fc-4cf4-8a37-765281b51ba6.png)
![image](https://user-images.githubusercontent.com/81981111/183418910-f713de92-2926-47ca-acaf-fc59c2b56fed.png)
![image](https://user-images.githubusercontent.com/81981111/183420291-168dec6d-7291-4ec0-9667-6040852268d1.png)
If it's of any help, I fixed the sidebar myself by adding css rules to hide the classes .FZkjV and .f68ED, which is a somewhat crude solution, but it works and doesn't seem to impede upon any other site functions.

**Comment by AprilSylph** [comment]
Unable to reproduce on Firefox 103.0.1 (64-bit) using XKit Rewritten v0.20.6

**Comment by AprilSylph** [comment]
Do any of the options in Tweaks or AccessKit still work for you?

**Comment by enchanted-sword** [comment]
Tweaks and AccessKit seem to work fine
