### ISSUE TITLE
Vanilla Video targets the dashboard carousel

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#695]
![image](https://user-images.githubusercontent.com/28949509/184396467-247aa9cb-8bc7-4b29-ab28-cf577e30f4b3.png)

**Comment by AprilSylph** [comment]
Really, at this point, we should be cloning Tumblr's video elements wholesale and modifying the clones instead of constructing our own and just cloning the source. This type of thing will still be a problem, yes, but it will look far less horrible.

**Comment by marcustyphoon** [comment]
I'm not sure how to do this one. Would changing from `video` to `article video` in the selector work? No, that excludes autoplaying video takeover banners. Maybe ``` `${keyToCss('videoPlayer')} video` ``` or ``` `${keyToCss('videoContainer')} video` ```?
