### ISSUE TITLE
AccessKit option to de-animate the dashboard carousel no longer works

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#696]
The animations are now MP4s instead of background images. This does introduce an opportunity to actually pause the animations instead of making the chiclets plain, though making the option work again is obviously more important.

**Comment by AprilSylph** [comment]
Hmm, looks like it still works on followed tag chiclets, but not the always-there ones. How annoying.

**Comment by marcustyphoon** [comment]
Interesting, doesn't work on my followed tag chiclets. Does work on the carousels in https://www.tumblr.com/timeline/trending, though.

**Comment by AprilSylph** [comment]
Doesn't work on mine either now. Looks like the animation changed? I think it was just a CSS fade-between-colours animation before.
