### ISSUE TITLE
Return viewing blogs on dashboard to a side panel

### ISSUE THREAD

**Issue by k8b0** [AprilSylph/XKit-Rewritten#699]
### Concept

I don't know if this is already a feature that I just can't make work, but it would be nice to have a way to make opening blogs from posts in the dashboard go back to that side panel, instead the middle of the screen where they've made it cover the dash.

**Comment by marcustyphoon** [comment]
It is indeed not currently a feature!

(I'm also not sure how possible it is, but stranger things have happened.)
