### ISSUE TITLE
Tweaks: Unsticky tab bar tweak nonfunctional

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#707]
### Platform

MacOS 10.14.6 x86

### Browser

Firefox 104.0b8

### Addon version

v0.20.7

### Details

The unsticky tab bar tweak is currently nonfunctional because of changes to the redpop DOM.

**Comment by AprilSylph** [comment]
lol someone reverted my PR that fixed its styles by the look of it. i'll have to see why tomorrow

**Comment by marcustyphoon** [comment]
Oh nice :D I just finished the tweak so I'll draft PR it and we can close/merge as appropriate.

**Comment by AprilSylph** [comment]
looks like this is actually a problem with Redpop's deployment, my style changes weren't reverted at all but they're completely missing in production, almost like we're getting served an old commit somehow.

**Comment by AprilSylph** [comment]
NEVERMIND I WAS WRONG someone made a new wrapper element that i didn't notice and reused my old styles while leaving my new, now-unused styles intact. cringe
