### ISSUE TITLE
Quote Replies: Possible failure to open draft post

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#710]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 104.0.1293.54

### Addon version

v0.20.7

### Details

Haven't managed to reproduce it, but I did just encounter a situation where Quote Replies opened its new tab on the drafts page, but the draft it created didn't have the post in question until a refresh.

Not sure if this could be mitigated by either doing a fetch after the post requests that creates the draft to see if it's there yet, or by forcing a page refresh in the drafts tab if the post isn't there yet (and the information stored in local storage indicates that the script has just been activated, and we've only tried this refresh once, and etc).

**Comment by marcustyphoon** [comment]
Just had this happen again, so it wasn't just a one-time glitch!

**Comment by AprilSylph** [comment]
I wonder if fetching the draft directly ever fails... if not, this might be solved just by using `navigate` to open the post form on the current page

**Comment by marcustyphoon** [comment]
Oh yeah: we can make that switch without mitigating this and I can just spam it a bunch and see if I can get it to occur again.

**Comment by marcustyphoon** [comment]
I tried this and it never seems to fail?

This seems silly to me, in a way, since `navigate` pops the post form open seemingly way faster than an entire new tab loads. But I guess it does the http request quite quickly and the server that's doing the SSR for the new tab might not be synced with the back end, I guess?

**Comment by AprilSylph** [comment]
It's probably more that there's a delay between posts existing and being included in their relevant timelines. I'm not sure how that would work using a compute model though (which we know the dashboard uses) - maybe blogs/drafts actually use an inbox model?

**Comment by marcustyphoon** [comment]
Sounds like you know a lot more about this than me, but yeah, makes a lot of sense. God bless `navigate`.
