### ISSUE TITLE
Sidebar utility: (Inconsistent) insertion in /blog/view

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#720]
### Platform

MacOS 10.14.6 x86

### Browser

Edge 104.0.1293.63, Chrome 104.0.5112.101 

### Addon version

v0.20.7

### Details

Sidebar items are inserted into the side of the blog view modal on an inconsistent basis.

This appears to be because the code searches for `sidebarItem` and `navSubHeader`, but not `desktopContainer`. Therefore, sidebar items are only inserted if there's a "more like this" element, and otherwise are not.

At least currently, I do not see the post limit checker on https://www.tumblr.com/blog/view/april or https://www.tumblr.com/blog/view/april/661324787743948800 but do see it on https://www.tumblr.com/blog/view/cyle and https://www.tumblr.com/blog/view/cyle/685974538303029248.

**Comment by AprilSylph** [comment]
Oh that's fun, I've never seen it inserted at all. I think I'm in a different bucket for the "More like this" test. I didn't ever intend for them to ever get inserted in the blog view, so I guess the selectors need to be more specific to prevent it from being targeted.

**Comment by marcustyphoon** [comment]
Oh, oops, uh, ignore my other PR then :D

**Comment by marcustyphoon** [comment]
Blog view sidebar with whatever I have on my account, with css translations, for potential future reference.

No, I don't know why all of the inline styles for the blog view modal are inserted again in the sidebar, but you did say it was a test :D

```html
<div class="vM8CJ • 📝sidebar">
  <div class="gJ6yV • 📝sidebarTopContainer">
    <header class="uYpYy WFEAx Vi52h • 📝header 📝isInSidebar 📝miniLayout">
      blog-specific header
    </header>
    <div
      style="
        --blog-title-color: #d71b2e;
        ...
        --color-modal-close-button-background: #ffffff;
        --border-radius-small: 8px;
        --black: 0, 0, 0;
        ...
        --follow: 243, 248, 251;
        --override-posts--color-primary-link: 0, 184, 255;
      "
    >
      <div class="B15CE • 📝desktopContainer">
        <div class="uJiXu • 📝title">Blogs like this one</div>
        <ul class="PwJi6 • 📝recommendedBlogs" aria-label="Blogs like this one" style="height: 236px">
          ...
        </ul>
        <div class="W9GZw • 📝dismissAll"></div>
      </div>
    </div>
    <div class="FZkjV • 📝sidebarItem">
      <h1 class="hF8Wr • 📝sidebarTitle">More like this</h1>
      <div class="rD_LN • 📝relatedPosts">
        ...
      </div>
    </div>
    <div id="xkit-sidebar">
      ...
    </div>
  </div>
  <div id="xkit-toasts" data-in-sidebar="true"></div>
</div>

```
