### ISSUE TITLE
Unfollow All / Mass Unfollow button?

### ISSUE THREAD

**Issue by Bennyxc00** [AprilSylph/XKit-Rewritten#725]
### Concept

I've been searching far and wide for something like this. The old "Tumblr - UnFollow All" script is gone and even via the web.archive.org it doesn't work anymore. Any chance you can work this out? Cuz everything else I've found seems very sketchy. 

Thank you.

**Comment by marcustyphoon** [comment]
I assume this kind of counts as a side effect of implementing Find Inactives, as long as it's sufficiently configurable to treat any blog as inactive!

**Comment by Bennyxc00** [comment]
I mean, if you can make it auto-unfollow all the “inactives” then yes!
