### ISSUE TITLE
Smart quote functionality in the post form

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#733]
### Concept

This would be both very convenient and very weird:

Unlike the real Tumblr tags input, the Quick Tags input converts doublequote characters into "smart" quotes, so that they can be part of the tag instead of doing very strange things. This is extremely useful, but the only way to do this from the post form itself is to draft the post, go to your drafts, add the rest of your tags with quick tags, then post the post.

My first proposed solution to this is an option for Quick Tags to just continue to show the text input form in the Quick Tags box in the post form. Of course, this sounds completely nuts unless the user realizes that this quotes functionality even exists, but it would at least be easy.

My second proposed solution to this is to add this smart-quotes functionality to the post form itself. I bet this is possible, either automatically or with a button in the tags area. With some clever code, it should even be possible to make the button only appear if one of the user's entered tags contains a quote character, at which point quite frankly the button could be pretty intrusive because submitting the post form with quote characters in the tag is effectively triggering a bug. Honestly, my main issue is that I don't know where this would go. Tweaks?

_(I'm also going to support-form the current behavior as a bug, but I think it does make sense for "replace the quote characters with something else" to be an XKit-specific solution. Unless Tumblr's back end can be made to just support quote characters, of course. Otherwise I assume Tumblr-side solutions would just be to add a warning message or split the tag on quote characters.)_

input: `#this is a tag with "an embedded quotation" that continues afterward`
tumblr: `#an embedded quotation` `#this is a tag with that continues afterward`
xkit: `#this is a tag with “an embedded quotation” that continues afterward`

**Comment by marcustyphoon** [comment]
...actually, tags are editable in the beta post editor now; I wonder if I can just make this work completely natively.

**Comment by AprilSylph** [comment]
I should just implement automatic smart quotes directly in the tags field, assuming the backend truly cannot handle plain quotes. I don't know enough about PHP to feel confident guessing as to why it treats them so strangely.

Either way, I don't think the convenience of this is great enough to warrant its inclusion in XKit's options. Sorry for not saying so sooner... I don't enjoy rejecting feature requests, so when I have the time/energy to participate in XKit maintenance, it's not exactly something I prioritise.

Closing PRs also isn't fun, but I do need to be realistic about what I intend to review and what I don't.

**Comment by marcustyphoon** [comment]
That's entirely fair! And no problem; I certainly don't mind having closed PRs. if I PR something it's generally because I was going to test the feature regardless, and maybe it sparks some discussion or inspires or becomes part of the source for a different feature later. I don't mean to make a bunch of extra work, though; I can imagine it might not feel great to do.
