### ISSUE TITLE
Quick Reblog not working

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#742]
Tumblr is testing new reblog controls, which breaks Quick Reblog's reblog button detection.

My main account was hit with this test, so hopefully I'll be able to craft an update tonight.

**Comment by AprilSylph** [comment]
New selector for the reblog button, while avoiding the reblog button in the menu:
```js
`${postSelector} footer button[aria-label="${translate('Reblog')}"]:not([role])`
```

**Comment by AprilSylph** [comment]
I didn't have time to implement and test this before the test was rolled back to less users, and now neither my main nor testing account are in the bucket.

@marcustyphoon Are any of your accounts still in the test?

**Comment by marcustyphoon** [comment]
Nope. I didn't even get to see it.

**Comment by Skeithh** [comment]
I currently have the new reblog test features on my account, if I can be of any help to test the new implementation

**Comment by AprilSylph** [comment]
@Skeithh if you clone the repository as it is right now, then load `src/` as an unpacked/temporary extension in your browser, you'll be able to test the fix. Be sure to either disable the release version of XKit Rewritten before you do (to avoid confusion; they'll have the same version number) or do so in a separate browser profile.
- [Loading a temporary extension in Firefox](https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Extensions)
- [Loading an unpacked extension in Chrome](https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest)

**Comment by partrah** [comment]
My account has been affected by this too so I did the load unpacked thing and it's working for me! Although it shows an error if I'm looking at the chrome extensions page, it's still working perfectly so far

**Comment by AprilSylph** [comment]
@partrah Thanks for testing the fix! I've now pushed v0.20.9, which should hit you in a day or two automatically. It's already approved for Firefox, I'll let you know when it's approved for Chrome.

**Comment by AprilSylph** [comment]
Now approved for Chrome!

**Comment by Hananasaur** [comment]
Just a comment on the reblog button fix... it used to also remember the already reblogged/queued posts from the /tagged/ pages, but now it doesn't seem to anymore. (It does remember it for the posts in the dashboard...)

Also thank you for applying such a quick fix!!!

**Comment by marcustyphoon** [comment]
Seems to be working for me, but I don't have the reblog control test. Skimming the code, I don't see any obvious reason why which page you're on or whether you have that test or not could affect the alreadyreblogged data saving or button coloration, but it's definitely possible. If you could try a few more times from different pages and file a separate issue with details if the problem persists, that would be great.
