### ISSUE TITLE
Quick Reblog: Tag suggestions cut off

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#765]
### Platform

MacOS 10.15.7 x86

### Browser

Firefox 106.0b3

### Addon version

v0.20.11

### Details

<img width="290.5" src="https://user-images.githubusercontent.com/8336245/192407135-6d370420-839c-453b-b3f0-edbee58db2d9.png" />

With more than a few tags entered in the quick tags interface, the suggested tags dropdown becomes filled entirely with the currently selected tags and the suggested options are not visible.

This appears to become an issue more quickly in Firefox than in Chromium, which lets the datalist element become wider than its corresponding input element, but it does happen eventually there as well.

I don't think datalists can be styled(?), so a fix for this would probably have to involve rendering `...[clipped current tags], suggestedTag` in the datalist and attaching a listener to it to fix things (if that's even possible).

**Comment by AprilSylph** [comment]
Unfortunately the way datalists work is that they replace the value of the input, so the current tags have to be included in full or they'll get modified/destroyed upon selecting an option. And `HTMLDataListElement`'s set of events is fully inherited from `HTMLElement` so I don't believe there's any way to intercept and modify this behaviour, unless we got very clever with another `input` event listener on the tags field.

**Comment by marcustyphoon** [comment]
Darn, I was worried about that. Right, I suppose we could... keep a temporary variable of the current input value, check if it suddenly changes to the value of one of the datalist elements... that seems possible.
