### ISSUE TITLE
no dashboard view/view in blog share links?

### ISSUE THREAD

**Issue by spiralavatar** [AprilSylph/XKit-Rewritten#769]
### Concept

with one of the newest updates to tumblr, i've noticed that they removed the "fold" option where you could original view the post inside of a blog itself, and the "share" button has also been redirecting most of it to that dashboard option, i was wondering if it is possible to bring back the option to share posts so they're using [url].tumblr.com rather than tumblr.com/[x]? or perhaps just bringing back the option to view a post in the blog rather than dashboard view?

thank you very much

**Comment by marcustyphoon** [comment]
> or perhaps just bringing back the option to view a post in the blog rather than dashboard view?

This is pretty much what the "open in tabs" script does, right?

> i've noticed that they removed the "fold" option where you could original view the post inside of a blog itself

Ooh, looks like you found a bug! I'll report this to Tumblr support.

Assuming this is indeed a bug, would the return of the little folded corner fulfill your use case?

**Comment by AprilSylph** [comment]
The timestamp in posts' meatball menus links to the blog network. You can right-click it and copy the link just like the dog-ear permalink.

**Comment by spiralavatar** [comment]
oooh, thank you!

**Comment by citrusella** [comment]
> This is pretty much what the "open in tabs" script does, right?

I know this is closed (found it by searching around to see if any XKit extension modifies links to the name.tumblr.com style), but... only sort of? It opens in a new tab, but if the link is not a name.tumblr.com variant, then it just opens the on dash version in its own dedicated tab (technically if the person has themes disabled or requires login then name.tumblr will redirect to /name but still).

**Comment by ohAitch** [comment]
Looks like they [removed it](https://changes.tumblr.com/post/705090738411782144/friday-december-30th-2022) again, this time intentionally; the meatball and share links both go to the dashboard view. Would it be possible to reopen this issue?

**Comment by AprilSylph** [comment]
The timestamp in the meatball menu uses the normal link. If it doesn't, the blog doesn't have a custom theme.
