### ISSUE TITLE
New Tweak Suggestion: Use Post Permalink for Share Link URL Format

### ISSUE THREAD

**Issue by prof-m** [AprilSylph/XKit-Rewritten#780]
### Background
Tumblr has implemented several changes to the URL format of "share links" - AKA, the link you get when you click the "Share" button on a post, and then click "Copy to Clipboard":
<img width="768" alt="image" src="https://user-images.githubusercontent.com/65079055/194366213-f96fe38c-c6d0-4963-befc-35159b26919f.png">

The most recent version of the share link URL looks like this:
`https://at.tumblr.com/anthropicmoose/tumblr-is-tracking-shared-links/02drni4ybt37`

But the permalink URL for that same post remains as it's always been:
`https://anthropicmoose.tumblr.com/post/697379457013514240/tumblr-is-tracking-shared-links`

The current share link URL has a number of issues, including increased tracking and frequent buggy redirects to app installations rather than the post itself, which tends to be annoying for anyone receiving a link. If the person sharing the link wants to give someone the post's permalink, they don't have a good way to transform the link they've copied into the original link, because the new share link URL format doesn't actually include the post's postId.

### Feature Request
A new tweak or other functionality that overrides the URL format of the share link when a user clicks "Share Button->Copy to Clipboard" on a post on their dashboard. 

Specifically one that turns a URL formatted like this:
Format: `https://at.tumblr.com/{blogname}/{postname}/{randomGuid}`
Example: `https://at.tumblr.com/anthropicmoose/tumblr-is-tracking-shared-links/02drni4ybt37`

Into the post permalink URL like this:
Format: `https://{blogname}.tumblr.com/post/{postId}/{postName}`
Example: `https://anthropicmoose.tumblr.com/post/697379457013514240/tumblr-is-tracking-shared-links`

### Technical Notes
Because the new share link URL format doesn't actually include the posts `postId`, you can't directly derive the post's permalink from the share link URL.

One way of retrieving it might be to just look elsewhere on the post's HTML - the permalink is still there, used in the top-right corner of a post:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/65079055/194369068-546057ba-4b93-4e09-9e28-954e60d7013b.png">

**Comment by marcustyphoon** [comment]
> frequent buggy redirects to app installations rather than the post itself

Those should get fixed, but totally agreed there should be a way to get the other formats.

I personally use the blog view URL format, i.e. `https://www.tumblr.com/anthropicmoose/697379457013514240/`, so I would love to have that option as well.

**Comment by AprilSylph** [comment]
If you use Firefox Enhanced Tracking Protection set to Strict, "Copy link" buttons will fail to generate Branch links, and retrying will give you the plain blog view URL.
