### ISSUE TITLE
Anti-Capitalism: remove ad-free plea

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#782]
Tumblr now runs its own adblocking plea banner, making it redundant to show our own plea modal.

**Comment by JoLiKMC** [comment]
I know it's entirely gratuitous at this point, but yes, whoever might be working on Anti-Capitalism, please do consider adding a toggle or some code to _remove Tumblr's_ on-Dashboard ad-free plea.  It only pops up once per login, it seems (for now?), but it's still kind of annoying.  And kind of funny, too.  "Hellsite", indeed.

**Comment by AprilSylph** [comment]
No.

**Comment by JoLiKMC** [comment]
… care to _expand_ on that?
