### ISSUE TITLE
Seen Posts: Dims posts I haven't seen yet with dashboard endless scrolling disabled

### ISSUE THREAD

**Issue by ChangelingRain** [AprilSylph/XKit-Rewritten#786]
### Platform

Windows 10

### Browser

Firefox 105.0.3 (32-bit)

### Addon version

v0.20.12

### Details

The initial display of posts on the Dashboard is correct. New posts will be highlighted, while posts already seen will be dimmed.
However, after pressing the 'Next' button to go to the next page of posts, all of those posts will be dimmed, even ones I haven't seen yet.

This is a new problem as of roughly this morning.

**Comment by DrHubertMalbec** [comment]
### **Platform**

EndeavourOS

### **Browser**

Firefox 104.0.1 (64-bit)

### **Addon version**

v0.20.12

### **Details**

Having the exact same issue as the user above. Worked fine when I went to bed, just woke up to find this issue occurring.

**Comment by ValensHawke** [comment]
Same exact issue as user above. However, mine happened around 10 AM Pacific. Also, perhaps related. There appears to be a change (perhaps bug?) to Tumblr if you have Endless scrolling turned off. Instead of the buttons being Previous/Next after you go to the Next page on your dash, it's now Latest/Next. I did report that to Tumblr. 
Windows 11
Firefox 105.0.3

**Comment by marcustyphoon** [comment]
Not sure if the button being "latest" is a bug (probably) but I am pretty sure the rest of it is a Tumblr bug. Wasn't able to pinpoint the buggy line of code without access to the source, though.

**Comment by marcustyphoon** [comment]
I would guess that they are. In any case there's nothing to really do to the XKit code for this issue (unless Tumblr decides not to fix this issue with posts immediately being shown twice; I could mitigate that manually but it should be unnecessary).

Also, if you have the same information as a previous issue/comment, please thumbs-up that issue/comment!

**Comment by ChangelingRain** [comment]
New information: After getting several next pages deep(initial dashboard page > 1 > 2 > 3 > 4), Seen Posts started working again for exactly one page(number 4) - the following page was again incorrectly dimmed, though, and it didn't happen again at page 9 or 10 deep so I have no idea what this actually means.

**Comment by grlgoddess** [comment]
I first noticed this on the old version of XKit. I was a few pages in when I disabled this function on old XKit, and enabled it on XKit Rewritten. It immediately worked properly on the current page, and for every page until I was actually caught up. I then returned to the first page by clicking the t icon in the top left.

I'm not 100% sure if it kept working at that point, if I had to go to page 2, as this was last night. After refreshing page 1 a few times last night before today refreshing again and going to page 2, it was definitely no longer working.

I don't currently have enough new posts to test, but perhaps toggling Seen Posts off and then back on for each session can work as a workaround?

**Comment by electric-snake** [comment]
I'm having the same problem, but if I turn it off before loading a new page and then turn it on again, it functions as expected. Works as a workaround, but it'll be nice to not have to remember to do it for every page again

**Comment by AprilSylph** [comment]
This should be fixed now! This was part of a bigger issue with the paginated dashboard on Tumblr's side.

**Comment by ChangelingRain** [comment]
It is indeed fixed for me!
