### ISSUE TITLE
Show every line of tags not working

### ISSUE THREAD

**Issue by Lycunadari** [AprilSylph/XKit-Rewritten#789]
### Platform

Mac OS 12.6

### Browser

Firefox 106

### Addon version

v0.20.12

### Details

When I check the "Show every line of tags by default" option in tweaks, it doesn't show more tags than without the option (still cuts of after four lines of tags), but still hides the "see all" button. It looks like this:
Without "Show all lines":

<img width="528" alt="Bildschirmfoto 2022-10-23 um 11 56 00" src="https://user-images.githubusercontent.com/116488860/197385855-4579b0ca-527a-490d-861d-e0afc8e265d1.png">

Without "Show all lines" after clicking "See all":

<img width="519" alt="Bildschirmfoto 2022-10-23 um 11 56 23" src="https://user-images.githubusercontent.com/116488860/197385787-d0ee52c2-731a-45f8-b204-4c2948624e65.png">

And with the "Show all lines" option checked:

<img width="514" alt="Bildschirmfoto 2022-10-23 um 11 56 48" src="https://user-images.githubusercontent.com/116488860/197385826-a4097ef8-2acc-49f6-9d67-4a5e66a8d8df.png">

So there's the last line of tags missing with no option to show them.

**Comment by marcustyphoon** [comment]
See #787! This should be fixed in the next release. Unfortunately I don't think GitHub has an option to leave resolved issues visible until the code that fixes them actually gets released.

**Comment by Lycunadari** [comment]
Ah that's great, thanks for your quick reply, and all your work here :)
