### ISSUE TITLE
Tag Tracking+: Unexpected behavior when following tags with sequential spaces (minor)

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#790]
### Platform

MacOS 10.15.7 x86

### Browser

Edge 106.0.1370.52

### Addon version

0.20.13

### Details

Following e.g. https://www.tumblr.com/tagged/xkit%20%20rewritten?sort=recent results in  a "0+" Tag Tracking+ number, as Tumblr returns results tagged
```
#xkit rewritten
```
but we filter out any posts without
```
#xkit  rewritten
```
This is presumably just kind of one of those edge cases with the tag system and I don't know that it's worth handling explicitly. I recall something related showing up on the changes blog recently too.

It did result in significant confusion when I apparently accidentally followed the two-spaces version of a tag though.

**Comment by AprilSylph** [comment]
We're no longer filtering results based on tag, instead we are filtering recommended & sponsored posts via `recommendedSource === null` & `displayType === undefined`, respectively.
