### ISSUE TITLE
Add a method to trigger the Quick Reblog pop-up on touchscreens

### ISSUE THREAD

**Issue by salazarbarrera** [AprilSylph/XKit-Rewritten#791]
### Concept

**Concept and motivation**

In mobile, when one taps and holds an image or <a> tag, Chromium and Firefox-based browsers alike display the context menu. At the same time, pressing and holding an element, will mimic a hovering cursor. Both things combined means that every time the Quick Reblog pop up is invoked, a context menu appears above it, slowing down the process and defeating its purpose in mobile browsers.

Adding an alternative way to invoke the popup would solve this problem. Maybe deleting the href and overriding the onclick listener associated to all the reblog buttons may do the trick, but I'm not sure if disabling the official click behaviour is the way to go.

*Things I tried*

I've been messing around with js and css injection to check if I could find a workaround without changing XKit Rewritten, but it seems adding a new option within the extension is the only way. In particular, I tried to disable the context menu, but it seems to be immortal in Android Firefox, and disabling the pointer events via css also disables the hover event. Also, I noticed that the reblog buttons and the new post button, share the same class.

**Comment by AprilSylph** [comment]
The hover event doesn't happen on touchscreens at all. We would need to disable the context menu and add some sort of long-press listener (I don't think that's an actual event in JavaScript).

**Comment by marcustyphoon** [comment]
Might be able to preventDefault() the touch event and then use the touch api to detect the long press. Might take a look at it at some point.

**Comment by salazarbarrera** [comment]
Maybe we could close this issue. Not because of Xkit rewritten itself, but because web mobile Tumblr already incorporated something similar.

**Comment by AprilSylph** [comment]
Between that and #893, yes, I think we can consider this resolved.
