### ISSUE TITLE
Tag Tracking+: list tags in sidebar

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#799]
This is what the sidebar utility was created for, and people want this. It's time to figure out how often to refresh the counts.

Idea that just struck me: copy the interval that Tumblr uses to hit `/v2/user/counts` (30s).

**Comment by AprilSylph** [comment]
More ideas:
- Keep the counts in memory, use same values between sidebar & search bar
- Always refresh a count if its last-seen timestamp changes
- Wait for all API fetches to resolve before visually updating the counts

**Comment by marcustyphoon** [comment]
Additional idea: store counts and last-fetched timestamps in local storage, use the cached value initially, and skip the fetch and assume it is fresh if it has been fetched in the last [30 seconds or something]. This would prevent the `...` from appearing at all, and would prevent a large number of API requests if you open a bunch of Tumblr tabs in succession, change a setting that hard refreshes redpop, etc.

I also spent a while thinking about methods to ensure that multiple simultaneously open Tumblr tabs don't cause additional unnecessary API requests (i.e. "if any last-fetched timestamp is in the last 30 seconds, skip this fetch").
