### ISSUE TITLE
Trimmed posts not rebloggable 

### ISSUE THREAD

**Issue by jessrotzi** [AprilSylph/XKit-Rewritten#806]
### Platform

Windows 10

### Browser

106.0.5 (64-bit)

### Addon version

0.20.13

### Details

It does not happen all the time, but there have been a handful of instances when I used the Trim Post option where the other person involved could not reblog the post. One such one was [this post](https://wanderingsongbird.tumblr.com/post/699050508400410624/the-admission-that-he-was-weaponless-did-get-her) and [this one](https://wanderingsongbird.tumblr.com/post/698503566777794560/what-hair-products-do-you-use-wanderingsongbird) -- it was the same user for this (ask-the-ghostface), but two different blogs (or rather, one blog, but the leon-the-rookie is a side blog. 
Another instance of this happening was with user dark-lina (also a firefox user) [here](https://wanderingsongbird.tumblr.com/post/699051845462769664/its-a-beautiful-melody-with-a-lot-of-sadness).

It did happen on another blog of mine, but I did end up deleting the post and just reblogged it without the trim.

Each of these were originally answered asks, too, that I used the trim option on.

No other users had issues with this, as I did check in when this first popped up.

**Comment by AprilSylph** [comment]
Strange, I am able to reblog the first post using both the legacy and beta editors. I was expecting this to be an issue with the legacy editor...

It would be helpful if the affected users (those who cannot reblog the posts) could put screenshots of their errors either here or in tickets to Tumblr support.

**Comment by jessrotzi** [comment]
Thank you for your patience. I was working and having to check with other
people as we went along with rps as usual.
The consensus from my rp partners were the same -- the reblog button itself
would end up greyed out entirely and they could not interact with the post.
[image: image.png]
^^^ Like this.
I did go in and check the settings on the post they could not reblog, and
it was set to where anyone on tumblr could reblog (see below)
[image: image.png]
This particular post is found:
https://www.tumblr.com/breathless-songbird/701079231212486656/good-evening-miss-i-see-you-are-doing-lovely-on
(I do apologize! It is a nsfw blog, but the post itself IS safe fore work.
Shibari is being discussed, and I'd rather it not be on my normal blog, and
I would rather give you a heads up instead of sending you in without one.

Now their screen snippet they used was from firefox, but they use safari on
their iphone, and it is still greyed out.

**Comment by jessrotzi** [comment]
For one of them it was added part of the way through. For the other it had
been there since the start.

Here are the links to the images instead.
To show where the reblog is grayed out. Sometimes it has let people hit the
reblog but it never actually posted.
https://cdn.discordapp.com/attachments/1039796151462928424/1042436756777222154/image.png


And a link to the image I had of it showing my options being set to where
anyone on tumblr can reblog
https://media.discordapp.net/attachments/1039796151462928424/1042438610915430450/image0.jpg


And I do have a friend that doesn't seem to have issues with the reblogs?
He uses Firefox, but he's in Germany. So I don't know if location has
something to do with it.
