### ISSUE TITLE
shared link tracking remover

### ISSUE THREAD

**Issue by thecloudking** [AprilSylph/XKit-Rewritten#810]
### Concept

tumblr's link sharing was recently changed to add tracking information at the end of urls. lots of users hate this change, and while the old link format without the tracking format still works it would be nice to have the option for xkit to reformat the links for xkit users instead of having to do it manually

example:

the link as tumblr currently copies it (not my post)
https://www.tumblr.com/polkadotmotmot/614889112046075904/ian-cumberland-black-hole-ii-2016?source=share

the link as it would be formatted before this change was implemented
https://polkadotmotmot.tumblr.com/614889112046075904/ian-cumberland-black-hole-ii-2016

**Comment by AprilSylph** [comment]
That format doesn't have any tracking. `?source=share` has zero identifying information other than what button was pressed to get the link. If you're talking about `at.tumblr.com` links, you can block Branch.io with Firefox Enhanced Tracking Protection or other network blocks and the "Copy link" buttons will fail on the first try, then copy the version you put here.
