### ISSUE TITLE
Hide Recommended Blogs between posts inconsistent with pagination

### ISSUE THREAD

**Issue by Heilos2006** [AprilSylph/XKit-Rewritten#812]
### Platform

windows 7 Version 6.1.7601

### Browser

Google Chrome Version 107.0.5304.107 (Official Build) (64-bit)

### Addon version

v0.20.13

### Details

I have toggled the extension on and off, tried refreshing multiple times and it's still not working. The recommended blogs show up every second page at the top of the screen when hitting the "next" button while using the pagination option on tumblr.

![image](https://user-images.githubusercontent.com/117964575/201264103-dba9a4d6-1362-489e-b298-fbc307c9cdda.png)

**Comment by luxidoptera** [comment]
Having the same issue here; accidentally made a new issue for this as I missed your post. It only shows up after a few pages of browsing for me.

![image](https://user-images.githubusercontent.com/15697751/201552241-06919886-c6bb-49ca-ae31-4f9795a79f3a.png)

**Comment by marcustyphoon** [comment]
Implementation notes to self:
- see #338 
- fix should work on /tagged/ pages ("`Top %1$s blogs`") as well as "Check out these blogs"
- pagination enabled detection is doable but pagination state appears difficult to detect (even with react data)
- most straightforward method is probably detecting the `announcement` class or `objectType: announcement` in timelineObject data for titles that should be excluded; not sure how robust this is though

![image](https://user-images.githubusercontent.com/8336245/201589847-2b2a94b1-b9f4-4a31-87f2-91ccc583219d.png)
