### ISSUE TITLE
Tag Tracking+: Tags in sidebar break

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#821]
### Platform

MacOS 10.15.7 x86

### Browser

Ungoogled Chromium 107.0.5304.110

### Addon version

master

### Details

- Enable Tag Tracking+ and the new sidebar function
- Navigate to a search page
- Wait briefly for the initial API fetches to complete
- Soft navigate to the dashboard
- The Tag Tracking+ sidebar is added with ellipses and they are not updated

**Comment by AprilSylph** [comment]
Ah, I see, the sidebar isn't getting inserted into search pages... looks like I actually only fixed explore & hubs, and just assumed search pages would work too.

Relying on the sidebar being present in the page when the count is updated is also not very holistic.

**Comment by AprilSylph** [comment]
Oh, I just never committed the work that fixes the sidebar util on explore/search/hubs at all. Fail moment
