### ISSUE TITLE
Queue and Reblog tags separated from Quick Reblog

### ISSUE THREAD

**Issue by moonflowcr** [AprilSylph/XKit-Rewritten#836]
### Concept

I don't use the Quick Reblog feature in XKit Rewritten because I prefer to use the beta editor, but I like to have a tag for my queued posts, so the idea would be making it a separate feature so I don't have to have a feature I don't use enabled

**Comment by AprilSylph** [comment]
Even if you enabed Quick Reblog, its queue tag option does not affect the editor. If your queue tag is complicated, you can add it as a bundle in Quick Tags and add it to your posts that way.

Detecting what state the editor is in to situationally add or remove tags is not a problem I would expect to be tackled for the foreseeable future.
