### ISSUE TITLE
Tag Tracking+ Does not update

### ISSUE THREAD

**Issue by Echoweaver** [AprilSylph/XKit-Rewritten#846]
### Platform

MacOS 10.15.7 Catalina

### Browser

Firefox 107.0

### Addon version

0.21.0

### Details

Since the update adding the Tag Tracking+ sidebar (which I LOVE as a layout), my unread count does not update. It either stays at "..." or updates to 0 when I click through each tag to read it. This is true whether the sidebar is enabled or not.

I let it sit and watched the issue tracker for a while to see if anyone else reported this problem, but I haven't seen anything. I guess that means it's likely an issue with my non-Windows, non-Chrome setup. I also run with Privacy Badger, so I know I'm a PITA case. However, this feature did work for me before the update.

**Comment by AprilSylph** [comment]
> non-Windows, non-Chrome setup

I develop Firefox addons here, and I sure as hell don't do it on Windows

**Comment by AprilSylph** [comment]
Does disabling Privacy Badger affect it at all? I wouldn't imagine that it would, but nice to eliminate it as a factor.

**Comment by AprilSylph** [comment]
Working for me on Firefox 107.0 (64-bit) with Enhanced Tracking Protection & uBlock Origin enabled, FWIW (on Windows 10, but this is likely not a factor)

**Comment by AprilSylph** [comment]
Could you show me the result of the following steps?

1. Open a Tumblr tab
2. With it focused, select the application menu &rarr; More tools &rarr; Web Developer Tools
3. Select the Network tab in the devtools
4. Enter `?limit=20` into the "Filter URLs" field
5. Refresh the tab

When the Tag Tracking+ sidebar appears, you should see some requests start popping up. Screenshot those for me when they finish (there should be one per tag you track). Here's how mine looks:
![image](https://user-images.githubusercontent.com/28949509/202915551-476d4d71-f808-4e9b-b988-1cee9bcb36ab.png)

You may have to resize the devtools and/or dock it to the right of the page (via its own little meatballs button) to get a good screenshot.

**Comment by AprilSylph** [comment]
Current hunch: fetching posts for your first tracked tag fails for some insane reason (like the tag has a forwardslash or something) and the loop errors out, so none of your counts get updated. If **none** of your tracked tags failed to update before, though, this is unlikely as I don't believe I changed how the individual requests are made.

**Comment by Echoweaver** [comment]
> Current hunch: fetching posts for your first tracked tag fails for some insane reason (like the tag has a forwardslash or something) and the loop errors out, so none of your counts get updated.
> 
> If **all** of your tracked tags successfully got an unread count before the update though, this would be unlikely, as I don't believe I changed how the individual requests are made.

Yes, I didn't have any trouble with the tracked tags up until now. However, my first tracked tag is wonky, so there might be something to that.  

That first tracked tag is a thorn in my side. It's "##simblr #today's recap" (as a single tracked tag). That tag is an artifact from a bajillion tumblr revisions ago. At that time, it was a twisted but valid way to search for multiple tags. A tumblr revision at some point broke that probably unintended functionality, and now I can't remove it from my tracked tags because everything I attempt to do interacting with it fails. There's likely some way to just get a list of tracked tags and delete one, but I'm not that savvy a tumblr user. 

So, if that thing threw an error that affected things downstream, that might be my problem.

I'll give you the rest of the info presently. Sorry for maligning your platform support. 😅

**Comment by marcustyphoon** [comment]
Ooh, cool! Yeah, that's probably it. I wouldn't call it your problem; to the contrary, I'm glad that scenario occurred to someone with the inclination to report it and the ability to speculate and provide good info on what's happening, so we can prevent it from breaking for anyone else!

**Comment by Echoweaver** [comment]
Yup. That's it.

If anyone in the savvy tumblr world could give me advice on how to remove that blasted tracked tag, I would love them forever. Everything I've found searching online gives the "click through the tag and select Unfollow," which does not work well when the tag won't load at all....

<img width="996" alt="Screen Shot 2022-11-20 at 7 17 59 PM" src="https://user-images.githubusercontent.com/1949507/202934643-235a1c50-ca3b-4fdb-85d9-bec561ffeff7.png">

**Comment by marcustyphoon** [comment]
Can reproduce by following that "tag" using a direct API call in the browser console.

```js
await window.tumblr.apiFetch('/v2/user/tags/add', { method: 'POST', body: { tag: "#simblr #today's recap" } })
```

This, of course, means you can also remove the follow with:

```js
await window.tumblr.apiFetch('/v2/user/tags/add', { method: 'POST', body: { tag: "#simblr #today's recap" } })
```

This is a Tumblr bug and they should be able to fix it (it is doing  `{ tag: "simblr #today's recap" }`); we should report this!

**Comment by Echoweaver** [comment]
Duuude. I'm going to see if I can remove it that way.

But perhaps I'll keep it around for awhile for testing purposes.
