### ISSUE TITLE
Tag Tracking+: add error handling to `refreshCount`

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/XKit-Rewritten#847]
Expect the `apiFetch` to potentially throw; if it does, set the count string to `\u26A0\uFE0F` (⚠) to communicate the failure to the user.

Possible partial solution to #846, as this should prevent `refreshCount` from ever throwing and interrupting the `refreshAllCounts` loop.

**Comment by marcustyphoon** [comment]
I guess the shortest solution to this would be replacing Promise.all with Promise.allSettled! (Not saying we should do only that, of course, just noting it because I haven't used that function before and before now it wouldn't have crossed my mind.)
