### ISSUE TITLE
Quick reblog renders under hlDot when Infinite scrolling is disabled

### ISSUE THREAD

**Issue by HydraheadHunter** [AprilSylph/XKit-Rewritten#848]
### Platform

windows 10

### Browser

Firefox

### Addon version

v0.21.0 Beta

### Details

When infinte scrolling is disabled, the bottom of a tumblr page has a horizontal bar, class `hlDot` under class `D5eCV.`

`hlDot` has a z-index of 100. Quick reblog has a z-index of 97. This cause the quick reblog interface to be obscured by `hlDot`, a horizontal bar thick enough to obscur approximately two quick tags. For users with two to three quick tag bundles, the bar obsures the tag field and reblog button.

Suggest increasing the quick reblog feature's default z-index to >100 as a potential long term solution to the problem, or if that's untennable, a css modifier that lowers the z-index of `hlDot to` <97. 

Edit: it was `hlDot` not `h1Dot`. This inability of me to read has caused some confusion. I'm editing my posts with the correct name, but mentioning the whoopsie here to explain what happened.

**Comment by HydraheadHunter** [comment]
Update: the object h1Dot is not consistantly there, I'm looking into what cause it to start existing, but I'm bad at computers.

**Comment by marcustyphoon** [comment]
What does it look like? I'm looking as well.

**Comment by HydraheadHunter** [comment]
it's just a black(?) bar that's attached to the bottom of the page. It's color might be decided by the palette you're using (and so not always black) but when it exists, it renders directly below the legal contact information for tumblr. It's always a part of some larger class which is aligned to the bottom of the page with a bit of a gap.

My working theory is something something infinite scroll event controller, and it sometimes exists despite infinite scroll being disabled because tumblr is a webbedsite with bugs. But that hypothesis doesn't have any supporting evidence and is based solely on my gut instinct.

**Comment by marcustyphoon** [comment]
Thanks, that's interesting! I wonder if this is a Tumblr bug.

**Comment by AprilSylph** [comment]
`D5eCV` &rarr; `bluespaceLayout`
`h1Dot` &rarr; Does not exist in the CSS map

This is very curious, I wouldn't expect any Redpop dev to use a literal classname unless completely necessary (which is usually never). I'll take a look when I can to satisfy my curiosity, but I have a hunch that some other extension might be inserting this.

**Comment by HydraheadHunter** [comment]
The bug finally happened again. still don't know what causes it, but new information; this appears to be a second empty copy of the tumblr main body and header being suffixed to the first one which probably supports your hypothesis, but I have no idea what extension would insert an empty copy of the tumblr dashboard and header underneath the tumblr dashboard.

Below are screenshots of the normal html, the buggy html, and bug itself. Please, ignore my cringe quick tags.

![Screenshot 2022-11-20 200320](https://user-images.githubusercontent.com/34995041/202945422-ed04ee2b-1bde-4df1-bfd7-b8af8345cbf3.png)
![Screenshot 2022-11-20 200532](https://user-images.githubusercontent.com/34995041/202945435-8b9c264f-8e83-4580-b5e8-ee787c5a0267.png)
![Screenshot 2022-11-20 200145](https://user-images.githubusercontent.com/34995041/202945443-eaa6ba97-8a7d-43aa-aa62-956cf5ebdef6.png)

**Comment by HydraheadHunter** [comment]
After looking up what the words "hydration error" mean, because I cannot stress enough that I only know just enough about computers to be a danger to myself and any device I interact with, yeah that sounds like a good explaination of why this is probably happening.

I'm not good enough with computers to be helpful beyond this point, especially considering that a solution to the cause of the bug is mostly academic to me since treating its primary symptom only required knowing the actual name of the problem element, followed by quickly writing two lines of css in stylish to lower `hlDot`'s z-index to 96.

If y'all decided to continue pursuing this, I wish you luck; and if you decide it's not worth the trouble, well I'm probably one to agree.

**Comment by marcustyphoon** [comment]
Hopefully this is fixed by the underlying bug being fixed (by Tumblr) and that element no longer existing at all! If not, we'll certainly do something to adjust.

**Comment by AprilSylph** [comment]
If you can make the double `#base-container` appear reliably, please file a ticket with Tumblr support detailing the steps you take; this element absolutely should never appear twice in the DOM
