### ISSUE TITLE
Tag Tracking+: Support opening new tabs from sidebar

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#854]
### Concept

Requested by kristin in the New XKit Discord:

> glad to see the tag tracking sidebar back! wish i could right click it though

...and also by me. Right-clicking and control-clicking/command-clicking the sidebar tag links to open their targets in a new tab would be awesome.

Would we have to change from a `<button>` to an `<a>` for this?

**Comment by AprilSylph** [comment]
> Would we have to change from a <button> to an <a> for this?

If we want to just support CTRL+Click, no, but not everyone is savvy enough with keyboard shortcuts to rely on this. The sidebar util should be modified to support `href` per item in addition to `onclick`. `<a role="button">` is semantically identical to `<button>` anyway.
