### ISSUE TITLE
Quick reblog allowing me to reblog unrebloggable posts

### ISSUE THREAD

**Issue by missapple93** [AprilSylph/XKit-Rewritten#859]
### Platform

macOS Ventura 13

### Browser

Firefox 107 (64-bit)

### Addon version

0.21.0

### Details

My friend set his post so that no one could reblog it, but I was somehow able to save it as a draft and reblog it using the quick reblog feature. As a note, when I had it saved as a draft I used Tumblr's native dropdown menu to switch from "save draft" to "post" and got the appropriate error messages about unrebloggable posts. Attempting to edit my reblogs also does not save and prompts the same error, so I think it's isolated to quick reblog. The post in question is https://www.tumblr.com/eluciferate/701643354671349760/this-is-wild-hallie-can-reblog-my-unrebloggable. 

I can see this being an unwelcome feature for people who'd prefer to keep their posts from spreading, so I wanted to report it ASAP. Please let me know if you have any questions. Thank you!

**Comment by marcustyphoon** [comment]
Oops. I totally missed this issue when it was created!

I didn't manage to reproduce this yet. For me, the quick reblog popup will not show up on a disabled reblog icon, and when I hack the code to get it to show up anyway, attempting to use it fails as expected.

When you were able to do this, did the reblog icon appear greyed out? Are you able to do it now, or was it a short-term thing?

**Comment by AprilSylph** [comment]
I can see the "problem" with the post linked: mentions. Blogs that are mentioned in a post can always reblog that post.

**Comment by marcustyphoon** [comment]
Wow, that's an odd bit of undocumented behavior. Should I support request adding that to help?

Anyway, do you know offhand if mentions in the reblog chain count? (I can go test this.)

**Comment by AprilSylph** [comment]
I wouldn't call it undocumented...

![image](https://user-images.githubusercontent.com/28949509/205485810-2a6a20ca-f92f-4235-944c-56359767f7ec.png)

**Comment by marcustyphoon** [comment]
...Wait, I literally just opened... okay apparently I didn't just open the post form to check! Or I did and I only read the dropdown label.

> “No one” means that your post cannot be reblogged by anyone, ever.
> https://help.tumblr.com/hc/en-us/articles/231236387-Reblogs

This could probably use a bit of a poke even though it's above a screenshot that does include, well, what you just screenshotted. Not really readable though.
