### ISSUE TITLE
Hide Seen: Remove seen posts entirely from display

### ISSUE THREAD

**Issue by char-lock** [AprilSylph/XKit-Rewritten#869]
### Concept
While the Hide Seen script dims seen posts as one would want, I have found it much more beneficial to my Tumblr experience to have the posts hide upon a reload of the page.

### Proposed Solution
I implemented an additional preference to a custom version of XKit Rewritten that proved very nice to my overall experience -- pretty simply, if the plugin encounters a post it registers as seen, and the preference is enabled, it deletes the post element entirely, which also assists in protecting memory resources from piling up. If the user wants to see the posts again, you just disable the preference and reload.

I used my custom version of this feature for a few weeks now, and it has proved pretty much bug free, but I wanted to get general consensus on whether this should be implemented to the wider plugin features.

**Comment by AprilSylph** [comment]
> it deletes the post element entirely

never do this. React will crash if it tries to remove an element that doesn't exist on the page.

I would be open to having this be implemented so long as it doesn't break endless scrolling, or only works with endless scrolling disabled.

**Comment by marcustyphoon** [comment]
From a technical standpoint I would probably lean towards what we do in scripts like Show Originals, setting the css `display: none` property on the `article` element, since actual removal breaks j/k scrolling and doesn't - oh hi April. Anyway, yeah, the memory benefits aren't huge I think and we try to make everything reversible without a refresh.

**Comment by char-lock** [comment]
> > it deletes the post element entirely
> 
> never do this. React will crash if it tries to remove an element that doesn't exist on the page, or has otherwise been moved from its original parent.
> 
> I would be open to having this be implemented so long as it doesn't break endless scrolling, or only works with endless scrolling disabled.

I haven't experience any issues in runtime, and endless scrolling works flawlessly.

**Comment by char-lock** [comment]
> From a technical standpoint I would probably lean towards what we do in scripts like Show Originals, setting the css `display: none` property on the `article` element, since actual removal breaks j/k scrolling and doesn't - oh hi April. Anyway, yeah, the memory benefits aren't huge I think and we try to make everything reversible without a refresh.
> 
> Also check out Show Originals' `lengthenTimeline` function, which ensures the user can scroll to load more posts if all of the current ones are hidden!

I tried this in an original implementation, and it eventually caused an extreme amount of lag from just the sheer amount of posts being hidden. Albeit that took a while, it was still noticeable.

**Comment by char-lock** [comment]
So that it's less nebulous, the proposed implementation can be found here:
https://github.com/char-lock/XKit-Rewritten/commit/5c6ccc1c26d6ad7e7d998031413a33635062163c

**Comment by marcustyphoon** [comment]
The endless scrolling thing is referring specifically to the scenario where you hide your entire initial page of results; lengthening the timeline fixes this.

If you remove the post element itself, k definitely breaks. If you only remove the article elements, j/k works.

Even though it works in practice now, both to prevent crashing the Tumblr code if there is ever a feature added that does try to manipulate a hidden post and to keep the consistent behavior throughout the extension that script toggles always work in both directions, I think we would want to use the CSS method.

**Comment by char-lock** [comment]
Fair enough! That's an easy enough swap-over. I'll go ahead and change up implementation to use the CSS.

**Comment by marcustyphoon** [comment]
Trying to think of problematic edge cases here. Should this exclude the user's own posts? Editing a post refreshes it on the dash, right? Would it vanish then?

**Comment by char-lock** [comment]
I, personally, like hiding my own posts, but we could add a secondary preference that hides your own posts.
