### ISSUE TITLE
Trim Reblogs: More descriptive description

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#872]
### Concept

Should we change the description line on Trim Reblogs to e.g. "Trim long threads after posting or drafting" or something? I don't know how to fit it into one line but any way to make something unintuitive more obvious seems important, and with what looks like the beginning of the retirement of Editable Reblogs I see a lot of confusion.

**Comment by AprilSylph** [comment]
I'm fine with it fitting into two lines. We already see overflow on Vanilla Audio & Vanilla Video.

Also, the wiki needs updating for Trim Reblogs' new pick-and-mix behaviour, oops.

**Comment by marcustyphoon** [comment]
|  hm |
| - |
| <img width="375" src="https://user-images.githubusercontent.com/8336245/204748291-10001816-3b95-4342-be04-cedf3bbf240d.png"> |
| <img width="375" src="https://user-images.githubusercontent.com/8336245/204748316-68aa7ffb-9e8b-4667-be21-a885e653f37c.png"> |
| <img width="375" src="https://user-images.githubusercontent.com/8336245/204748331-abe8c0a6-2a42-4f9f-b157-69228e2cd53d.png"> |
