### ISSUE TITLE
AccessKit Disable Gifs: Buggy behavior in new post editor

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#875]
### Platform

MacOS 10.15.7 x86

### Browser

Ungoogled Chromium v107.0.5304.110

### Addon version

v0.21.0

### Details

Disable Gifs tries to process gifs in the post editor, succeeding in adding a gif label but failing to actually pause the gif and causing a flicker effect on mouseover.

I didn't look into the exact details of this, but realistically I don't think it matters: if someone is inserting a gif into their post I assume they're probably okay with seeing it animated for a bit, so the most logical fix for this seems like excluding gifs in the post editor.

**Comment by marcustyphoon** [comment]
This statement is fully intended to be read as a joke, but you know, considering the lack of semantically unique translated class names on the gutenblr container elements*, I wouldn't hate having an obviously-gutenblr id on there somewhere. Just in case any redpop devs are reading this, you know, by pure chance :P

*`blockEditorContainer` is pretty good, but it doesn't contain everything; off the top of my head `postContainer` isn't used anywhere else, but that's of course not specific at all!

**Comment by AprilSylph** [comment]
What's wrong with `.block-editor-writing-flow`? Does the issue occur in the reblog trail preview too?

**Comment by marcustyphoon** [comment]
Oh, yeah, that's fine and actually better in this case, good point. 'Twas more of a general statement (I ran into this in #865.)
