### ISSUE TITLE
trim reblogs causing duplication of reply.

### ISSUE THREAD

**Issue by draindive** [AprilSylph/XKit-Rewritten#892]
### Platform

windows 10

### Browser

microsoft edge

### Addon version

0.21.0

### Details

this seems to be a problem occuring at random amongst a lot of people, but it's something i've seen happen a fair few times now. some people seem to be experiencing their most recent addition when reblogging, duplicated, ie, it posts twice despite only writing it once in that same thread. i'll link an example below: this person replied to one of my posts after trimming, only to end up with their post showing twice in the same thread despite only writing it out once. 
![example](https://user-images.githubusercontent.com/15834707/205470698-d5d231f5-64ff-4c23-9a29-d22459b16414.png)

**Comment by marcustyphoon** [comment]
Hm, has it happened to you? I'd love to know a) the exact sequence of events, b) whether Trim Reblogs warned the user about the thread being made with the legacy post editor, c) whether the thread or any of the additions in the thread actually were made with the legacy post editor, naturally.

I'll try and play around with it and see if I can reproduce it based on pure guesswork, but more information helps, of course.

**Comment by draindive** [comment]
it hasn't happened to me yet, as far as i know because i'm either fully using legacy or fully using beta depending on which blog i'm on. the thread in this post was made entirely with the beta editor, however, and the party involved intentionally left the post alone / didn't use legacy editor when writing their reply to me here because the blog i have doesn't have legacy. this has happened to a friend of mine who has, also, been on a fully New Tumblr Post Editor blog. it seems to be occuring both fully on legacy to trim and vice versa, as well as on beta to beta. the poster managed to cut the duplicated post from the thread using trim reblogs after posting, though, but the bug seems to happen when processing the post Being Posted as they didn't spot it until it showed on the dashboard.

**Comment by marcustyphoon** [comment]
Strange! Thanks for the additional info.
