### ISSUE TITLE
PostBlock: Block posts instantly (minor)

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#894]
### Concept

PostBlock should be able to use the storage architecture that Seen Posts uses as of #523 to process posts instantly when soft navigating. This seems a bit ironic, as the comment in that post describing how the implementation ought to work describes it as "PostBlock-like."

**Comment by marcustyphoon** [comment]
Now that I think about it, this could also be done by adding a data attribute to every post with its root id and making a css selector that hides the root ids the user has blocked (the way notificationblock does it).

I don't think it really matters which way one does it. This way would perform slightly better when blocking or unblocking a post, I guess (no need to touch every post with classList.add/remove), but does it matter?

**Comment by alleycatboy** [comment]
> Now that I think about it, this could also be done by adding a data attribute to every post with its root id and making a css selector that hides the root ids the user has blocked (the way notificationblock does it).
> 
> I don't think it really matters which way one does it. This way would perform slightly better when blocking or unblocking a post, I guess (no need to touch every post with classList.add/remove), but does it matter?

I like this idea, I think it could really cut down on how many times the DOM is touched.

**Comment by alleycatboy** [comment]
Also it seems like there's an awful lot of processing going on in checking and adding/removing classes that may or may not already be there for every single post on the dashboard.

**Comment by marcustyphoon** [comment]
Yep. Of course, it presumably makes the CSS engine have to do more work, which has to be done a lot more often then blocking/unblocking a post, which is done, you know, basically never :D But I'm constantly surprised at how unreasonably fast CSS layout engines seem to be.
