### ISSUE TITLE
Quote Replies: Show all buttons when using touchscreen

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#895]
### Concept

Right now, quote replies is presumably pretty annoying to use when using a touchscreen.

The way I would probably solve this is by adding an event listener that adds an e.g. xkit-has-touchscreen class to the document body on the first touch event, and overriding the only-on-hover css based on that. (Maybe this could be removed on a long debounce?)

**Comment by AprilSylph** [comment]
`hover: hover` is a good media query too

**Comment by marcustyphoon** [comment]
Interesting! I wonder whether that's switched when you change between tablet and non-tablet mode on a Surface device.
