### ISSUE TITLE
PostBlock isn't working

### ISSUE THREAD

**Issue by wordywarlock** [AprilSylph/XKit-Rewritten#90]
- **The browser I'm using is: Firefox** 
- **My browser version is: 86.0** 
- **My XKit Rewritten version is: v0.1.1 (Beta)** 

---
I noticed that the PostBlock I was using was the base Xkit version, rather than Xkit Rewritten. I uninstalled the addon from regular XKit, and now the Xkit Rewritten version doesnt show up- posts dont have a block button at all.

**Comment by AprilSylph** [comment]
the new PostBlock button is in posts' meatball menus; is it missing there? (unable to reproduce on Firefox 87.0b6)

**Comment by wordywarlock** [comment]
Ohhhhhh, I didn't know that. Thank you.
