### ISSUE TITLE
Tag Replacer: Option to replace in queue/drafts

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#931]
### Concept

It would be nice to be able to replace tags in one's drafts/queue as well as in published posts.

This could be implemented, for example, as three checkboxes in the UI for published posts/drafts/queue, with a default that one of them is checked based on the location on which the user opened the UI, or something.

**Comment by AprilSylph** [comment]
Can queues/drafts be filtered by tag? Wouldn't want to have to fetch an entire 1000-post queue just to replace 3 tags

**Comment by marcustyphoon** [comment]
Good point. I don't think so. Certainly if there is a way, it's not documented.
