### ISSUE TITLE
Quick Reblog: Reblogged checkmark is misplaced in mobile view

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#938]
### Platform

MacOS 10.15.7 x86

### Browser

Ungoogled Chromium v108.0.5359.98

### Addon version

master

### Details

With a viewport width less than 990px, the reblogged checkmark moves to the top left of the reblog icon instead of the bottom right. 

<img width="262" alt="Screen Shot 2023-01-20 at 10 05 34 PM" src="https://user-images.githubusercontent.com/8336245/213846178-f05a60f6-7ba4-43ec-8b7e-19a8eeee7708.png">

**Comment by AprilSylph** [comment]
Can you still reproduce this? I can't.

As far as I can tell I fixed this in fcd62e67687cc67acdd228af6783c7bb66b8dbee, but that commit predates this issue by a lot.

**Comment by marcustyphoon** [comment]
I saw it momentarily while the page was reflowing while resizing just now, I think, but that of course doesn't count. I'll assume it's fixed unless I see it again!
