### ISSUE TITLE
Quick Tags feature spits out just errors

### ISSUE THREAD

**Issue by PannaLisenka** [AprilSylph/XKit-Rewritten#940]
### Platform

MacOs Monterey 12.5.1

### Browser

Mozilla Firefox 108.0.2

### Addon version

0.21.0

### Details

Hi, I just installed XKit and used the Quick Tags feature – worked great, except I listed the tags with hashes, so in my posts all tags looked like ##tag. I removed the hashes from the list, and now the QT doesn't work at all. I thought this might do with the use of slashes in the tags, but I removed all of those and still it doesn't work. Put in a new list of tags, completely random – again; worked once, and then nothing. Then I added the original bundle of hashtags to XKit, tried the QT – worked once, then error galore. Help?

Backup:

`{ "enabledScripts": [ "quick_tags", "anti_capitalism" ], "quick_tags.preferences.answerTag": "", "quick_tags.preferences.autoTagAsker": false, "quick_tags.preferences.originalPostTag": "", "quick_tags.preferences.tagBundles": [ { "title": "test", "tags": "day, window, sky, crap, donna williams, levity, carnival, britney, asshole, demo, bill, andrew, tate, category, awesome, library, picnic, trash, cocacola, trashcan, velocity, oval, tube, intestine" } ] }`

**Comment by marcustyphoon** [comment]
What errors are you seeing? Can you screenshot them or something? I'm not encountering any errors using your backup or manually putting slashes or hashes in a bundle.

**Comment by PannaLisenka** [comment]
There you go:

<img width="1192" alt="Screenshot 2023-01-22 at 21 40 03" src="https://user-images.githubusercontent.com/123244270/213939286-0732489a-8d70-497f-9d93-58ee883e16d3.png">

<img width="1192" alt="Screenshot 2023-01-22 at 21 40 30" src="https://user-images.githubusercontent.com/123244270/213939293-74a095f6-c211-44b1-9a99-44aae425aa19.png">


<img width="1192" alt="Screenshot 2023-01-22 at 21 40 34" src="https://user-images.githubusercontent.com/123244270/213939304-7c7cd13d-5d43-4c5a-abff-8d0d19f4398e.png">

**Comment by AprilSylph** [comment]
Were the posts in question created using the legacy editor?

**Comment by PannaLisenka** [comment]
Not sure – no idea what legacy editor is. These were the posts I reblogged using option + R, created using the Post to Tumblr Mozilla extension, or just the regular editor that opens after clicking the pencil icon in the upper right corner on the homepage. Although I discovered that there is one kind of post I can actually quicktag; text post made using the regular editor. Quotes, photo posts, links, chats, audio or video posts still can't be quicktagged. Hope this helps.

**Comment by PannaLisenka** [comment]
Sorry, misclick.

**Comment by AprilSylph** [comment]
> created using the Post to Tumblr Mozilla extension

That uses the legacy editor. From everything else you describe, you're using the legacy editor on the main site, too. There's a "LEGACY" toggle in the top-right of the screen when the editor is open.

**Comment by marcustyphoon** [comment]
![beta compose with arrow](https://user-images.githubusercontent.com/8336245/215205108-aeac7651-5e12-41e6-ad59-e6d11dbcba5d.png)

**Comment by AprilSylph** [comment]
Closing in favour of #965; this is expected behaviour, so technically it would be an enhancement to "fix" this.
