### ISSUE TITLE
Anti Capitalism - update for new ad/purchase buttons

### ISSUE THREAD

**Issue by Skeithh** [AprilSylph/XKit-Rewritten#943]
### Concept

Multiple features have been added to the site to direct you towards buying crap since the implementation of anti-capitalism, and the extension has not kept up with these additions. here's a list of capitalist features i'd appreciate being able to disable or hide using anti-capitalism:

- Tumblrmart icon & its NEW blob
- go ad-free button in the account dropdown
- blue checkmark button in the account dropdown
- live streaming credits button in the account dropdown

**Comment by marcustyphoon** [comment]
I knew we should have renamed the script to "adblocker" or something.

Here's code to hide the "new" badge on the tumblrmart icon:

Stylus:
```css
.KTRcB > .BPf9u + .O42NY {
  display: none;
}
```

uBlock Origin:
```
! 2023-01-26 https://www.tumblr.com
www.tumblr.com##.KTRcB > .BPf9u + .O42NY
```

Anyway, we won't do this. The ability to buy features is part of the site. Sadly, we live in a society where capitalism is required to pay for servers and developers.

**Comment by dogheartedly** [comment]
@Skeithh Here's a quick ublock filter workaround I use, though I can't guarantee it'll work on yours. Removes the "new" popup, the market button, and then the ad-free/checkmark/credits menu options respectively.

Add this to "My filters" in your uBlock settings:
```
! 2023-01-27 https://www.tumblr.com
www.tumblr.com##.BPf9u + .O42NY
www.tumblr.com##div.KTRcB:nth-of-type(4)
www.tumblr.com##li.QKL2M.ywBwc.IYrO9:nth-of-type(4)
www.tumblr.com##li.QKL2M.ywBwc.IYrO9:nth-of-type(5)
www.tumblr.com##li.QKL2M.ywBwc.IYrO9:nth-of-type(6)
```
