### ISSUE TITLE
Quick Reblog mobile: something other than hover state

### ISSUE THREAD

**Issue by taracdia** [AprilSylph/XKit-Rewritten#946]
### Concept

It would be nice if for mobile there was a different way of triggering the quick Reblog since we can't hover over it. At the moment we can long click the button and then have to dismiss the open in new page dialog or just click it and then we can't even use quick reblog because the normal modal covers it

**Comment by marcustyphoon** [comment]
Duplicate of #791, I think!

**Comment by taracdia** [comment]
You're right! I didn't see it. Thanks!

**Comment by marcustyphoon** [comment]
In theory, as of 0.21.3 a long press should now work... some of the time... sort of?

**Comment by taracdia** [comment]
Yeah it kinda of does, thanks!
