### ISSUE TITLE
Quick Reblog not highlighting all reblogged posts

### ISSUE THREAD

**Issue by asshuka** [AprilSylph/XKit-Rewritten#95]
- The browser I'm using is: Firefox
- My browser version is: 86.0.1
- My XKit Rewritten version is: 0.2.1
---
Quick Reblog does highlight the reblog button right after reblogging, but when you refresh or navigate away from the page, it goes back to the default color. Curiously, the first reblogged post of the page is properly highlighted. I've tested across different Tumblr palettes, as well with Palettes for Tumblr disabled.

**Comment by AprilSylph** [comment]
unable to reproduce on Firefox 86.0.1 (64-bit). could you upload your configuration (from the Backup tab) here for further testing? GitHub should allow you to attach the .json file

**Comment by asshuka** [comment]
Unfortunately it doesn't! I just renamed the file to stick a .txt on it, hopefully file is still usable after re-renaming 🙇‍♀️
[XKit Payload 1615762347022.json.txt](https://github.com/AprilSylph/XKit-Rewritten/files/6138480/XKit.Payload.1615762347022.json.txt)

**Comment by AprilSylph** [comment]
still unable to reproduce using this configuration on Firefox 86. could you try spinning up a new Firefox profile (via about:profiles) and seeing if the issue still persists there?

**Comment by AprilSylph** [comment]
nevermind, i think i've just been able to reproduce this; my guess is that loading new posts while reblogging a post can cause data to be overwritten. i'll need to rethink how `quick_reblog.alreadyRebloggedList` is handled in order to make it more reliable.
