### ISSUE TITLE
Scroll to Bottom: Button can vanish

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#975]
### Platform

MacOS 10.15.7 x86

### Browser

Ungoogled Chromium v110.0.5481.100

### Addon version

master (actually 945)

### Details

If one hard-loads an "embedded blog view" page (e.g. https://www.tumblr.com/april), then soft-navigates to another location, the Tumblr React code doesn't remove the `isPeeprShowing` css class on the `lowerRightContentContainer` element, and so the scroll to bottom button is gone.

This is a redpop bug, but if it persists we could mitigate it.

(By the way, do you still think that activating scroll to bottom on a blog page has a higher chance of getting one spam-flagged than activating it somewhere else, e.g. #488? One way to fix this is just to not hide the thing on embedded blog view, right? Actually there might be a UI inconsistency if you do that, I forget now.)

**Comment by AprilSylph** [comment]
> do you still think that activating scroll to bottom on a blog page has a higher chance of getting one [rate-limited] than activating it somewhere else[...]?

I dunno, I never thought about why I saw the rate-limiting that I did. Try it for yourself, see if it still happens. If it doesn't, a temporary rate limit isn't permanently harmful to the account (AFAIK).

**Comment by marcustyphoon** [comment]
Hm, yeah, hard to say. I'm currently 2100 posts down your blog and nothing seemed to happen.
