### ISSUE TITLE
Rename control panel title attr to "XKit Rewritten"

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/XKit-Rewritten#988]
### Concept

I have seen a few people referring to XKit Rewritten in a context in which they are informing people about its existence as "XKit Control Panel." 

I can think of no way that this could occur other than the mouseover tooltip text on the control button being "XKit Control Panel" while all of the other web extensions I know of use that tooltip text to display the name of their extension. I think it would be clearer to make the change to do the same thing.

**Comment by marcustyphoon** [comment]
(poking this for comment)

**Comment by AprilSylph** [comment]
I thought it would be better if the browser action button has a title that describes what it does or what it opens, but if no other extension does that then it indeed only serves to cause confusion
