### ISSUE TITLE
Tweaks: Ability to completely hide filtered posts

### ISSUE THREAD

**Issue by asshuka** [AprilSylph/XKit-Rewritten#99]
Tumblr's built-in blacklist works great, but how the filtered post looks feels a little intrusive. It would be great to have an option to trim it:
![210316_20-08-02](https://user-images.githubusercontent.com/80346620/111314429-fb568d00-8693-11eb-86b1-6afcd8b40979.png)
![210316_20-08-02_2](https://user-images.githubusercontent.com/80346620/111314433-fc87ba00-8693-11eb-99fb-ec48031795ed.png)
and/or have an option to hide the post completely.

**Comment by invalidCards** [comment]
@asshuka please see if this tweak meets your expectations:
![afbeelding](https://user-images.githubusercontent.com/842080/111319346-2e822780-8666-11eb-8d7e-d6e39cd9f3c6.png)

**Comment by asshuka** [comment]
Yes. Somehow I didn't put two and two together because I literally just used the filter option for the first time I am very sorry,
Still I hope hiding the filtered post altogether stands as a suggestion!
