### ISSUE TITLE
Hide Tip Button

### ISSUE THREAD

**Issue by StellarPluto** [AprilSylph/XKit-Rewritten#990]
### Concept

Add an option to hide Tip button that is next to a blog name when a post is on the dashboard. Maybe add this as a default part of Anti-Capitalism?

**Comment by marcustyphoon** [comment]
We don't plan to do this, I believe. (If it wouldn't lead to user confusion, I would love to retroactively rename anti-capitalism to something about blocking ads/promotional content; we live in a society where money can be exchanged for goods and services!)
